Repository DataDog/datadog-operator, pull requests merged in 2019-12, with the labels that each got.

#5 Add Pod Disruption Budget to the Datadog operator
  chart/datadog-operator/templates/pod_disruption_budget.yaml
Labels: enhancement

#6 Make component synchronization more robust
  pkg/apis/datadoghq/v1alpha1/test/new.go
  pkg/controller/datadogagentdeployment/clusteragent.go
  pkg/controller/datadogagentdeployment/datadogagentdeployment_controller_test.go
Labels: enhancement

#9 [Fix] Update CR status after disabling cluster agent and clc runners
  pkg/controller/datadogagentdeployment/clusteragent.go
  pkg/controller/datadogagentdeployment/clusterchecksrunner.go
Labels: bug

#11 Add PodDisruptionBudget management
  Makefile
  chart/datadog-operator/templates/role.yaml
  deploy/role.yaml
  docs/how-to-contribute.md
  docs/quick-start.md
  examples/datadog-agent-with-clusteragent.yaml
  examples/datadog-agent-with-dca-clusterchecksrunner.yaml
  examples/datadog-agent-with-tolerations.yaml
  examples/datadog-agent.yaml
  go.sum
  pkg/controller/datadogagentdeployment/clusteragent.go
  pkg/controller/datadogagentdeployment/clusterchecksrunner.go
  pkg/controller/datadogagentdeployment/datadogagentdeployment_controller.go
  pkg/controller/datadogagentdeployment/datadogagentdeployment_controller_test.go
  pkg/controller/datadogagentdeployment/poddisruptionbudget.go
  pkg/controller/datadogagentdeployment/utils.go
Labels: enhancement

#12 Add proper status in `get dad` display
  pkg/apis/datadoghq/v1alpha1/datadogagentdeployment_types.go
  pkg/controller/datadogagentdeployment/agent.go
  pkg/controller/datadogagentdeployment/clusteragent.go
  pkg/controller/datadogagentdeployment/clusterchecksrunner.go
  pkg/controller/datadogagentdeployment/datadogagentdeployment_controller.go
  pkg/controller/datadogagentdeployment/utils.go
Labels: enhancement, wip
