Repository DataDog/datadog-operator, pull requests merged in 2020-02, with the labels that each got.

#30 Refactor cluster agent tests for maintainability
  pkg/controller/datadogagent/clusteragent_test.go
  pkg/controller/datadogagent/datadogagent_controller_test.go
Labels: enhancement

#32 Documentation refactoring
  .github/CODEOWNERS
  README.md
  docs/cluster_agent_setup.md
  docs/custom_check.md
  docs/data_collected.md
  docs/getting_started.md
  docs/how-to-contribute.md
  docs/quick-start.md
  examples/datadog-agent-all.yaml
  examples/datadog-agent-with-clusteragent.yaml
  examples/datadog-agent-with-dca-clusterchecksrunner.yaml
  examples/datadog-agent-with-tolerations.yaml
  examples/datadog-agent.yaml
Labels: documentation

#37 Update codeowners
  .github/CODEOWNERS
Labels: documentation

#36 Reconcile() updates now MetricsForwarder.Status in DatadogAgentStatus
  pkg/controller/datadogagent/datadogagent_controller.go
  pkg/controller/datadogagent/datadogagent_controller_test.go
  pkg/controller/datadogagent/secret.go
  pkg/controller/utils/condition/condition.go
  pkg/controller/utils/datadog/forwarders_manager.go
  pkg/controller/utils/datadog/metrics_forwarder.go
Labels: bug

#35 Small bugfixes and OLM changes to be able to publish it in a registry
  deploy/clusterrole.yaml
  deploy/crds/datadoghq.com_datadogagents_crd.yaml
  deploy/olm-catalog/datadog-operator/0.1.1/datadog-operator.v0.1.1.clusterserviceversion.yaml
  deploy/olm-catalog/datadog-operator/0.1.1/datadoghq.com_datadogagents_crd.yaml
  deploy/olm-catalog/datadog-operator/datadog-operator.package.yaml
  deploy/role.yaml
  examples/datadog-agent-all.yaml
  examples/datadog-agent-openshift.yaml
  pkg/apis/datadoghq/v1alpha1/const.go
  pkg/apis/datadoghq/v1alpha1/datadogagent_default.go
  pkg/apis/datadoghq/v1alpha1/datadogagent_types.go
  pkg/apis/datadoghq/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/datadoghq/v1alpha1/zz_generated.openapi.go
  pkg/controller/datadogagent/agent_test.go
  pkg/controller/datadogagent/clusteragent.go
  pkg/controller/datadogagent/utils.go
Labels: enhancement

#40 introduce golangci configuration
  .gitlab-ci.yml
  .golangci.toml
  pkg/apis/datadoghq/v1alpha1/const.go
  pkg/apis/datadoghq/v1alpha1/datadogagent_default.go
  pkg/apis/datadoghq/v1alpha1/datadogagent_types.go
  pkg/apis/datadoghq/v1alpha1/test/new.go
  pkg/controller/datadogagent/agent.go
  pkg/controller/datadogagent/agent_test.go
  pkg/controller/datadogagent/clusteragent.go
  pkg/controller/datadogagent/clusteragent_metricsserver.go
  pkg/controller/datadogagent/clusteragent_test.go
  pkg/controller/datadogagent/clusterchecksrunner.go
  pkg/controller/datadogagent/common_configmap.go
  pkg/controller/datadogagent/common_rbac.go
  pkg/controller/datadogagent/const.go
  pkg/controller/datadogagent/datadogagent_controller.go
  pkg/controller/datadogagent/datadogagent_controller_test.go
  pkg/controller/datadogagent/poddisruptionbudget.go
  pkg/controller/datadogagent/secret.go
  pkg/controller/datadogagent/service.go
  pkg/controller/datadogagent/utils.go
  pkg/controller/utils/comparison/comparison.go
  pkg/controller/utils/condition/condition.go
  pkg/controller/utils/datadog/forwarders_manager.go
  pkg/controller/utils/datadog/metrics_forwarder.go
  pkg/controller/utils/shared_utils.go
  pkg/secrets/secrets.go
  version/version.go
Labels: enhancement

#43 [WIP] Add missing fields in DatadogAgent CRD
  deploy/crds/datadoghq.com_datadogagents_crd.yaml
  pkg/apis/datadoghq/v1alpha1/datadogagent_types.go
  pkg/apis/datadoghq/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/datadoghq/v1alpha1/zz_generated.openapi.go
  pkg/controller/datadogagent/clusteragent.go
  pkg/controller/datadogagent/clusterchecksrunner.go
  pkg/controller/datadogagent/utils.go
Labels: enhancement
