Repository DataDog/datadog-operator, pull requests merged in 2020-03, with the labels that each got.

#50 Change Baklava to documentation team
  .github/CODEOWNERS
Labels: documentation

#46 Removing usage disclaimer
  README.md
Labels: documentation

#42 [kubectl plugin] Add more commands
  LICENSE
  cmd/kubectl-datadog/agent/agent/agent.go
  cmd/kubectl-datadog/agent/check/check.go
  cmd/kubectl-datadog/agent/check/check_test.go
  cmd/kubectl-datadog/agent/check/types.go
  cmd/kubectl-datadog/agent/upgrade/upgrade.go
  cmd/kubectl-datadog/agent/upgrade/upgrade_test.go
  cmd/kubectl-datadog/clusteragent/clusteragent/clusteragent.go
  cmd/kubectl-datadog/clusteragent/leader/leader.go
  cmd/kubectl-datadog/clusteragent/upgrade/upgrade.go
  cmd/kubectl-datadog/clusteragent/upgrade/upgrade_test.go
  cmd/kubectl-datadog/datadog/datadog.go
  cmd/kubectl-datadog/flare/flare.go
  cmd/kubectl-datadog/flare/redactor.go
  cmd/kubectl-datadog/flare/replacer.go
  cmd/kubectl-datadog/flare/replacer_test.go
  cmd/kubectl-datadog/get/get.go
  cmd/kubectl-datadog/main.go
  datadog.yaml
  deploy/crds/datadoghq.com_datadogagents_crd.yaml
  pkg/apis/datadoghq/v1alpha1/datadogagent_types.go
  pkg/apis/datadoghq/v1alpha1/zz_generated.openapi.go
  pkg/controller/datadogagent/utils.go
  pkg/plugin/common/options.go
  pkg/plugin/common/utils.go
  pkg/plugin/common/utils_test.go
Labels: enhancement

#52 fix agent status update
  pkg/controller/datadogagent/agent.go
Labels: bug

#54 fix DatadogAgent.Status when EDS activated
  chart/datadog-operator/templates/role.yaml
  deploy/operator.yaml
  deploy/role.yaml
  pkg/controller/datadogagent/agent.go
Labels: bug

#58 [Plugin] fix component status
  cmd/kubectl-datadog/get/get.go
Labels: bug, component/plugin

#59 change probes port, make it configurable
  chart/datadog-operator/templates/deployment.yaml
  chart/datadog-operator/values.yaml
  cmd/manager/main.go
  deploy/operator.yaml
Labels: component/controler

#60 Add SecCompProfileName for system-probe
  deploy/crds/datadoghq.com_datadogagents_crd.yaml
  pkg/apis/datadoghq/v1alpha1/const.go
  pkg/apis/datadoghq/v1alpha1/datadogagent_types.go
  pkg/apis/datadoghq/v1alpha1/test/new.go
  pkg/apis/datadoghq/v1alpha1/zz_generated.openapi.go
  pkg/controller/datadogagent/datadogagent_controller_test.go
  pkg/controller/datadogagent/utils.go
Labels: component/controller

#56 Prepare release tooling
  .goreleaser.yml
  datadog.yaml
Labels: component/plugin

#61 update system-probe seccomp profil
  pkg/controller/datadogagent/systemprobe.go
Labels: bug, component/controller

#63 [Plugin] Add DD_LOG_LEVEL=off to get agent status
  cmd/kubectl-datadog/agent/check/check.go
Labels: bug, component/plugin
