Repository DataDog/datadog-operator, pull requests merged in 2020-12, with the labels that each got.

#176 Update datadog-agent-apm.yaml
  examples/datadog-agent-apm.yaml
Labels: bug

#186 Fix process-agent and trace-agent custom-config configuration
  api/v1alpha1/test/new.go
  controllers/datadogagent/agent.go
  controllers/datadogagent/agent_test.go
  controllers/datadogagent/clusteragent.go
  controllers/datadogagent/clusterchecksrunner.go
  controllers/datadogagent/clusterchecksrunner_test.go
  controllers/datadogagent/systemprobe.go
  controllers/datadogagent/utils.go
Labels: bug, component/controller

#185 Fix missing OpenShift RBAC to use SCC
  bundle/manifests/datadog-operator.clusterserviceversion.yaml
  bundle/manifests/datadoghq.com_datadogmetrics.yaml
  config/manifests/bases/datadog-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/datadogagent_controller.go
Labels: bug

#178 [datadogfeature] adding orchestrator explorer as a feature
  api/v1alpha1/datadogagent_default.go
  api/v1alpha1/datadogagent_types.go
  api/v1alpha1/test/new.go
  api/v1alpha1/zz_generated.deepcopy.go
  api/v1alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  config/samples/datadog-agent-all.yaml
  config/samples/datadog-agent-with-clusteragent-with-orchestrator.yaml
  controllers/datadogagent/agent_test.go
  controllers/datadogagent/clusteragent.go
  controllers/datadogagent/clusteragent_test.go
  controllers/datadogagent/const.go
  controllers/datadogagent/controller_test.go
  controllers/datadogagent/orchestrator/envs.go
  controllers/datadogagent/utils.go
  controllers/datadogagent_controller_test.go
  controllers/testutils/new.go
  docs/configuration.md
  examples/datadog-agent-all.yaml
  examples/datadog-agent-with-dca-with-orchestrator-explorer.yaml
Labels: documentation, enhancement

#187 Update getting_started.md
  docs/getting_started.md
Labels: bug, documentation

#189 Fix Daemonset hash annotation generation
  api/v1alpha1/const.go
  api/v1alpha1/test/new.go
  controllers/datadogagent/agent.go
  controllers/datadogagent/agent_test.go
  controllers/datadogagent/clusteragent.go
  controllers/datadogagent/clusterchecksrunner.go
  controllers/datadogagent/common_configmap.go
  controllers/datadogagent/controller_test.go
  controllers/datadogagent/service.go
  pkg/controller/utils/comparison/comparison.go
Labels: bug, component/controller

#192 Fix formatting of logs coming from client-go
  go.mod
  main.go
  pkg/klog/klog.go
Labels: bug

#193 Fix DD_SITE env variable integration
  controllers/datadogagent/agent_test.go
  controllers/datadogagent/clusteragent.go
  controllers/datadogagent/clusteragent_test.go
  controllers/datadogagent/clusterchecksrunner.go
  controllers/datadogagent/clusterchecksrunner_test.go
  controllers/datadogagent/utils.go
Labels: bug, component/controller

#183 Introducing support for kube_state_metrics core.
  .gitignore
  api/v1alpha1/const.go
  api/v1alpha1/datadogagent_default.go
  api/v1alpha1/datadogagent_types.go
  api/v1alpha1/datadogagent_validation.go
  api/v1alpha1/test/new.go
  api/v1alpha1/zz_generated.deepcopy.go
  api/v1alpha1/zz_generated.openapi.go
  bundle/manifests/datadog-operator.clusterserviceversion.yaml
  bundle/manifests/datadoghq.com_datadogagents.yaml
  bundle/manifests/datadoghq.com_datadogmonitors.yaml
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  controllers/datadogagent/clusteragent.go
  controllers/datadogagent/clusteragent_test.go
  controllers/datadogagent/clusterchecksrunner_rbac.go
  controllers/datadogagent/kubestatemetrics.go
  controllers/datadogagent/kubestatemetrics_test.go
  controllers/datadogagent/testdata/ksm_clusterrole.yaml
  controllers/datadogagent/utils.go
  controllers/datadogagent/utils_test.go
  docs/kubernetes_state_metrics.md
Labels: component/controller, enhancement

#194 Adding missing doc and lint test
  controllers/datadogagent/clusteragent_test.go
  docs/configuration.md
Labels: documentation

#196 [SB] Add secrets helper
  Dockerfile
  cmd/helpers/main.go
  cmd/helpers/secrets/secrets.go
  docs/secret_management.md
  main.go
  pkg/secrets/secrets.go
  pkg/secrets/types.go
  scripts/readsecret.sh
Labels: component/controller, enhancement, feature request

#190 Fix issues with Secret management
  controllers/datadogagent/clusteragent.go
  controllers/datadogagent/secret.go
Labels: bug, component/controller

#197 allow dd credentials to be set in operator
  api/v1alpha1/datadogagent_types.go
  api/v1alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  controllers/datadogagent/secret.go
  controllers/datadogagent/secret_test.go
  controllers/datadogagent_controller_test.go
  controllers/testutils/new.go
  pkg/config/config.go
  pkg/controller/utils/datadog/metrics_forwarder.go
  pkg/controller/utils/datadog/metrics_forwarder_test.go
Labels: component/controller, enhancement

#181 Caroline/add command to plugin to list datadogmetrics
  cmd/kubectl-datadog/datadog/datadog.go
  cmd/kubectl-datadog/metrics/get/get.go
  cmd/kubectl-datadog/metrics/metrics.go
Labels: enhancement

#198 Extend the DatadogAgent CR example
  config/samples/datadog-agent-all.yaml
  config/samples/datadog-operator-hub-example.yaml
  config/samples/kustomization.yaml
Labels: component/olm, enhancement
