Repository DataDog/datadog-operator, pull requests merged in 2020-09, with the labels that each got.

#145 Fix crds generation
  deploy/crds/v1/datadoghq.com_datadogagents_crd.yaml
  deploy/crds/v1beta1/datadoghq.com_datadogagents_crd.yaml
Labels: bug

#143 [security-agent] Configuration settings for security agent
  deploy/crds/datadoghq.com_datadogagents_crd.yaml
  deploy/crds/v1/datadoghq.com_datadogagents_crd.yaml
  deploy/crds/v1beta1/datadoghq.com_datadogagents_crd.yaml
  go.test.sh
  pkg/apis/datadoghq/v1alpha1/const.go
  pkg/apis/datadoghq/v1alpha1/datadogagent_types.go
  pkg/apis/datadoghq/v1alpha1/test/new.go
  pkg/apis/datadoghq/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/datadoghq/v1alpha1/zz_generated.openapi.go
  pkg/controller/datadogagent/agent_test.go
  pkg/controller/datadogagent/clusteragent.go
  pkg/controller/datadogagent/clusteragent_test.go
  pkg/controller/datadogagent/datadogagent_controller_test.go
  pkg/controller/datadogagent/systemprobe.go
  pkg/controller/datadogagent/utils.go
  test/e2e/datadogagent_test.go
Labels: component/controller, enhancement

#146 Add DatadogMetrics example in OLM
  hack/release/cluster-service-version-patch.yaml
Labels: bug, component/olm

#147 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#144 Fix pod anti affinity
  pkg/controller/datadogagent/clusteragent.go
  pkg/controller/datadogagent/clusteragent_test.go
  pkg/controller/datadogagent/clusterchecksrunner.go
  pkg/controller/datadogagent/clusterchecksrunner_test.go
  pkg/controller/datadogagent/utils.go
Labels: bug, component/controller

#149 [system-probe] Add missing system probe settings for parity with helm chart
  deploy/crds/datadoghq.com_datadogagents_crd.yaml
  deploy/crds/v1/datadoghq.com_datadogagents_crd.yaml
  deploy/crds/v1beta1/datadoghq.com_datadogagents_crd.yaml
  pkg/apis/datadoghq/v1alpha1/const.go
  pkg/apis/datadoghq/v1alpha1/datadogagent_types.go
  pkg/apis/datadoghq/v1alpha1/test/new.go
  pkg/apis/datadoghq/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/datadogagent/agent_test.go
  pkg/controller/datadogagent/systemprobe.go
  pkg/controller/datadogagent/utils.go
Labels: enhancement

#150 Actually use `securityContext` attribute as PodSecurityContext
  deploy/crds/datadoghq.com_datadogagents_crd.yaml
  deploy/crds/v1/datadoghq.com_datadogagents_crd.yaml
  deploy/crds/v1beta1/datadoghq.com_datadogagents_crd.yaml
  pkg/apis/datadoghq/v1alpha1/datadogagent_types.go
  pkg/apis/datadoghq/v1alpha1/test/new.go
  pkg/apis/datadoghq/v1alpha1/utils.go
  pkg/apis/datadoghq/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/datadogagent/datadogagent_controller_test.go
  pkg/controller/datadogagent/utils.go
Labels: bug

#151 Fix RBAC with compliance and admission controller
  chart/datadog-operator/templates/clusterrole.yaml
  chart/datadog-operator/templates/role.yaml
  deploy/clusterrole.yaml
  deploy/role.yaml
  examples/datadog-agent-all.yaml
  pkg/apis/datadoghq/v1alpha1/const.go
  pkg/controller/datadogagent/clusteragent.go
  pkg/controller/datadogagent/datadogagent_controller_test.go
Labels: bug

#155 Always mount `config` volume when security agent is enabled
  pkg/controller/datadogagent/agent_test.go
  pkg/controller/datadogagent/utils.go
Labels: bug, component/controller
