Repository DataDog/datadog-operator, pull requests merged in 2020-08, with the labels that each got.

#133 add github workflow for pr linter
  .github/workflows/pr-linter.yml
Labels: enhancement

#134 Activate push to latest when tag
  .gitlab-ci.yml
Labels: bug

#138 CSV version 0.2.3 allowing agent (not operator) to use SCCs on OpenShift
  deploy/clusterrole.yaml
  deploy/clusterrole_binding.yaml
  deploy/olm-catalog/datadog-operator/0.2.3/datadog-operator.v0.2.3.clusterserviceversion.yaml
  deploy/olm-catalog/datadog-operator/0.2.3/datadoghq.com_datadogagents_crd.yaml
  deploy/olm-catalog/datadog-operator/datadog-operator.package.yaml
  deploy/service_account.yaml
Labels: bug

#139 Remove DD_HOSTNAME from agent and move it back to check runner
  Makefile
  pkg/controller/datadogagent/agent_test.go
  pkg/controller/datadogagent/clusterchecksrunner.go
  pkg/controller/datadogagent/clusterchecksrunner_test.go
  pkg/controller/datadogagent/utils.go
Labels: bug

#140 [system-probe] Update seccomp profile and capabilities for system probe
  pkg/controller/datadogagent/systemprobe.go
  pkg/controller/datadogagent/utils.go
Labels: bug, component/controller

#141 Fix generate-olm-bundle.sh to only package one version
  hack/generate-olm-bundle.sh
Labels: bug

#142 Support wpa configuration
  chart/datadog-operator/templates/clusterrole.yaml
  deploy/clusterrole.yaml
  deploy/crds/datadoghq.com_datadogagents_crd.yaml
  pkg/apis/datadoghq/v1alpha1/const.go
  pkg/apis/datadoghq/v1alpha1/datadogagent_types.go
  pkg/apis/datadoghq/v1alpha1/test/new.go
  pkg/apis/datadoghq/v1alpha1/zz_generated.openapi.go
  pkg/controller/datadogagent/clusteragent.go
  pkg/controller/datadogagent/clusteragent_test.go
  pkg/controller/datadogagent/datadogagent_controller_test.go
Labels: enhancement
