Repository DataDog/datadog-operator, pull requests merged in 2020-06, with the labels that each got.

#100 Add hostPort for Agent
  .github/workflows/main.yml
  pkg/apis/datadoghq/v1alpha1/const.go
  pkg/apis/datadoghq/v1alpha1/datadogagent_types.go
  pkg/apis/datadoghq/v1alpha1/test/new.go
  pkg/controller/datadogagent/agent_test.go
  pkg/controller/datadogagent/utils.go
Labels: enhancement

#108 Fix helm chart
  chart/datadog-operator/templates/deployment.yaml
Labels: bug

#109 Use 8443 as default port for the external metrics provider
  deploy/crds/datadoghq.com_datadogagents_crd.yaml
  pkg/apis/datadoghq/v1alpha1/const.go
  pkg/apis/datadoghq/v1alpha1/datadogagent_default.go
  pkg/apis/datadoghq/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/datadoghq/v1alpha1/zz_generated.openapi.go
  pkg/controller/datadogagent/clusteragent.go
  pkg/controller/datadogagent/datadogagent_controller_test.go
  pkg/controller/datadogagent/service.go
Labels: bug

#110 Fix nil pointer when DS Agent disabled
  pkg/controller/datadogagent/systemprobe.go
Labels: bug

#111 Add DatadogMetric support in operator
  chart/datadog-operator/crds/datadoghq.com_datadogmetrics_crd.yaml
  deploy/crds/datadoghq.com_datadogagents_crd.yaml
  examples/datadog-agent-openshift.yaml
  examples/datadog-agent-with-clusteragent.yaml
  examples/datadog-agent-with-dca-clusterchecksrunner.yaml
  pkg/apis/datadoghq/v1alpha1/const.go
  pkg/apis/datadoghq/v1alpha1/datadogagent_default.go
  pkg/apis/datadoghq/v1alpha1/datadogagent_types.go
  pkg/apis/datadoghq/v1alpha1/test/new.go
  pkg/apis/datadoghq/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/datadoghq/v1alpha1/zz_generated.openapi.go
  pkg/controller/datadogagent/clusteragent.go
  pkg/controller/datadogagent/clusteragent_test.go
  pkg/controller/datadogagent/utils.go
Labels: component/controller

#112 update EDS dependency
  LICENSE-3rdparty.csv
  deploy/crds/datadoghq.com_datadogagents_crd.yaml
  go.mod
  go.sum
  pkg/controller/datadogagent/datadogagent_controller.go
  vendor/github.com/datadog/extendeddaemonset/LICENSE
  vendor/github.com/datadog/extendeddaemonset/NOTICE
  vendor/github.com/datadog/extendeddaemonset/pkg/apis/datadoghq/v1alpha1/extendeddaemonset_types.go
  vendor/github.com/datadog/extendeddaemonset/pkg/apis/datadoghq/v1alpha1/extendeddaemonsetsetting_types.go
  vendor/github.com/datadog/extendeddaemonset/pkg/apis/datadoghq/v1alpha1/extendednode_types.go
  vendor/github.com/datadog/extendeddaemonset/pkg/apis/datadoghq/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/datadog/extendeddaemonset/pkg/apis/datadoghq/v1alpha1/zz_generated.openapi.go
  vendor/modules.txt
Labels: component/controller, enhancement

#113 Fix logs configuration defaulting
  pkg/apis/datadoghq/v1alpha1/datadogagent_default.go
Labels: bug, component/controller
