Repository DataDog/datadog-operator, pull requests merged in 2020-11, with the labels that each got.

#165 Re-add handling of WATCH_NAMESPACE following migration to Operator SDK 1.0
  main.go
  pkg/config/config.go
Labels: bug

#168 Fix scheduling of system-probe related checks in the core agent and missing permissions for network policies
  Makefile
  config/manager/kustomization.yaml
  config/rbac/role.yaml
  controllers/datadogagent/agent_test.go
  controllers/datadogagent/clusteragent.go
  controllers/datadogagent/utils.go
  controllers/datadogagent_controller.go
Labels: bug

#169 Fix compliance CheckInterval set in DCA/SecAgent
  controllers/datadogagent/clusteragent.go
  controllers/datadogagent/utils.go
Labels: bug

#170 Fix system-probe and logs volumeMount conflict
  api/v1alpha1/const.go
  controllers/datadogagent/agent_test.go
  controllers/datadogagent/systemprobe.go
Labels: bug

#171 Correctly apply Cluster Checks Runner NetworkPolicy
  controllers/datadogagent/clusterchecksrunner.go
Labels: bug

#173 Fix naming of GroupVersion to be in line with OperatorSDK v1
  LICENSE-3rdparty.csv
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/test/new.go
  cmd/kubectl-datadog/agent/upgrade/upgrade_test.go
  cmd/kubectl-datadog/clusteragent/upgrade/upgrade_test.go
  controllers/datadogagent/clusteragent.go
  controllers/datadogagent/clusteragent_test.go
  controllers/datadogagent/controller_test.go
Labels: bug

#166 [makefile] add helper functions
  Makefile
  docs/how-to-contribute.md
Labels: documentation, enhancement

#167 [datadogfeature] adding orchestrator explorer as a feature
  api/v1alpha1/datadogagent_default.go
  api/v1alpha1/datadogagent_types.go
  api/v1alpha1/test/new.go
  api/v1alpha1/zz_generated.deepcopy.go
  api/v1alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  config/manager/kustomization.yaml
  config/samples/datadog-agent-all.yaml
  config/samples/datadog-agent-with-clusteragent-with-orchestrator.yaml
  controllers/datadogagent/agent_test.go
  controllers/datadogagent/clusteragent.go
  controllers/datadogagent/clusteragent_test.go
  controllers/datadogagent/const.go
  controllers/datadogagent/controller_test.go
  controllers/datadogagent/orchestrator/envs.go
  controllers/datadogagent/utils.go
  controllers/datadogagent_controller_test.go
  controllers/testutils/new.go
  docs/configuration.md
  examples/datadog-agent-all.yaml
  examples/datadog-agent-with-dca-with-orchestrator-explorer.yaml
Labels: documentation, enhancement

#179 [DatadogMonitor] add scaffolding and basic crd
  PROJECT
  api/v1alpha1/datadogmonitor_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  api/v1alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogmonitors.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogmonitors.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_datadogmonitors.yaml
  config/crd/patches/webhook_in_datadogmonitors.yaml
  config/rbac/datadogmonitor_editor_role.yaml
  config/rbac/datadogmonitor_viewer_role.yaml
  config/samples/datadoghq_v1alpha1_datadogmonitor.yaml
  config/samples/kustomization.yaml
  controllers/datadogmonitor_controller.go
  main.go
Labels: enhancement

#180 Fix missing mount of system-probe config in process agent and remove s6 from CLC (aligned on Helm chart)
  controllers/datadogagent/clusterchecksrunner.go
  controllers/datadogagent/clusterchecksrunner_test.go
  controllers/datadogagent/utils.go
Labels: bug

#182 [ddm] Add maxAge to DatadogMetric CRD
  api/v1alpha1/datadogmetric_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/v1/datadoghq.com_datadogmetrics.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogmetrics.yaml
Labels: enhancement
