Repository DataDog/datadog-operator, pull requests merged in 2020-10, with the labels that each got.

#154 collectEvents at Cluster Agent level
  deploy/crds/datadoghq.com_datadogagents_crd.yaml
  deploy/crds/v1/datadoghq.com_datadogagents_crd.yaml
  docs/configuration.md
  pkg/apis/datadoghq/v1alpha1/datadogagent_default.go
  pkg/apis/datadoghq/v1alpha1/datadogagent_types.go
  pkg/controller/datadogagent/clusteragent.go
  pkg/controller/datadogagent/clusteragent_test.go
Labels: component/controller, enhancement

#156 Fix helm chart path
  docs/installation.md
Labels: documentation

#158 Fix compliance checkInterval duration type
  deploy/crds/datadoghq.com_datadogagents_crd.yaml
  deploy/crds/v1/datadoghq.com_datadogagents_crd.yaml
  deploy/crds/v1beta1/datadoghq.com_datadogagents_crd.yaml
  pkg/apis/datadoghq/v1alpha1/datadogagent_types.go
  pkg/apis/datadoghq/v1alpha1/test/new.go
  pkg/apis/datadoghq/v1alpha1/zz_generated.deepcopy.go
Labels: bug, component/controller

#159 Update `verify-pr-label-action` GH action to allow contributions from fork
  .github/workflows/pr-linter.yml
Labels: bug, component/olm

#160 Fix missing data in base CSV
  bundle/manifests/datadog-operator.clusterserviceversion.yaml
  bundle/manifests/datadoghq.com_datadogagents.yaml
  config/manifests/bases/datadog-operator.clusterserviceversion.yaml
Labels: component/olm, documentation

#161 Improve test stability
  .github/workflows/pr-linter.yml
  controllers/datadogagent_controller_test.go
Labels: bug, component/controller

#163 Add option to override the API endpoint for the external metrics server
  api/v1alpha1/datadogagent_types.go
  api/v1alpha1/test/new.go
  api/v1alpha1/zz_generated.deepcopy.go
  api/v1alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  controllers/datadogagent/clusteragent.go
  controllers/datadogagent/clusteragent_test.go
  docs/configuration.md
Labels: enhancement

#162 Add the option to create NetworkPolicy for the Agents
  api/v1alpha1/datadogagent_default.go
  api/v1alpha1/datadogagent_types.go
  api/v1alpha1/test/new.go
  api/v1alpha1/zz_generated.deepcopy.go
  api/v1alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  controllers/datadogagent/agent.go
  controllers/datadogagent/clusteragent.go
  controllers/datadogagent/clusterchecksrunner.go
  controllers/datadogagent/common_networkpolicy.go
  controllers/datadogagent/common_rbac.go
  controllers/datadogagent/const.go
  controllers/datadogagent/controller_test.go
  controllers/datadogagent_controller.go
  deploy/crds/datadoghq.com_datadogagents_crd.yaml
  deploy/crds/v1/datadoghq.com_datadogagents_crd.yaml
  deploy/crds/v1beta1/datadoghq.com_datadogagents_crd.yaml
  docs/configuration.md
Labels: enhancement

#117 Update liveness and readiness probes
  api/v1alpha1/const.go
  controllers/datadogagent/agent_test.go
  controllers/datadogagent/clusterchecksrunner.go
  controllers/datadogagent/clusterchecksrunner_test.go
  controllers/datadogagent/utils.go
Labels: enhancement

#164 Fix secret backend command CLI flag
  main.go
  pkg/secrets/secrets.go
Labels: bug
