Repository DataDog/datadog-operator, pull requests merged in 2020-05, with the labels that each got.

#83 Update documentation
  README.md
  docs/getting_started.md
Labels: documentation

#82 Add kubectl datadog plugin doc
  docs/getting_started.md
  docs/kubectl-plugin.md
Labels: component/plugin, documentation, enhancement

#87 Fix olm bundle release
  deploy/olm-catalog/csv-config.yaml
  deploy/olm-catalog/datadog-operator/0.2.0/datadog-operator.v0.2.0.clusterserviceversion.yaml
  deploy/olm-catalog/datadog-operator/0.2.1/datadog-operator.v0.2.1.clusterserviceversion.yaml
  hack/generate-olm-bundle.sh
Labels: bug

#99 [Doc] secret backend documentation
  README.md
  chart/datadog-operator/templates/deployment.yaml
  chart/datadog-operator/values.yaml
  docs/secret_management.md
Labels: documentation, enhancement

#102 Fix DatadogMetric generation with operator-sdk 0.17
  deploy/crds/datadoghq.com_datadogmetrics_crd.yaml
  pkg/apis/datadoghq/v1alpha1/datadogmetric_types.go
  pkg/apis/datadoghq/v1alpha1/zz_generated.openapi.go
Labels: bug
