Repository DataDog/datadog-operator, pull requests merged in 2021-08, with the labels that each got.

#344 Limit release of official branch
  .github/workflows/release.yaml
Labels: bug

#301 Create unit-test helper functions
  controllers/datadogagent/agent_eds_test.go
  controllers/datadogagent/testutils/doc.go
  controllers/datadogagent/testutils/extendeddaemonset_utils.go
  controllers/datadogagent/testutils/metadata_utils.go
  controllers/datadogagent/testutils/podtemplate_utils.go
Labels: enhancement

#345 Fix defaultOverride status update
  controllers/datadogagent/controller.go
Labels: bug, component/controller

#349 Fix cluster-agent defaulting to enable it by default
  api/v1alpha1/datadogagent_default.go
  api/v1alpha1/datadogagent_default_test.go
  api/v1alpha1/test/new.go
  config/manager/manager.yaml
  controllers/datadogagent/agent_test.go
  controllers/datadogagent/controller_test.go
  controllers/datadogagent/utils.go
  controllers/datadogagent_controller_test.go
  controllers/testutils/new.go
  examples/datadogagent/datadog-agent-with-credential-secret.yaml
Labels: bug, component/controller

#350 fix nil pointer panic in system-probe config
  controllers/datadogagent/systemprobe.go
Labels: bug

#351 Improve defaulting when spec.Agent|ClusterAgent empty
  api/v1alpha1/datadogagent_default.go
  api/v1alpha1/datadogagent_default_test.go
  api/v1alpha1/test/new.go
  controllers/datadogagent/clusteragent.go
  controllers/datadogagent/controller.go
  controllers/datadogagent/controller_test.go
  controllers/datadogagent/secret_agent.go
  controllers/datadogagent/secret_test.go
  controllers/datadogagent_controller_test.go
  controllers/testutils/new.go
Labels: bug, component/controller

#352 Fix behaviour change with CLC defaulting
  api/v1alpha1/datadogagent_default.go
Labels: bug

#353 fix clusterrolebinding update
  controllers/datadogagent/agent_rbac.go
  controllers/datadogagent/clusteragent.go
  controllers/datadogagent/clusterchecksrunner_rbac.go
  controllers/datadogagent/common_rbac.go
  controllers/datadogagent/kubestatemetrics.go
  controllers/datadogagent/orchestrator.go
Labels: bug

#355 Standardize image defaulting
  api/v1alpha1/const.go
  api/v1alpha1/datadogagent_default.go
  api/v1alpha1/datadogagent_default_test.go
  api/v1alpha1/datadogagent_types.go
  api/v1alpha1/test/new.go
  api/v1alpha1/zz_generated.openapi.go
  cmd/kubectl-datadog/agent/upgrade/upgrade.go
  cmd/kubectl-datadog/agent/upgrade/upgrade_test.go
  cmd/kubectl-datadog/clusteragent/upgrade/upgrade.go
  cmd/kubectl-datadog/clusteragent/upgrade/upgrade_test.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  controllers/datadogagent/agent_test.go
  controllers/datadogagent/clusteragent.go
  controllers/datadogagent/clusteragent_test.go
  controllers/datadogagent/clusterchecksrunner.go
  controllers/datadogagent/clusterchecksrunner_rbac_test.go
  controllers/datadogagent/clusterchecksrunner_test.go
  controllers/datadogagent/utils.go
  controllers/datadogagent/utils_test.go
  docs/configuration.md
  pkg/defaulting/images.go
  pkg/defaulting/images_test.go
Labels: enhancement, component/controller

#356 [docs/getting_started] Fix kubectl apply command
  docs/getting_started.md
Labels: documentation

#357 [docs/configuration] Fix links to example configs
  docs/configuration.md
  hack/generate-docs/footer.markdown
Labels: documentation

#358 [controllers/datadogagent] Add namespace in "part-of" label
  controllers/datadogagent/agent.go
  controllers/datadogagent/agent_test.go
  controllers/datadogagent/clusteragent.go
  controllers/datadogagent/clusteragent_test.go
  controllers/datadogagent/clusterchecksrunner.go
  controllers/datadogagent/clusterchecksrunner_test.go
  controllers/datadogagent/utils.go
Labels: enhancement

#360 [hack/install-kubebuilder] Fix donwload link
  hack/install-kubebuilder.sh
Labels: bug

#359 [controllers/datadogagent] Ensure ClusterRoles and ClusterRoleBindings are deleted
  controllers/datadogagent/clusteragent.go
  controllers/datadogagent/common_rbac.go
  controllers/datadogagent/common_rbac_test.go
  controllers/datadogagent/controller_test.go
  controllers/datadogagent/finalizer.go
  controllers/datadogagent/finalizer_test.go
Labels: bug, component/controller

#361 [v0.7] Backport clusterRoles and clusterRoleBindings fixes
  controllers/datadogagent/agent.go
  controllers/datadogagent/agent_test.go
  controllers/datadogagent/clusteragent.go
  controllers/datadogagent/clusteragent_test.go
  controllers/datadogagent/clusterchecksrunner.go
  controllers/datadogagent/clusterchecksrunner_test.go
  controllers/datadogagent/common_rbac.go
  controllers/datadogagent/common_rbac_test.go
  controllers/datadogagent/controller_test.go
  controllers/datadogagent/finalizer.go
  controllers/datadogagent/finalizer_test.go
  controllers/datadogagent/utils.go
  hack/install-kubebuilder.sh
Labels: bug

#364 Fix panic in feature override when process or system probe configs are empty
  api/v1alpha1/datadogagent_default.go
Labels: bug, component/controller

#362 Fix runtime security volumes creation
  api/v1alpha1/datadogagent_default.go
  controllers/datadogagent/utils.go
  controllers/testutils/new.go
Labels: bug, component/controller

#366 [README] Fix github actions badge
  README.md
Labels: documentation
