Repository DataDog/datadog-operator, pull requests merged in 2021-03, with the labels that each got.

#249 Fix OLM bundle generation
  bundle-redhat/manifests/datadog-operator-datadog-operator-manager_v1_serviceaccount.yaml
  bundle-redhat/manifests/datadog-operator.clusterserviceversion.yaml
  bundle/manifests/datadog-operator-datadog-operator-manager_v1_serviceaccount.yaml
  bundle/manifests/datadog-operator.clusterserviceversion.yaml
  config/manifests/bases/datadog-operator.clusterserviceversion.yaml
  hack/release/cluster-service-version-patch.yaml
Labels: bug

#250 Fix missing patch for bundle generation
  Makefile
  api/v1alpha1/datadogmonitor_types.go
  api/v1alpha1/zz_generated.openapi.go
  bundle-redhat/manifests/datadog-operator-datadog-operator-manager_v1_serviceaccount.yaml
  bundle-redhat/manifests/datadog-operator.clusterserviceversion.yaml
  bundle-redhat/manifests/datadoghq.com_datadogmonitors.yaml
  bundle/manifests/datadog-operator-datadog-operator-manager_v1_serviceaccount.yaml
  bundle/manifests/datadog-operator.clusterserviceversion.yaml
  bundle/manifests/datadoghq.com_datadogmonitors.yaml
  config/crd/bases/v1/datadoghq.com_datadogmonitors.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogmonitors.yaml
  config/manifests/bases/datadog-operator.clusterserviceversion.yaml
  config/rbac/service_account.yaml
  config/samples/datadog-operator-hub-example.yaml
  hack/patch-bundle-csv-scc.yaml
  hack/patch-bundle.sh
  hack/patch-crds.sh
Labels: bug, component/olm

#251 Fix OLM bundle generation (#249)
  config/manager/kustomization.yaml
  config/manifests/bases/datadog-operator.clusterserviceversion.yaml
  hack/release/cluster-service-version-patch.yaml
Labels: bug, component/olm

#255 Merge back v0.5
  Makefile
  api/v1alpha1/datadogmonitor_types.go
  api/v1alpha1/zz_generated.openapi.go
  bundle-redhat/manifests/datadog-operator.clusterserviceversion.yaml
  bundle-redhat/manifests/datadoghq.com_datadogmonitors.yaml
  bundle/manifests/datadog-operator.clusterserviceversion.yaml
  bundle/manifests/datadoghq.com_datadogmonitors.yaml
  config/crd/bases/v1/datadoghq.com_datadogmonitors.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogmonitors.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/datadog-operator.clusterserviceversion.yaml
  config/rbac/service_account.yaml
  config/samples/datadog-operator-hub-example.yaml
  go.sum
  hack/patch-bundle-csv-scc.yaml
  hack/patch-bundle.sh
  hack/patch-crds.sh
Labels: bug

#254 Fix KSM core RBAC issue with Events
  controllers/datadogagent/clusterchecksrunner_rbac.go
  controllers/datadogagent/clusterchecksrunner_rbac_test.go
  controllers/datadogagent/kubestatemetrics.go
  controllers/datadogagent/testdata/ksm_clusterrole.yaml
  go.sum
Labels: bug, component/controller

#257 Update license
  api/v1alpha1/const.go
  api/v1alpha1/datadogagent_default.go
  api/v1alpha1/datadogagent_default_test.go
  api/v1alpha1/datadogagent_types.go
  api/v1alpha1/datadogmetric_types.go
  api/v1alpha1/doc.go
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/test/new.go
  api/v1alpha1/utils.go
  api/v1alpha1/zz_generated.deepcopy.go
  api/v1alpha1/zz_generated.openapi.go
  controllers/datadogagent/agent.go
  controllers/datadogagent/agent_rbac.go
  controllers/datadogagent/agent_test.go
  controllers/datadogagent/clusteragent.go
  controllers/datadogagent/clusteragent_metricsserver.go
  controllers/datadogagent/clusterchecksrunner.go
  controllers/datadogagent/clusterchecksrunner_rbac.go
  controllers/datadogagent/common_configmap.go
  controllers/datadogagent/common_configmap_test.go
  controllers/datadogagent/const.go
  controllers/datadogagent/controller.go
  controllers/datadogagent/controller_test.go
  controllers/datadogagent/event.go
  controllers/datadogagent/finalizer.go
  controllers/datadogagent/poddisruptionbudget.go
  controllers/datadogagent/secret.go
  controllers/datadogagent/secret_agent.go
  controllers/datadogagent/secret_clusteragent.go
  controllers/datadogagent/service.go
  controllers/datadogagent/systemprobe.go
  controllers/datadogagent/utils.go
  controllers/datadogagent_controller.go
  controllers/datadogagent_controller_test.go
  controllers/setup.go
  controllers/suite_test.go
  controllers/testutils/debug.go
  controllers/testutils/new.go
  controllers/testutils/node.go
  controllers/utils/event_test.go
  hack/boilerplate.go.txt
  main.go
  pkg/config/config.go
  pkg/controller/debug/register.go
  pkg/controller/utils/comparison/comparison.go
  pkg/controller/utils/condition/condition.go
  pkg/controller/utils/datadog/common.go
  pkg/controller/utils/datadog/event.go
  pkg/controller/utils/datadog/forwarders_manager.go
  pkg/controller/utils/datadog/metrics_forwarder.go
  pkg/controller/utils/datadog/metrics_forwarder_test.go
  pkg/controller/utils/shared_utils.go
  pkg/kubernetes/const.go
Labels: component/controller, enhancement

#258 Fix make deploy due to last-applied annotation size
  Makefile
  config/manager/manager.yaml
Labels: bug, component/controller

#248 Rework the creds manager
  LICENSE-3rdparty.csv
  controllers/datadogagent/controller.go
  controllers/datadogagent/event.go
  controllers/datadogagent_controller.go
  controllers/setup.go
  main.go
  pkg/config/creds.go
  pkg/config/creds_test.go
  pkg/controller/utils/datadog/metrics_forwarder.go
  pkg/controller/utils/datadog/metrics_forwarder_test.go
  pkg/secrets/secrets.go
  pkg/secrets/types.go
Labels: component/controller, enhancement

#259 support query alerts and service checks, and add recommended monitor examples
  api/v1alpha1/datadogmonitor_types.go
  controllers/datadogmonitor/controller.go
  controllers/datadogmonitor/controller_test.go
  controllers/datadogmonitor/monitor_test.go
  examples/datadogagent/datadog-agent-all.yaml
  examples/datadogagent/datadog-agent-apm.yaml
  examples/datadogagent/datadog-agent-logs-apm.yaml
  examples/datadogagent/datadog-agent-logs.yaml
  examples/datadogagent/datadog-agent-openshift.yaml
  examples/datadogagent/datadog-agent-unix-socket.yaml
  examples/datadogagent/datadog-agent-with-clusteragent.yaml
  examples/datadogagent/datadog-agent-with-dca-clusterchecksrunner.yaml
  examples/datadogagent/datadog-agent-with-dca-with-orchestrator-explorer.yaml
  examples/datadogagent/datadog-agent-with-prometheus-autodiscovery-advanced-config.yaml
  examples/datadogagent/datadog-agent-with-prometheus-autodiscovery.yaml
  examples/datadogagent/datadog-agent-with-tolerations.yaml
  examples/datadogagent/datadog-agent.yaml
  examples/datadogmonitor/datadog-monitor-crashloopbackoff.yaml
  examples/datadogmonitor/datadog-monitor-deployment-replicas.yaml
  examples/datadogmonitor/datadog-monitor-imagepullbackoff.yaml
  examples/datadogmonitor/datadog-monitor-nodes-unavailable.yaml
  examples/datadogmonitor/datadog-monitor-pods-failed-state.yaml
  examples/datadogmonitor/datadog-monitor-pods-restarting.yaml
  examples/datadogmonitor/datadog-monitor-statefulset-replicas.yaml
  examples/datadogmonitor/datadog-monitor-test.yaml
Labels: component/controller, enhancement

#262 Use an EmptyDir volume shared between all the agents for logs so that `agent flare` can gather the logs of all of them.
  api/v1alpha1/const.go
  controllers/datadogagent/agent_test.go
  controllers/datadogagent/utils.go
  controllers/datadogagent/utils_test.go
Labels: enhancement

#263 [datadogmonitor] support monitor options
  api/v1alpha1/datadogmonitor_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/v1/datadoghq.com_datadogmonitors.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogmonitors.yaml
  controllers/datadogmonitor/controller.go
  controllers/datadogmonitor/monitor.go
  controllers/datadogmonitor/monitor_test.go
  examples/datadogmonitor/datadog-monitor-test.yaml
Labels: enhancement

#264 [datadogmonitor] make improvements to kubectl get output
  api/v1alpha1/datadogmonitor_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/v1/datadoghq.com_datadogmonitors.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogmonitors.yaml
  controllers/datadogmonitor/controller.go
  controllers/datadogmonitor/controller_test.go
  controllers/datadogmonitor/finalizer.go
Labels: enhancement

#265 add log keys
  pkg/config/config.go
Labels: bug
