Repository DataDog/datadog-operator, pull requests merged in 2021-09, with the labels that each got.

#371 Update agent and cluster-agent default images
  pkg/defaulting/images.go
Labels: enhancement, component/controller

#369 [controllers/datadogagent] Fix watch of ClusterRoles and ClusterRoleBindings
  controllers/datadogagent/agent.go
  controllers/datadogagent/clusteragent.go
  controllers/datadogagent/clusterchecksrunner.go
  controllers/datadogagent/common_rbac.go
  controllers/datadogagent/labels.go
  controllers/datadogagent/labels_test.go
  controllers/datadogagent/utils.go
  controllers/datadogagent_controller.go
Labels: bug, component/controller

#379 fix permissions for extendeddaemonsetreplicasets
  config/rbac/role.yaml
  controllers/datadogagent_controller.go
Labels: bug, component/controller

#380 [DatadogAgent] patch bundle to rm status defaultOverride
  hack/patch-bundle.sh
Labels: bug

#383 Update agent and cluster agent image tags to 7.31.1 and 1.15.1
  pkg/defaulting/images.go
Labels: enhancement, component/controller

#384 remove agent image tags in alm example of cluster service version (redhat)
  bundle-redhat/manifests/datadog-operator.clusterserviceversion.yaml
Labels: enhancement

#385 Remove image references in example file
  config/samples/datadog-operator-hub-example.yaml
Labels: enhancement

#381 Add pod anti-affinity for cluster-agent
  controllers/datadogagent/clusteragent.go
  controllers/datadogagent/clusteragent_test.go
Labels: enhancement, component/controller
