Repository DataDog/datadog-operator, pull requests merged in 2021-01, with the labels that each got.

#203 Fix Dogstatsd config defaulting
  api/v1alpha1/datadogagent_default.go
  api/v1alpha1/datadogagent_default_test.go
Labels: bug, component/controller

#205 Use DD_EXTERNAL_METRICS_PROVIDER_ENDPOINT
  api/v1alpha1/const.go
  controllers/datadogagent/clusteragent.go
  controllers/datadogagent/clusteragent_test.go
Labels: component/controller, enhancement

#209 Add ARM64 images and publish using dedicated pipeline
  .gitlab-ci.yml
  Dockerfile
  Makefile
Labels: enhancement

#210 Increase to 250Mi the operator default resources
  config/manager/manager.yaml
Labels: component/olm, enhancement

#212 Add a master tag corresponding to master branch
  .gitlab-ci.yml
Labels: enhancement

#204 Add the possibility to configure the dogstatsd/apm socket host path
  api/v1alpha1/const.go
  api/v1alpha1/datadogagent_default.go
  api/v1alpha1/datadogagent_default_test.go
  api/v1alpha1/datadogagent_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  api/v1alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  controllers/datadogagent/utils.go
  controllers/datadogagent/utils_test.go
  examples/datadog-agent-unix-socket.yaml
Labels: bug, component/controller

#213 Add documentation about OLM installation
  docs/installation.md
Labels: documentation

#214 Update container image location
  api/v1alpha1/datadogagent_default.go
  api/v1alpha1/datadogagent_types.go
  api/v1alpha1/test/new.go
  api/v1alpha1/zz_generated.openapi.go
  bundle-redhat/manifests/datadog-operator.clusterserviceversion.yaml
  bundle-redhat/manifests/datadoghq.com_datadogagents.yaml
  bundle/manifests/datadog-operator.clusterserviceversion.yaml
  bundle/manifests/datadoghq.com_datadogagents.yaml
  cmd/kubectl-datadog/agent/upgrade/upgrade.go
  cmd/kubectl-datadog/agent/upgrade/upgrade_test.go
  cmd/kubectl-datadog/clusteragent/upgrade/upgrade.go
  cmd/kubectl-datadog/clusteragent/upgrade/upgrade_test.go
  cmd/kubectl-datadog/flare/replacer_test.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  config/samples/datadog-agent-apm.yaml
  config/samples/datadog-agent-logs-apm.yaml
  config/samples/datadog-agent-logs.yaml
  config/samples/datadog-agent-openshift.yaml
  config/samples/datadog-agent-with-clusteragent-with-orchestrator.yaml
  config/samples/datadog-agent-with-clusteragent.yaml
  config/samples/datadog-agent-with-dca-clusterchecksrunner.yaml
  config/samples/datadog-agent-with-tolerations.yaml
  config/samples/datadog-agent.yaml
  controllers/datadogagent/agent_test.go
  controllers/datadogagent/clusteragent_test.go
  controllers/datadogagent/clusterchecksrunner_test.go
  docs/cluster_agent_setup.md
  docs/configuration.md
  docs/custom_check.md
  docs/installation.md
  docs/secret_management.md
  examples/datadog-agent-all.yaml
  examples/datadog-agent-apm.yaml
  examples/datadog-agent-logs-apm.yaml
  examples/datadog-agent-logs.yaml
  examples/datadog-agent-openshift.yaml
  examples/datadog-agent-with-clusteragent.yaml
  examples/datadog-agent-with-dca-clusterchecksrunner.yaml
  examples/datadog-agent-with-dca-with-orchestrator-explorer.yaml
  examples/datadog-agent-with-tolerations.yaml
  examples/datadog-agent.yaml
  hack/release/cluster-service-version-patch.yaml
  pkg/plugin/common/utils_test.go
Labels: enhancement, feature request

#215 Decrease the number of CLC to 1 by default
  api/v1alpha1/datadogagent_default.go
  controllers/datadogagent/clusterchecksrunner_test.go
Labels: component/controller, enhancement, feature request
