Repository DataDog/datadog-operator, pull requests merged in 2021-07, with the labels that each got.

#330 Support KSMCore in DCA
  api/v1alpha1/datadogagent_default.go
  api/v1alpha1/datadogagent_default_test.go
  api/v1alpha1/datadogagent_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  api/v1alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  config/rbac/role.yaml
  controllers/datadogagent/clusteragent.go
  controllers/datadogagent/clusterchecksrunner_rbac.go
  controllers/datadogagent/clusterchecksrunner_rbac_test.go
  controllers/datadogagent/kubestatemetrics.go
  controllers/datadogagent/kubestatemetrics_test.go
  controllers/datadogagent/utils.go
  controllers/datadogagent_controller.go
  docs/configuration.md
  go.sum
Labels: component/controller, enhancement

#333 Remove Metrics Server APIService in finalizer
  controllers/datadogagent/finalizer.go
Labels: bug

#331 Enable Dogstatsd UDS in an emptyDir by default
  Makefile
  api/v1alpha1/datadogagent_default.go
  api/v1alpha1/datadogagent_default_test.go
  config/rbac/role.yaml
  controllers/datadogagent/agent_test.go
  controllers/datadogagent/utils.go
  controllers/datadogagent/utils_test.go
  controllers/datadogagent_controller.go
Labels: component/controller, enhancement

#332 Do not default CLC and DCA replica fields
  api/v1alpha1/datadogagent_default.go
  api/v1alpha1/datadogagent_default_test.go
  api/v1alpha1/datadogagent_types.go
  api/v1alpha1/test/new.go
  api/v1alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  controllers/datadogagent/clusteragent.go
  controllers/datadogagent/clusteragent_test.go
  controllers/datadogagent/clusterchecksrunner.go
  controllers/datadogagent/clusterchecksrunner_test.go
  controllers/datadogagent/utils.go
  controllers/datadogagent/utils_test.go
  docs/configuration.md
Labels: component/controller, enhancement

#336 fix version check to work with release candidates
  api/v1alpha1/datadogagent_default.go
  controllers/datadogagent/finalizer.go
  pkg/utils/version_test.go
Labels: bug

#335 Support nested path in confd configmap
  api/v1alpha1/datadogagent_types.go
  api/v1alpha1/test/new.go
  api/v1alpha1/zz_generated.deepcopy.go
  api/v1alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  controllers/datadogagent/agent_test.go
  controllers/datadogagent/builder.go
  controllers/datadogagent/builder_test.go
  controllers/datadogagent/clusteragent.go
  controllers/datadogagent/clusteragent_test.go
  controllers/datadogagent/controller_test.go
  controllers/datadogagent/kubestatemetrics.go
  controllers/datadogagent/utils.go
  docs/configuration.md
  examples/datadogagent/datadog-agent-cluster-agent-confd.yaml
  examples/datadogagent/datadog-agent-ksm-core-custom-conf.yaml
Labels: component/controller, enhancement

#334 [dca] support sts
  controllers/datadogagent/clusteragent.go
Labels: enhancement

#310 Add `/var/log/containers` to the list of mounted paths.
  api/v1alpha1/const.go
  api/v1alpha1/datadogagent_default.go
  api/v1alpha1/datadogagent_default_test.go
  api/v1alpha1/datadogagent_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  api/v1alpha1/zz_generated.openapi.go
  bundle/manifests/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  controllers/datadogagent/agent_test.go
  controllers/datadogagent/utils.go
  docs/configuration.md
Labels: enhancement

#338 Fix APM HostPort configuration
  api/v1alpha1/datadogagent_default_test.go
  controllers/datadogagent/agent_test.go
  controllers/datadogagent/utils.go
Labels: bug, component/controller

#340 Add variable to set lease duration
  main.go
Labels: enhancement

#341 Automate `datadog` krew plugin releasing
  .github/workflows/release.yaml
Labels: enhancement

#342 Fix runtime security config mount
  controllers/datadogagent/agent_test.go
  controllers/datadogagent/utils.go
  controllers/datadogagent/utils_test.go
Labels: bug
