Repository DataDog/datadog-operator, pull requests merged in 2021-06, with the labels that each got.

#308 Check Scrubbing for default only if OrchestratorExplorer is enabled
  api/v1alpha1/datadogagent_default.go
  api/v1alpha1/datadogagent_default_test.go
Labels: bug

#303 Improve support for environment autodiscovery by removing explicit setting of DOCKER_HOST by default with Agent 7.27+
  LICENSE-3rdparty.csv
  api/v1alpha1/datadogagent_default.go
  controllers/datadogagent/agent_test.go
  controllers/datadogagent/controller_test.go
  controllers/datadogagent/utils.go
  controllers/datadogagent/utils_test.go
  go.mod
  go.sum
  pkg/utils/utils.go
  pkg/utils/version.go
  pkg/utils/version_test.go
Labels: component/controller, enhancement

#314 [dca] add daemonsets list/watch for the cluster-agent
  controllers/datadogagent/clusteragent.go
Labels: component/controller, enhancement

#316 Introduce custom ConfigMap for system-probe and move built-in configuration to ENV vars
  api/v1alpha1/const.go
  api/v1alpha1/datadogagent_types.go
  api/v1alpha1/datadogagent_validation.go
  api/v1alpha1/test/new.go
  api/v1alpha1/zz_generated.deepcopy.go
  api/v1alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  controllers/datadogagent/agent_test.go
  controllers/datadogagent/controller_test.go
  controllers/datadogagent/systemprobe.go
  controllers/datadogagent/utils.go
  docs/configuration.md
Labels: enhancement

#315 Set runtime security custom policy using config map
  api/v1alpha1/const.go
  controllers/datadogagent/agent_test.go
  controllers/datadogagent/clusterchecksrunner_test.go
  controllers/datadogagent/controller_test.go
  controllers/datadogagent/systemprobe.go
  controllers/datadogagent/utils.go
  controllers/datadogagent/utils_test.go
Labels: enhancement

#309 Support global registry configuration
  api/v1alpha1/const.go
  api/v1alpha1/datadogagent_default.go
  api/v1alpha1/datadogagent_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  api/v1alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  controllers/datadogagent/clusteragent.go
  controllers/datadogagent/clusteragent_test.go
  controllers/datadogagent/clusterchecksrunner.go
  controllers/datadogagent/clusterchecksrunner_test.go
  controllers/datadogagent/utils.go
  controllers/datadogagent/utils_test.go
  docs/configuration.md
Labels: component/controller, enhancement

#317 [examples/datadogmonitor] fix metric typo in example monitor
  examples/datadogmonitor/datadog-monitor-deployment-replicas.yaml
Labels: documentation

#318 Fix CLC manifest when custom RuntimeDir is used
  controllers/datadogagent/clusterchecksrunner.go
  controllers/datadogagent/clusterchecksrunner_test.go
Labels: bug

#320 Fix CRI vs Docker socket path priority. Always try to mount default runtime dir if using standard path to maximize usage of Env AD
  controllers/datadogagent/utils.go
Labels: bug, component/controller

#321 Fix CRI vs Docker socket path priority in VolumeMounts (fix changes from #320)
  controllers/datadogagent/utils.go
Labels: bug

#323 Add support for system-probe extra volumeMounts
  api/v1alpha1/datadogagent_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  api/v1alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  controllers/datadogagent/utils.go
  docs/configuration.md
Labels: component/controller, enhancement

#319 Allow Agent pods to have Affinity
  api/v1alpha1/datadogagent_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  api/v1alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  controllers/datadogagent/controller_test.go
  controllers/datadogagent/utils.go
  docs/configuration.md
Labels: component/controller, enhancement

#326 Use pod name as cluster check runner ID
  api/v1alpha1/const.go
  controllers/datadogagent/clusterchecksrunner.go
  controllers/datadogagent/clusterchecksrunner_test.go
  controllers/datadogagent/const.go
Labels: component/controller, enhancement

#328 Only copy runtime policies when enabled
  controllers/datadogagent/agent_test.go
  controllers/datadogagent/utils.go
Labels: bug

#324 Introducing defaulting logic
  LICENSE-3rdparty.csv
  api/v1alpha1/const.go
  api/v1alpha1/datadogagent_default.go
  api/v1alpha1/datadogagent_default_test.go
  api/v1alpha1/datadogagent_types.go
  api/v1alpha1/datadogagent_validation.go
  api/v1alpha1/patch/datadogagent.go
  api/v1alpha1/patch/datadogagent_test.go
  api/v1alpha1/test/new.go
  api/v1alpha1/utils.go
  api/v1alpha1/zz_generated.deepcopy.go
  api/v1alpha1/zz_generated.openapi.go
  cmd/kubectl-datadog/agent/upgrade/upgrade.go
  cmd/kubectl-datadog/agent/upgrade/upgrade_test.go
  cmd/kubectl-datadog/clusteragent/upgrade/upgrade.go
  cmd/kubectl-datadog/clusteragent/upgrade/upgrade_test.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  controllers/datadogagent/agent.go
  controllers/datadogagent/agent_rbac.go
  controllers/datadogagent/agent_test.go
  controllers/datadogagent/clusteragent.go
  controllers/datadogagent/clusteragent_test.go
  controllers/datadogagent/clusterchecksrunner.go
  controllers/datadogagent/clusterchecksrunner_rbac.go
  controllers/datadogagent/clusterchecksrunner_rbac_test.go
  controllers/datadogagent/clusterchecksrunner_test.go
  controllers/datadogagent/common_configmap.go
  controllers/datadogagent/controller.go
  controllers/datadogagent/controller_test.go
  controllers/datadogagent/kubestatemetrics.go
  controllers/datadogagent/poddisruptionbudget.go
  controllers/datadogagent/secret_agent.go
  controllers/datadogagent/secret_clusteragent.go
  controllers/datadogagent/service.go
  controllers/datadogagent/systemprobe.go
  controllers/datadogagent/utils.go
  controllers/datadogagent/utils_test.go
  controllers/datadogagent_controller_test.go
  controllers/testutils/new.go
  docs/configuration.md
  go.mod
  go.sum
  pkg/controller/utils/datadog/metrics_forwarder.go
Labels: editorial review, enhancement
