Repository DataDog/datadog-operator, pull requests merged in 2021-11, with the labels that each got.

#400 Add documentation on how to test operator bundles + fix defaultOverride bundle patch
  RELEASING.md
  apis/datadoghq/v1alpha1/datadogagent_types.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  hack/patch-bundle.sh
  hack/patch-crds.sh
Labels: documentation

#405 Adding Base structure for pod/container config
  apis/datadoghq/v2alpha1/datadogagent_types.go
  apis/datadoghq/v2alpha1/zz_generated.deepcopy.go
  apis/datadoghq/v2alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
Labels: enhancement

#406 Fix links in README
  README.md
Labels: documentation, enhancement

#408 Set the TriggerWindow correctly when an anomaly monitor is set up
  controllers/datadogmonitor/monitor.go
Labels: bug

#407 Do not serve v2alpha1 as schema not defined yet
  apis/datadoghq/v2alpha1/datadogagent_types.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  config/manager/kustomization.yaml
Labels: component/controller

#411 fix: add vpa permissions to ksm core rbacs
  apis/datadoghq/v1alpha1/const.go
  config/rbac/role.yaml
  controllers/datadogagent/kubestatemetrics.go
  controllers/datadogagent/testdata/ksm_clusterrole.yaml
  controllers/datadogagent_controller.go
Labels: bug, component/controller
