Repository DataDog/datadog-operator, pull requests merged in 2021-04, with the labels that each got.

#267 Fix DCA RBAC for the external metrics provider
  controllers/datadogagent/clusteragent.go
Labels: enhancement

#269 Update Releasing doc link in Readme.md
  README.md
Labels: bug, documentation

#270 Trigger internal image generation
  .gitlab-ci.yml
Labels: enhancement

#260 Add support for Kubelet configuration
  api/v1alpha1/const.go
  api/v1alpha1/datadogagent_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  api/v1alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  controllers/datadogagent/agent_test.go
  controllers/datadogagent/utils.go
  controllers/datadogagent/utils_kubelet.go
  docs/configuration.md
Labels: component/controller, editorial review, enhancement

#271 Cleanup gitlab-ci config
  .gitlab-ci.yml
Labels: enhancement

#275 Fix operator leader election on vintage k8s cluster
  main.go
Labels: bug, component/controller

#276 Fix `system-probe` and `process-agent` config arg
  controllers/datadogagent/agent_test.go
  controllers/datadogagent/utils.go
Labels: bug, component/controller

#277 Add missing argument to process-agent
  controllers/datadogagent/agent_test.go
  controllers/datadogagent/utils.go
Labels: bug, component/controller

#273 [DatadogAgent] update configuration options for system probe
  api/v1alpha1/datadogagent_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  api/v1alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  config/samples/datadog-operator-hub-example.yaml
  controllers/datadogagent/systemprobe.go
  controllers/datadogagent/utils.go
  docs/configuration.md
  examples/datadogagent/datadog-agent-all.yaml
Labels: enhancement

#268 Add Features.LogCollection
  api/v1alpha1/datadogagent_default.go
  api/v1alpha1/datadogagent_default_test.go
  api/v1alpha1/datadogagent_types.go
  api/v1alpha1/datadogagent_validation.go
  api/v1alpha1/patch/datadogagent.go
  api/v1alpha1/patch/datadogagent_test.go
  api/v1alpha1/test/new.go
  api/v1alpha1/zz_generated.deepcopy.go
  api/v1alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  controllers/datadogagent/agent_test.go
  controllers/datadogagent/clusteragent_test.go
  controllers/datadogagent/controller.go
  controllers/datadogagent/controller_test.go
  controllers/datadogagent/kubestatemetrics_test.go
  controllers/datadogagent/utils.go
  controllers/datadogagent/utils_test.go
  controllers/datadogagent_controller_test.go
  controllers/testutils/new.go
  docs/configuration.md
Labels: component/controller, enhancement

#279 Fix public image tag
  .gitlab-ci.yml
Labels: bug

#281 Fix dockerhub pull image in gitlabci
  .gitlab-ci.yml
Labels: bug

#283 fix rbac for cluster agent
  controllers/datadogagent/clusteragent.go
Labels: bug

#282 Discourage putting plain text secrets in the DatadogAgent CRDs
  docs/cluster_agent_setup.md
  docs/configuration.md
  docs/getting_started.md
  docs/installation.md
Labels: documentation

#280 Fix process collection config option
  examples/datadogagent/datadog-agent-all.yaml
Labels: documentation

#284 Update system-probe integration for 7.28.0
  api/v1alpha1/const.go
  controllers/datadogagent/agent_test.go
  controllers/datadogagent/systemprobe.go
  controllers/datadogagent/utils.go
  controllers/datadogagent/utils_test.go
Labels: component/controller, enhancement

#285 Remove automatic copy of all labels/annotations from DatadogAgent CRD - now only Datadog tags labels will be copied
  api/v1alpha1/datadogagent_types.go
  api/v1alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  controllers/datadogagent/agent.go
  controllers/datadogagent/agent_test.go
  controllers/datadogagent/clusteragent.go
  controllers/datadogagent/clusteragent_test.go
  controllers/datadogagent/clusterchecksrunner.go
  controllers/datadogagent/const.go
  controllers/datadogagent/utils.go
  docs/configuration.md
Labels: bug

#286 Fix redhat bundle validation
  docs/configuration.md
  hack/redhat-bundle.sh
Labels: bug

#289 Deactivate DSD in CLC Runners - udpate DCA to new liveness/readiness
  api/v1alpha1/const.go
  controllers/datadogagent/clusteragent.go
  controllers/datadogagent/clusteragent_test.go
  controllers/datadogagent/clusterchecksrunner.go
  controllers/datadogagent/clusterchecksrunner_test.go
Labels: bug

#287 add cronjobs/jobs list/watch for the cluster-agent
  controllers/datadogagent/clusteragent.go
Labels: enhancement
