Repository DataDog/datadog-operator, pull requests merged in 2021-05, with the labels that each got.

#291 Fix DCA health port
  Makefile
  config/rbac/role.yaml
  controllers/datadogagent/clusteragent.go
  controllers/datadogagent/clusteragent_test.go
  controllers/datadogagent_controller.go
Labels: bug

#290 Remove automatic copying of previous Agent/ClusterAgent unknown annotations/labels
  LICENSE-3rdparty.csv
  api/v1alpha1/datadogagent_types.go
  api/v1alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  controllers/datadogagent/agent.go
  controllers/datadogagent/clusteragent.go
  controllers/datadogagent/utils.go
  controllers/datadogagent/utils_test.go
  docs/configuration.md
  go.mod
  go.sum
Labels: bug

#292 remove fallback logic for credentials
  api/v1alpha1/datadogagent_types.go
  api/v1alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  controllers/datadogagent/secret.go
  controllers/datadogagent/secret_agent.go
  controllers/datadogagent/secret_test.go
Labels: bug

#261 [datadogmonitor] add getting started doc
  docs/datadog_monitor.md
Labels: documentation

#293 fix example DatadogMonitor tags
  examples/datadogmonitor/datadog-monitor-crashloopbackoff.yaml
  examples/datadogmonitor/datadog-monitor-deployment-replicas.yaml
  examples/datadogmonitor/datadog-monitor-imagepullbackoff.yaml
  examples/datadogmonitor/datadog-monitor-nodes-unavailable.yaml
  examples/datadogmonitor/datadog-monitor-pods-failed-state.yaml
  examples/datadogmonitor/datadog-monitor-statefulset-replicas.yaml
Labels: documentation

#294 add missing permissions
  config/rbac/leader_election_role.yaml
Labels: bug

#295 fix clusterrole for kustomize
  config/rbac/role.yaml
  controllers/datadogagent_controller.go
Labels: bug

#298 Add support for overriding Commands/Args in all Agents
  api/v1alpha1/datadogagent_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  api/v1alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  controllers/datadogagent/agent_test.go
  controllers/datadogagent/clusteragent.go
  controllers/datadogagent/clusterchecksrunner.go
  controllers/datadogagent/utils.go
  docs/configuration.md
Labels: enhancement

#297 [runtime-security] Mount host root and export HOST_ROOT env variable if runtime is enabled
  controllers/datadogagent/agent_test.go
  controllers/datadogagent/utils.go
  controllers/datadogagent/utils_test.go
Labels: enhancement

#299 Avoid continuous requeuing of DatadogMonitors due to MonitorStateLastUpdateTime
  controllers/datadogmonitor/controller.go
Labels: bug

#313 OLM doc update
  docs/installation.md
Labels: documentation

#306 Small indentation issue
  docs/datadog_monitor.md
Labels: documentation

#311 Fix management of seccomp ConfigMap when not used
  LICENSE-3rdparty.csv
  api/v1alpha1/datadogagent_types.go
  api/v1alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  controllers/datadogagent/agent_test.go
  controllers/datadogagent/clusteragent_test.go
  controllers/datadogagent/clusterchecksrunner_test.go
  controllers/datadogagent/controller_test.go
  controllers/datadogagent/systemprobe.go
  controllers/datadogagent/utils.go
  controllers/setup.go
  docs/configuration.md
  main.go
  pkg/testutils/testutils.go
Labels: bug
