Repository DataDog/datadog-operator, pull requests merged in 2022-11, with the labels that each got.

#636 [defaulting/images] Update agents to 7.40.0
  pkg/defaulting/images.go
Labels: enhancement

#635 Fix seccomp conversion
  apis/datadoghq/v1alpha1/datadogagent_conversion_agent.go
  apis/datadoghq/v1alpha1/testdata/all.yaml
Labels: bug

#638 [defaulting/images] Update agents to 7.40.1
  pkg/defaulting/images.go
Labels: enhancement

#641 [v2alpha1/default] Default Features.ClusterChecks.Enabled if unset
  apis/datadoghq/v2alpha1/datadogagent_default.go
  apis/datadoghq/v2alpha1/datadogagent_default_test.go
Labels: bug

#642 Expose the `…ENABLE_OOM_KILL` and `…TCP_QUEUE_LENGTH` env vars to the `init-config` container
  apis/datadoghq/common/v1/types.go
  controllers/datadogagent/feature/oomkill/feature.go
  controllers/datadogagent/feature/tcpqueuelength/feature.go
  controllers/datadogagent/merger/envvars.go
  controllers/datadogagent/merger/fake/envvar_manager.go
Labels: bug

#647 [github/workflows/main] Fix codecov reporting
  .github/workflows/main.yml
  Makefile
Labels: tooling

#645 [feature/prometheusscrape] Allow to configure the version of the Openmetrics check
  apis/datadoghq/common/envvar.go
  apis/datadoghq/v2alpha1/datadogagent_default.go
  apis/datadoghq/v2alpha1/datadogagent_types.go
  apis/datadoghq/v2alpha1/zz_generated.deepcopy.go
  apis/datadoghq/v2alpha1/zz_generated.openapi.go
  apis/utils/utils.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  controllers/datadogagent/feature/prometheusscrape/feature.go
  controllers/datadogagent/feature/prometheusscrape/feature_test.go
  docs/configuration.v2alpha1.md
Labels: enhancement

#646 [Makefile] Update envtest k8s version to 1.24
  Makefile
Labels: tooling

#644 Share the system-probe socket when `oom_kill` or `tcp_queue_length` checks are enabled
  controllers/datadogagent/feature/oomkill/feature.go
  controllers/datadogagent/feature/oomkill/feature_test.go
  controllers/datadogagent/feature/tcpqueuelength/feature.go
  controllers/datadogagent/feature/tcpqueuelength/feature_test.go
Labels: bug

#648 CWS: fix custom policy file name
  controllers/datadogagent/feature/cws/const.go
Labels: bug

#640 Building on M1 will can't use kustomize3
  Makefile
Labels: enhancement, tooling

#653 fix: replace deprecated newHostDelay with newGroupDelay
  apis/datadoghq/v1alpha1/datadogmonitor_types.go
  apis/datadoghq/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/datadoghq.com_datadogmonitors.yaml
  config/crd/bases/v1/datadoghq.com_datadogmonitors.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogmonitors.yaml
  controllers/datadogmonitor/monitor.go
  controllers/datadogmonitor/monitor_test.go
  examples/datadogmonitor/audit-alert-monitor-test.yaml
  examples/datadogmonitor/event-alert-monitor-test.yaml
  examples/datadogmonitor/event-v2-alert-monitor-test.yaml
  examples/datadogmonitor/log-alert-monitor-test.yaml
  examples/datadogmonitor/metric-monitor-test.yaml
  examples/datadogmonitor/process-alert-monitor-test.yaml
  examples/datadogmonitor/rum-alert-monitor-test.yaml
  examples/datadogmonitor/service-check-monitor-test.yaml
  examples/datadogmonitor/slo-alert-monitor-test.yaml
  examples/datadogmonitor/trace-analytics-alert-monitor-test.yaml
Labels: bug, feature/datadog-monitor

#651 Disable otlp feature by default
  controllers/datadogagent/feature/otlp/feature.go
Labels: bug
