Repository DataDog/datadog-operator, pull requests merged in 2022-03, with the labels that each got.

#452 feat: update Agent to 7.34.0 and DCA to 1.18.0
  pkg/defaulting/images.go
Labels: enhancement, component/controller

#448 Add SecurityContext to DCA and CLC
  apis/datadoghq/v1alpha1/datadogagent_types.go
  apis/datadoghq/v1alpha1/zz_generated.deepcopy.go
  apis/datadoghq/v1alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  controllers/datadogagent/clusteragent.go
  controllers/datadogagent/clusteragent_test.go
  controllers/datadogagent/clusterchecksrunner.go
  controllers/datadogagent/clusterchecksrunner_test.go
  docs/configuration.md
Labels: enhancement

#453 [docs/openshift] Fix example config
  docs/install-openshift.md
Labels: documentation

#455 [controllers/datadogagent] Mount logs volume in DCA and CLC
  controllers/datadogagent/clusteragent.go
  controllers/datadogagent/clusteragent_test.go
  controllers/datadogagent/clusterchecksrunner.go
  controllers/datadogagent/clusterchecksrunner_test.go
  controllers/datadogagent/utils.go
Labels: bug

#458 add minimum version note to new datadogmonitor examples
  examples/datadogmonitor/audit-alert-monitor-test.yaml
  examples/datadogmonitor/event-alert-monitor-test.yaml
  examples/datadogmonitor/event-v2-alert-monitor-test.yaml
  examples/datadogmonitor/log-alert-monitor-test.yaml
  examples/datadogmonitor/process-alert-monitor-test.yaml
  examples/datadogmonitor/rum-alert-monitor-test.yaml
  examples/datadogmonitor/slo-alert-monitor-test.yaml
  examples/datadogmonitor/trace-analytics-alert-monitor-test.yaml
Labels: documentation, feature/datadog-monitor

#454 Fix DatadogAgent secret backend usage
  apis/datadoghq/v1alpha1/datadogagent_types.go
  apis/datadoghq/v1alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  controllers/datadogagent/agent.go
  controllers/datadogagent/clusteragent.go
  controllers/datadogagent/clusterchecksrunner.go
  controllers/datadogagent/secret.go
  controllers/datadogagent/secret_agent.go
  controllers/datadogagent/secret_clusteragent.go
  controllers/datadogagent/secret_common.go
  controllers/datadogagent/secret_test.go
  controllers/datadogagent/utils.go
  controllers/testutils/new.go
  docs/configuration.md
  docs/secret_management.md
  examples/datadogagent/datadog-agent-secret-backend.yaml
  pkg/controller/utils/shared_utils.go
  pkg/secrets/utils.go
Labels: bug, documentation, component/controller
