Repository DataDog/datadog-operator, pull requests merged in 2022-08, with the labels that each got.

#586 Fix image registry setting
  controllers/datadogagent/override/global.go
Labels: bug

#558 Migrate LiveProcessCollection feature
  apis/datadoghq/common/envvar.go
  apis/datadoghq/v2alpha1/datadogagent_default_test.go
  apis/datadoghq/v2alpha1/datadogagent_types.go
  apis/datadoghq/v2alpha1/zz_generated.deepcopy.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  controllers/datadogagent/controller.go
  controllers/datadogagent/feature/ids.go
  controllers/datadogagent/feature/liveprocess/feature.go
  controllers/datadogagent/feature/liveprocess/feature_test.go
  controllers/datadogagent/feature/test/testsuite.go
  controllers/datadogagent_controller_v2_test.go
  controllers/testutils/agent.go
  docs/configuration.v2alpha1.md
Labels: enhancement, component/controller

#588 [defaulting/images] Update agent to 7.38.1
  pkg/defaulting/images.go
Labels: enhancement

#589 [utils/test] Delete unused generateSpec func
  controllers/datadogagent/utils_test.go
Labels: refactoring

#583 [feature] APM feature migration
  apis/datadoghq/common/const.go
  apis/datadoghq/common/envvar.go
  apis/datadoghq/v1alpha1/const.go
  apis/datadoghq/v2alpha1/datadogagent_default.go
  apis/datadoghq/v2alpha1/datadogagent_types.go
  apis/datadoghq/v2alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  controllers/datadogagent/component/utils.go
  controllers/datadogagent/controller.go
  controllers/datadogagent/dependencies/store.go
  controllers/datadogagent/feature/apm/feature.go
  controllers/datadogagent/feature/apm/feature_test.go
  controllers/datadogagent/feature/dogstatsd/feature.go
  controllers/datadogagent/feature/dogstatsd/feature_test.go
  controllers/datadogagent/feature/ids.go
  controllers/datadogagent/merger/service.go
  controllers/datadogagent/override/global.go
  controllers/datadogagent/utils.go
  controllers/datadogagent_controller_v2_test.go
  controllers/testutils/agent.go
Labels: enhancement, component/controller

#591 Add EDS Support
  apis/datadoghq/v2alpha1/condition.go
  controllers/datadogagent/component/new.go
  controllers/datadogagent/controller_reconcile_agent.go
  controllers/datadogagent/controller_reconcile_v2_common.go
Labels: enhancement, component/controller

#594 update metrics forwarder manager to use an interface for the status condition
  controllers/datadogagent/controller.go
  controllers/datadogagent/controller_test.go
  pkg/controller/utils/datadog/forwarders_manager.go
  pkg/controller/utils/datadog/metrics_forwarder.go
Labels: enhancement, component/controller

#590 fix config links and apiVersion of example
  README.md
  docs/configuration.v1alpha1.md
  docs/configuration.v2alpha1.md
  docs/getting_started.md
Labels: documentation

#516 Add cilium network policies
  controllers/datadogagent/component/utils.go
  controllers/datadogagent/feature/types.go
  controllers/datadogagent/merger/cilium.go
  controllers/datadogagent/merger/cilium_test.go
  controllers/datadogagent/override/global.go
Labels: enhancement

#596 [feature] Live container feature migration
  apis/datadoghq/common/const.go
  apis/datadoghq/common/envvar.go
  controllers/datadogagent/clusterchecksrunner.go
  controllers/datadogagent/clusterchecksrunner_test.go
  controllers/datadogagent/component/agent/default.go
  controllers/datadogagent/component/clusterchecksrunner/default.go
  controllers/datadogagent/component/utils.go
  controllers/datadogagent/controller.go
  controllers/datadogagent/feature/ids.go
  controllers/datadogagent/feature/livecontainer/feature.go
  controllers/datadogagent/feature/livecontainer/feature_test.go
  controllers/datadogagent/feature/liveprocess/feature.go
  controllers/datadogagent/feature/liveprocess/feature_test.go
  controllers/datadogagent/feature/npm/feature.go
  controllers/datadogagent/feature/npm/feature_test.go
  controllers/datadogagent/override/global.go
  controllers/datadogagent/utils.go
  controllers/datadogagent_controller_v2_test.go
  controllers/testutils/agent.go
Labels: enhancement, component/controller

#604 [hack] Adapt generate-docs script to output 2 versions
  docs/configuration.v1alpha1.md
  docs/configuration.v2alpha1.md
  hack/generate-docs.go
  hack/generate-docs/header.markdown
  hack/generate-docs/v1alpha1_example.markdown
  hack/generate-docs/v2alpha1_example.markdown
Labels: tooling

#592 [override] Implement component overrides
  apis/datadoghq/common/common.go
  apis/datadoghq/common/common_test.go
  apis/datadoghq/common/const.go
  apis/datadoghq/v1alpha1/const.go
  apis/datadoghq/v2alpha1/const.go
  controllers/datadogagent/agent.go
  controllers/datadogagent/agent_test.go
  controllers/datadogagent/clusteragent.go
  controllers/datadogagent/clusterchecksrunner.go
  controllers/datadogagent/clusterchecksrunner_test.go
  controllers/datadogagent/controller.go
  controllers/datadogagent/controller_reconcile_agent.go
  controllers/datadogagent/controller_reconcile_ccr.go
  controllers/datadogagent/controller_reconcile_dca.go
  controllers/datadogagent/controller_reconcile_v2.go
  controllers/datadogagent/merger/rbac.go
  controllers/datadogagent/override/daemonset.go
  controllers/datadogagent/override/dependencies.go
  controllers/datadogagent/override/dependencies_test.go
  controllers/datadogagent/override/deploymentspec.go
  controllers/datadogagent/override/deploymentspec_test.go
  controllers/datadogagent/override/podtemplatespec.go
  controllers/datadogagent/override/podtemplatespec_test.go
  controllers/datadogagent/utils.go
  controllers/datadogagent/utils_test.go
  controllers/datadogagent_controller_v2_test.go
  controllers/testutils/agent.go
  docs/how-to-contribute.md
Labels: enhancement

#605 [datadogagent/finalizer] Add missing arg in Dependencies()
  controllers/datadogagent/finalizer.go
Labels: bug

#601 update metrics forwarder to support v2
  apis/datadoghq/common/v1/agent_types.go
  apis/datadoghq/common/v1/zz_generated.deepcopy.go
  apis/datadoghq/v1alpha1/datadogagent_types.go
  apis/datadoghq/v1alpha1/secret.go
  apis/datadoghq/v1alpha1/zz_generated.deepcopy.go
  apis/datadoghq/v1alpha1/zz_generated.openapi.go
  apis/datadoghq/v2alpha1/condition.go
  apis/datadoghq/v2alpha1/datadogagent_types.go
  apis/datadoghq/v2alpha1/secret.go
  apis/datadoghq/v2alpha1/test/new.go
  apis/datadoghq/v2alpha1/zz_generated.deepcopy.go
  apis/datadoghq/v2alpha1/zz_generated.openapi.go
  cmd/check-operator/upgrade/upgrade.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  controllers/datadogagent/clusteragent.go
  controllers/datadogagent/clusterchecksrunner.go
  controllers/datadogagent/controller.go
  controllers/datadogagent/controller_reconcile_v2.go
  controllers/datadogagent/controller_reconcile_v2_common.go
  controllers/datadogagent/controller_test.go
  controllers/datadogagent/utils.go
  controllers/datadogagent_controller.go
  docs/how-to-contribute.md
  main.go
  pkg/controller/utils/condition/condition.go
  pkg/controller/utils/datadog/forwarders_manager.go
  pkg/controller/utils/datadog/metrics_forwarder.go
  pkg/controller/utils/datadog/metrics_forwarder_test.go
Labels: enhancement, component/controller
