Repository DataDog/datadog-operator, pull requests merged in 2022-10, with the labels that each got.

#620 fix use of custom configmaps and configdata in overrides and features
  apis/datadoghq/common/const.go
  apis/datadoghq/common/v1/types.go
  apis/datadoghq/v1alpha1/const.go
  apis/datadoghq/v1alpha1/datadogagent_conversion.go
  apis/datadoghq/v1alpha1/datadogagent_conversion_agent.go
  apis/datadoghq/v2alpha1/datadogagent_types.go
  apis/datadoghq/v2alpha1/zz_generated.deepcopy.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  controllers/datadogagent/agent_test.go
  controllers/datadogagent/clusteragent.go
  controllers/datadogagent/clusteragent_test.go
  controllers/datadogagent/common_configmap.go
  controllers/datadogagent/controller_reconcile_v2.go
  controllers/datadogagent/feature/cspm/const.go
  controllers/datadogagent/feature/cspm/feature.go
  controllers/datadogagent/feature/cspm/feature_test.go
  controllers/datadogagent/feature/cws/const.go
  controllers/datadogagent/feature/cws/feature.go
  controllers/datadogagent/feature/cws/feature_test.go
  controllers/datadogagent/feature/kubernetesstatecore/configmap.go
  controllers/datadogagent/feature/kubernetesstatecore/feature.go
  controllers/datadogagent/feature/orchestratorexplorer/configmap.go
  controllers/datadogagent/feature/orchestratorexplorer/const.go
  controllers/datadogagent/feature/orchestratorexplorer/feature.go
  controllers/datadogagent/finalizer.go
  controllers/datadogagent/merger/fake/volume_mount_manager.go
  controllers/datadogagent/merger/volume_mount.go
  controllers/datadogagent/object/configmap/configmap.go
  controllers/datadogagent/object/volume/volumes.go
  controllers/datadogagent/override/dependencies.go
  controllers/datadogagent/override/dependencies_test.go
  controllers/datadogagent/override/podtemplatespec.go
  controllers/datadogagent/override/podtemplatespec_test.go
  controllers/datadogagent/override/utils.go
  controllers/datadogagent/utils.go
  docs/configuration.v2alpha1.md
Labels: enhancement

#621 rm datadogmonitor feature
  apis/datadoghq/v2alpha1/datadogagent_default_test.go
  apis/datadoghq/v2alpha1/datadogagent_types.go
  apis/datadoghq/v2alpha1/zz_generated.deepcopy.go
  apis/datadoghq/v2alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  docs/configuration.v2alpha1.md
Labels: enhancement

#624 Update system-probe seccomp profile
  controllers/datadogagent/systemprobe.go
Labels: bug

#622 Add SecurityContextConstraints
  apis/datadoghq/v2alpha1/datadogagent_types.go
  apis/datadoghq/v2alpha1/utils.go
  apis/datadoghq/v2alpha1/zz_generated.deepcopy.go
  apis/datadoghq/v2alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  controllers/datadogagent/component/agent/default.go
  controllers/datadogagent/component/clusteragent/default.go
  controllers/datadogagent/component/utils.go
  controllers/datadogagent/controller_reconcile_v2.go
  controllers/datadogagent/feature/apm/feature.go
  controllers/datadogagent/feature/cspm/const.go
  controllers/datadogagent/feature/cspm/feature.go
  controllers/datadogagent/feature/dogstatsd/feature.go
  controllers/datadogagent/finalizer.go
  controllers/datadogagent/merger/pod_security.go
  controllers/datadogagent/merger/pod_security_test.go
  controllers/datadogagent/override/dependencies.go
  controllers/datadogagent/override/dependencies_test.go
  pkg/kubernetes/const.go
  pkg/kubernetes/objects.go
Labels: enhancement, component/controller

#611 Add seccomp profile
  apis/datadoghq/common/const.go
  apis/datadoghq/common/v1/types.go
  apis/datadoghq/v1alpha1/const.go
  apis/datadoghq/v1alpha1/datadogagent_conversion_agent.go
  apis/datadoghq/v1alpha1/testdata/all.expected.yaml
  apis/datadoghq/v1alpha1/testdata/all.yaml
  apis/datadoghq/v2alpha1/datadogagent_types.go
  apis/datadoghq/v2alpha1/zz_generated.deepcopy.go
  apis/datadoghq/v2alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  controllers/datadogagent/agent_test.go
  controllers/datadogagent/component/agent/default.go
  controllers/datadogagent/component/utils.go
  controllers/datadogagent/controller_test.go
  controllers/datadogagent/feature/enabledefault/feature.go
  controllers/datadogagent/feature/types.go
  controllers/datadogagent/merger/configmap.go
  controllers/datadogagent/merger/configmap_test.go
  controllers/datadogagent/merger/security_context.go
  controllers/datadogagent/override/container.go
  controllers/datadogagent/override/container_test.go
  controllers/datadogagent/override/podtemplatespec.go
  controllers/datadogagent/systemprobe.go
  controllers/datadogagent/utils.go
  controllers/testutils/agent.go
Labels: enhancement

#627 Fixing subpath custom conf
  apis/datadoghq/v1alpha1/datadogagent_conversion.go
  apis/datadoghq/v1alpha1/testdata/all.expected.yaml
  controllers/datadogagent/clusteragent.go
Labels: bug

#626 [feature] Register OTLP feature and add integration tests
  controllers/datadogagent/controller.go
  controllers/datadogagent_controller_v2_test.go
  controllers/testutils/agent.go
Labels: bug, component/controller

#628 [defaulting/images] Update agents to 7.39.2
  pkg/defaulting/images.go
Labels: enhancement

#629 Fix ci failure for build_operator_check_image_amd64
  .gitlab-ci.yml
Labels: bug

#631 Fix volume mount to have auth token for agent
  controllers/datadogagent/component/agent/default.go
  controllers/datadogagent/component/utils.go
Labels: bug

#633 [feature] Fix log volumemounts
  controllers/datadogagent/feature/logcollection/feature.go
  controllers/datadogagent/feature/logcollection/feature_test.go
Labels: bug

#634 Adding support to override service accounts for components
  apis/datadoghq/v2alpha1/utils.go
  apis/datadoghq/v2alpha1/utils_test.go
Labels: enhancement
