Repository DataDog/datadog-operator, pull requests merged in 2022-04, with the labels that each got.

#460 feat: support admissionController.AgentCommunicationMode
  apis/datadoghq/v1alpha1/const.go
  apis/datadoghq/v1alpha1/datadogagent_types.go
  apis/datadoghq/v1alpha1/test/new.go
  apis/datadoghq/v1alpha1/zz_generated.deepcopy.go
  apis/datadoghq/v1alpha1/zz_generated.openapi.go
  apis/datadoghq/v2alpha1/datadogagent_types.go
  apis/datadoghq/v2alpha1/zz_generated.deepcopy.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  controllers/datadogagent/clusteragent.go
  controllers/datadogagent/clusteragent_test.go
  docs/configuration.md
Labels: enhancement, component/controller

#461 [controllers/datadogagent] Mount tmp volume in DCA and CLC
  apis/datadoghq/v1alpha1/const.go
  controllers/datadogagent/clusteragent.go
  controllers/datadogagent/clusteragent_test.go
  controllers/datadogagent/clusterchecksrunner.go
  controllers/datadogagent/clusterchecksrunner_test.go
  controllers/datadogagent/utils.go
Labels: bug

#459 update rbac to support secret backend multiple providers script
  apis/datadoghq/v1alpha1/const.go
  controllers/datadogagent/clusteragent.go
  controllers/datadogagent/clusteragent_metricsserver.go
  controllers/datadogagent/common_rbac.go
  controllers/datadogagent/common_rbac_test.go
  docs/secret_management.md
Labels: documentation, enhancement, component/controller

#456 Do not enforce `dd-agent` user (UID 101) for the CLC and DCA
  controllers/datadogagent/agent_test.go
  controllers/datadogagent/clusteragent.go
  controllers/datadogagent/clusteragent_test.go
  controllers/datadogagent/clusterchecksrunner.go
  controllers/datadogagent/clusterchecksrunner_test.go
  controllers/datadogagent/utils.go
Labels: bug

#462 tooling: Update golang version to 1.17
  .github/workflows/main.yml
  .github/workflows/release.yaml
  .gitlab-ci.yml
  apis/datadoghq/v1alpha1/zz_generated.deepcopy.go
  apis/datadoghq/v1alpha1/zz_generated.openapi.go
  apis/datadoghq/v2alpha1/zz_generated.deepcopy.go
  apis/datadoghq/v2alpha1/zz_generated.openapi.go
  pkg/secrets/test/decryptor/dummy_decryptor.py
Labels: tooling

#463 [controllers/datadogagent] Mount certificates volume in DCA
  apis/datadoghq/v1alpha1/const.go
  controllers/datadogagent/clusteragent.go
  controllers/datadogagent/clusteragent_test.go
  controllers/datadogagent/utils.go
Labels: bug

#464 fix: update golang version in dockerfile
  Dockerfile
Labels: bug, tooling

#465 [defaulting/images] Update agent to 7.35.0
  pkg/defaulting/images.go
Labels: enhancement, component/controller

#468 Add port names to agent service
  apis/datadoghq/v1alpha1/const.go
  controllers/datadogagent/service.go
Labels: bug

#470 Update default DCA image to 1.19.0
  pkg/defaulting/images.go
Labels: enhancement, component/controller

#438 Share common structs in common/v1 and adds missing fields to v2alpha1
  .gitlab-ci.yml
  Makefile
  apis/datadoghq/common/v1/agent_types.go
  apis/datadoghq/common/v1/types.go
  apis/datadoghq/common/v1/zz_generated.deepcopy.go
  apis/datadoghq/v1alpha1/datadogagent_default.go
  apis/datadoghq/v1alpha1/datadogagent_default_test.go
  apis/datadoghq/v1alpha1/datadogagent_types.go
  apis/datadoghq/v1alpha1/test/new.go
  apis/datadoghq/v1alpha1/zz_generated.deepcopy.go
  apis/datadoghq/v1alpha1/zz_generated.openapi.go
  apis/datadoghq/v2alpha1/datadogagent_conversion.go
  apis/datadoghq/v2alpha1/datadogagent_types.go
  apis/datadoghq/v2alpha1/datadogagent_webhook.go
  apis/datadoghq/v2alpha1/zz_generated.deepcopy.go
  apis/datadoghq/v2alpha1/zz_generated.openapi.go
  cmd/kubectl-datadog/agent/upgrade/upgrade_test.go
  cmd/kubectl-datadog/clusteragent/upgrade/upgrade.go
  cmd/kubectl-datadog/clusteragent/upgrade/upgrade_test.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  controllers/datadogagent/agent_test.go
  controllers/datadogagent/clusteragent_test.go
  controllers/datadogagent/secret_test.go
  controllers/datadogagent/utils.go
  controllers/datadogagent/utils_test.go
  controllers/datadogagent_controller.go
  controllers/datadogagent_controller_test.go
  controllers/testutils/new.go
  docs/configuration.md
  go.mod
  go.sum
  hack/generate-docs.go
  hack/license.sh
  pkg/controller/utils/datadog/metrics_forwarder_test.go
  pkg/secrets/secrets_test.go
  pkg/secrets/testdata/decryptor/dummy_decryptor.py
Labels: enhancement

#472 fix: k8s version detection for agent service
  controllers/datadogagent/service.go
  pkg/utils/version_test.go
Labels: bug, component/controller

#473 [backport] fix: k8s version detection for agent service (#472)
  controllers/datadogagent/service.go
  pkg/utils/version_test.go
Labels: bug

#475 [backport] Add NodeLabelsAsTags and NamespaceLabelsAsTags, remove default Pod behavior
  apis/datadoghq/v1alpha1/const.go
  apis/datadoghq/v1alpha1/datadogagent_default.go
  apis/datadoghq/v1alpha1/datadogagent_types.go
  apis/datadoghq/v1alpha1/zz_generated.deepcopy.go
  apis/datadoghq/v1alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  controllers/datadogagent/agent_test.go
  controllers/datadogagent/utils.go
  controllers/datadogagent/utils_test.go
  docs/configuration.md
Labels: enhancement
