Repository DataDog/datadog-operator, pull requests merged in 2022-07, with the labels that each got.

#537 [ci] fixes to redhat preflight jobs
  .gitlab-ci.yml
  Makefile
Labels: tooling

#527 add dependencies override and ability to rm rbacs by component
  controllers/datadogagent/controller_reconcile_v2.go
  controllers/datadogagent/dependencies/store.go
  controllers/datadogagent/feature/enabledefault/feature.go
  controllers/datadogagent/merger/rbac.go
  controllers/datadogagent/override/dependencies.go
Labels: enhancement, component/controller

#540 [v1alpha1/conversion] Fix confusing log msg
  apis/datadoghq/v1alpha1/datadogagent_conversion.go
Labels: enhancement

#538 Update default agent image tags to 7.37.1 and 1.21.0
  pkg/defaulting/images.go
Labels: enhancement

#542 update default agent image tags (#538)
  pkg/defaulting/images.go
Labels: enhancement

#539 [merger/rbac] Initialize maps
  controllers/datadogagent/merger/rbac.go
Labels: bug

#543 [features] Fix RBACs
  controllers/datadogagent/feature/cspm/feature.go
  controllers/datadogagent/feature/eventcollection/feature.go
  controllers/datadogagent/feature/kubernetesstatecore/feature.go
Labels: bug

#533 Upgrade tooling to work with new RedHat certification workflow
  .gitignore
  .gitlab-ci.yml
  Makefile
  RELEASING.md
  apis/datadoghq/v2alpha1/datadogagent_types.go
  bundle-redhat/manifests/datadog-operator.clusterserviceversion.yaml
  bundle-redhat/manifests/datadoghq.com_datadogagents.yaml
  bundle-redhat/manifests/datadoghq.com_datadogmetrics.yaml
  bundle-redhat/manifests/datadoghq.com_datadogmonitors.yaml
  bundle-redhat/metadata/annotations.yaml
  bundle-redhat/tests/scorecard/config.yaml
  bundle.redhat.Dockerfile
  bundle/manifests/datadoghq.com_datadogagents.yaml
  bundle/metadata/annotations.yaml
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  go.mod
  hack/install-openshift-preflight.sh
  hack/install-operator-manifest-tools.sh
  hack/patch-bundle.sh
  hack/redhat-bundle.sh
Labels: tooling

#544 [feature/default] Delete redundant "namespace" attr
  controllers/datadogagent/feature/enabledefault/feature.go
Labels: refactoring

#546 [v2alpha1] Don't skip
  apis/datadoghq/v2alpha1/datadogagent_types.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
Labels: bug

#547 [reconciler_v2] Keep agent status updated according to DaemonSet
  controllers/datadogagent/controller_reconcile_v2_common.go
Labels: bug

#551 [v1alpha1/conversion] Silence error
  apis/datadoghq/v1alpha1/datadogagent_conversion.go
Labels: enhancement

#545 call defaulting code
  apis/datadoghq/v2alpha1/datadogagent_default.go
  controllers/datadogagent/controller_reconcile_v2.go
  controllers/datadogagent/dependencies/store.go
  docs/how-to-contribute.md
Labels: enhancement, component/controller

#524 arm64 setup
  Makefile
  hack/install-operator-sdk.sh
  hack/install-yq.sh
Labels: tooling

#556 [component/ccr] Fix default service account name
  controllers/datadogagent/component/clusterchecksrunner/default.go
  controllers/datadogagent/component/clusterchecksrunner/default_test.go
Labels: bug

#555 [controllers/datadogagent] Register dogstatsd feature
  controllers/datadogagent/controller.go
Labels: bug

#559 rm underscores from feature directory names
  controllers/datadogagent/controller.go
  controllers/datadogagent/feature/oomkill/feature.go
  controllers/datadogagent/feature/oomkill/feature_test.go
  controllers/datadogagent/feature/prometheusscrape/feature.go
  controllers/datadogagent/feature/prometheusscrape/feature_test.go
  controllers/datadogagent/feature/tcpqueuelength/feature.go
  controllers/datadogagent/feature/tcpqueuelength/feature_test.go
Labels: component/controller, refactoring

#560 [features] Add ClusterChecks feature
  apis/datadoghq/common/const.go
  apis/datadoghq/v1alpha1/const.go
  controllers/datadogagent/clusteragent.go
  controllers/datadogagent/component/clusterchecksrunner/default.go
  controllers/datadogagent/controller.go
  controllers/datadogagent/feature/clusterchecks/feature.go
  controllers/datadogagent/feature/clusterchecks/feature_test.go
  controllers/datadogagent/feature/enabledefault/feature.go
  controllers/datadogagent/feature/ids.go
  controllers/datadogagent/utils.go
  controllers/datadogagent_controller_v2_test.go
  controllers/testutils/agent.go
Labels: enhancement

#562 [merger/security_context] Fix AddCapabilitiesToContainer
  controllers/datadogagent/merger/security_context.go
  controllers/datadogagent/merger/security_context_test.go
Labels: bug

#535 Do not create a pdb if DCA has a single replica
  controllers/datadogagent/controller_test.go
  controllers/datadogagent/poddisruptionbudget.go
Labels: bug

#563 [feature/{npm,usm}] Fix system-probe volume mount perms
  controllers/datadogagent/feature/npm/feature.go
  controllers/datadogagent/feature/npm/feature_test.go
  controllers/datadogagent/feature/usm/feature.go
  controllers/datadogagent/feature/usm/feature_test.go
  controllers/datadogagent/object/volume/volumes.go
Labels: bug

#526 [feature] CWS feature migration
  apis/datadoghq/common/const.go
  controllers/datadogagent/controller.go
  controllers/datadogagent/feature/cws/feature.go
  controllers/datadogagent/feature/cws/feature_test.go
  controllers/datadogagent/feature/ids.go
  controllers/datadogagent/feature/npm/feature_test.go
  controllers/datadogagent_controller_v2_test.go
  controllers/testutils/agent.go
Labels: enhancement

#536 [feature] Migrate orchestrator explorer feature
  apis/datadoghq/common/const.go
  apis/datadoghq/common/envvar.go
  apis/datadoghq/v1alpha1/datadogagent_conversion.go
  apis/datadoghq/v1alpha1/testdata/all.expected.yaml
  apis/datadoghq/v1alpha1/utils.go
  apis/datadoghq/v2alpha1/datadogagent_default.go
  apis/datadoghq/v2alpha1/datadogagent_default_test.go
  apis/datadoghq/v2alpha1/datadogagent_types.go
  apis/datadoghq/v2alpha1/utils.go
  apis/datadoghq/v2alpha1/zz_generated.deepcopy.go
  apis/datadoghq/v2alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  controllers/datadogagent/controller.go
  controllers/datadogagent/feature/orchestratorexplorer/configmap.go
  controllers/datadogagent/feature/orchestratorexplorer/configmap_test.go
  controllers/datadogagent/feature/orchestratorexplorer/const.go
  controllers/datadogagent/feature/orchestratorexplorer/env.go
  controllers/datadogagent/feature/orchestratorexplorer/feature.go
  controllers/datadogagent/feature/orchestratorexplorer/feature_test.go
  controllers/datadogagent/feature/orchestratorexplorer/rbac.go
  controllers/datadogagent/override/global.go
  docs/configuration.v2alpha1.md
Labels: enhancement

#564 [controller_v2_test] Test orchestrator explorer
  controllers/datadogagent_controller_v2_test.go
  controllers/testutils/agent.go
Labels: enhancement

#566 [features] Fix OOM Kill and TCP Queue Length
  controllers/datadogagent/agent_test.go
  controllers/datadogagent/component/agent/default.go
  controllers/datadogagent/feature/cws/feature.go
  controllers/datadogagent/feature/cws/feature_test.go
  controllers/datadogagent/feature/npm/feature.go
  controllers/datadogagent/feature/npm/feature_test.go
  controllers/datadogagent/feature/oomkill/feature.go
  controllers/datadogagent/feature/oomkill/feature_test.go
  controllers/datadogagent/feature/tcpqueuelength/feature.go
  controllers/datadogagent/feature/tcpqueuelength/feature_test.go
  controllers/datadogagent/feature/usm/feature.go
  controllers/datadogagent/feature/usm/feature_test.go
  controllers/datadogagent/utils.go
Labels: bug

#571 [features/factory] Delete unnecessary err return in BuildFeatures funcs
  controllers/datadogagent/clusteragent_test.go
  controllers/datadogagent/controller.go
  controllers/datadogagent/controller_reconcile_v2.go
  controllers/datadogagent/feature/factory.go
Labels: refactoring

#568 [feature/orchestratorexplorer] Set ENVs when running on Cluster Checks Runner
  controllers/datadogagent/feature/orchestratorexplorer/feature.go
  controllers/datadogagent/feature/orchestratorexplorer/feature_test.go
Labels: bug

#567 [controller_v2_test] Extract common test func
  controllers/datadogagent_controller_v2_test.go
Labels: refactoring

#570 [features] Assign IDs to features for more useful logs
  controllers/datadogagent/controller_reconcile_v2.go
  controllers/datadogagent/feature/clusterchecks/feature.go
  controllers/datadogagent/feature/cspm/feature.go
  controllers/datadogagent/feature/cws/feature.go
  controllers/datadogagent/feature/dogstatsd/feature.go
  controllers/datadogagent/feature/dummy/feature.go
  controllers/datadogagent/feature/enabledefault/feature.go
  controllers/datadogagent/feature/eventcollection/feature.go
  controllers/datadogagent/feature/factory.go
  controllers/datadogagent/feature/ids.go
  controllers/datadogagent/feature/kubernetesstatecore/feature.go
  controllers/datadogagent/feature/logcollection/feature.go
  controllers/datadogagent/feature/npm/feature.go
  controllers/datadogagent/feature/oomkill/feature.go
  controllers/datadogagent/feature/orchestratorexplorer/feature.go
  controllers/datadogagent/feature/prometheusscrape/feature.go
  controllers/datadogagent/feature/tcpqueuelength/feature.go
  controllers/datadogagent/feature/types.go
  controllers/datadogagent/feature/usm/feature.go
Labels: enhancement

#574 [defaulting/images] Update agent to 7.38.0
  pkg/defaulting/images.go
Labels: enhancement

#575 fix(check-operator): pass the upgrade check when DatadogAgent is not found
  cmd/check-operator/upgrade/upgrade.go
Labels: bug, component/controller

#577 [defaulting/images] Update DCA to 1.22.0
  pkg/defaulting/images.go
Labels: enhancement

#514 Implement global settings
  apis/datadoghq/common/const.go
  apis/datadoghq/v1alpha1/const.go
  apis/datadoghq/v2alpha1/datadogagent_default.go
  controllers/datadogagent/agent_test.go
  controllers/datadogagent/component/utils.go
  controllers/datadogagent/controller_reconcile_agent.go
  controllers/datadogagent/controller_reconcile_ccr.go
  controllers/datadogagent/controller_reconcile_dca.go
  controllers/datadogagent/controller_reconcile_v2.go
  controllers/datadogagent/dependencies/store.go
  controllers/datadogagent/feature/types.go
  controllers/datadogagent/merger/network_policy.go
  controllers/datadogagent/merger/network_policy_test.go
  controllers/datadogagent/merger/service.go
  controllers/datadogagent/merger/service_test.go
  controllers/datadogagent/override/global.go
  controllers/datadogagent/utils.go
  controllers/datadogagent/utils_kubelet.go
Labels: enhancement

#578 [feature/ksm] Don't schedule on the DaemonSet Agent
  controllers/datadogagent/feature/kubernetesstatecore/configmap.go
  controllers/datadogagent/feature/kubernetesstatecore/configmap_test.go
  controllers/datadogagent/feature/kubernetesstatecore/feature.go
Labels: bug

#580 [feature/cws] Fix tagger auth error
  controllers/datadogagent/component/agent/default.go
  controllers/datadogagent/feature/cws/feature.go
  controllers/datadogagent/feature/cws/feature_test.go
Labels: bug

#582 [component/clusteragent] Change anti-affinity to "preferred"
  controllers/datadogagent/clusteragent_test.go
  controllers/datadogagent/component/clusteragent/default.go
Labels: bug

#581 [controller_v2_test] Test agent with global settings
  controllers/datadogagent_controller_v2_test.go
  controllers/testutils/agent.go
Labels: enhancement
