Repository DataDog/datadog-operator, pull requests merged in 2022-06, with the labels that each got.

#509 add volumeMountManager
  controllers/datadogagent/clusteragent.go
  controllers/datadogagent/clusteragent_test.go
  controllers/datadogagent/feature/cspm/feature.go
  controllers/datadogagent/feature/cspm/feature_test.go
  controllers/datadogagent/feature/fake/PodTemplateManagers.go
  controllers/datadogagent/feature/kubernetesstatecore/feature.go
  controllers/datadogagent/feature/logcollection/feature.go
  controllers/datadogagent/feature/logcollection/feature_test.go
  controllers/datadogagent/feature/npm/feature.go
  controllers/datadogagent/feature/npm/feature_test.go
  controllers/datadogagent/feature/oom_kill/feature.go
  controllers/datadogagent/feature/oom_kill/feature_test.go
  controllers/datadogagent/feature/tcp_queue_length/feature.go
  controllers/datadogagent/feature/tcp_queue_length/feature_test.go
  controllers/datadogagent/feature/types.go
  controllers/datadogagent/feature/usm/feature.go
  controllers/datadogagent/feature/usm/feature_test.go
  controllers/datadogagent/merger/fake/volume_manager.go
  controllers/datadogagent/merger/fake/volume_mount_manager.go
  controllers/datadogagent/merger/volume.go
  controllers/datadogagent/merger/volume_mount.go
  controllers/datadogagent/merger/volume_mount_test.go
  controllers/datadogagent/merger/volumemount.go
Labels: enhancement, component/controller

#513 [defaulting/images] Update agent to 7.36.1 and DCA to 1.20.0
  pkg/defaulting/images.go
Labels: enhancement

#506 default cluster checks runner component
  apis/datadoghq/common/common.go
  apis/datadoghq/common/const.go
  apis/datadoghq/common/envvar.go
  apis/datadoghq/v1alpha1/const.go
  apis/datadoghq/v1alpha1/datadogagent_default.go
  apis/datadoghq/v1alpha1/datadogagent_default_test.go
  controllers/datadogagent/agent_test.go
  controllers/datadogagent/clusteragent.go
  controllers/datadogagent/clusterchecksrunner.go
  controllers/datadogagent/clusterchecksrunner_test.go
  controllers/datadogagent/component/clusterchecksrunner/default.go
  controllers/datadogagent/component/utils.go
  controllers/datadogagent/const.go
  controllers/datadogagent/feature/npm/feature.go
  controllers/datadogagent/feature/npm/feature_test.go
  controllers/datadogagent/utils.go
  controllers/datadogagent/utils_kubelet.go
Labels: enhancement, component/controller

#507 [controllers/datadogagent/component] Implement default agent
  controllers/datadogagent/component/agent/default.go
  controllers/datadogagent/component/utils.go
Labels: component/controller, refactoring

#510 [controllers/datadogagent/component] Implement default agent containers
  apis/datadoghq/common/const.go
  apis/datadoghq/v1alpha1/const.go
  controllers/datadogagent/agent_test.go
  controllers/datadogagent/component/agent/default.go
  controllers/datadogagent/component/utils.go
  controllers/datadogagent/controller_reconcile_agent.go
  controllers/datadogagent/controller_reconcile_v2.go
  controllers/datadogagent/utils.go
Labels: component/controller, refactoring

#487 [feature] Migrate dogstatsd feature
  apis/datadoghq/common/const.go
  apis/datadoghq/common/envvar.go
  apis/datadoghq/v1alpha1/utils.go
  apis/datadoghq/v2alpha1/datadogagent_default.go
  apis/datadoghq/v2alpha1/datadogagent_default_test.go
  apis/datadoghq/v2alpha1/datadogagent_types.go
  apis/datadoghq/v2alpha1/utils.go
  apis/datadoghq/v2alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  controllers/datadogagent/feature/dogstatsd/feature.go
  controllers/datadogagent/feature/dogstatsd/feature_test.go
  controllers/datadogagent/feature/fake/PodTemplateManagers.go
  controllers/datadogagent/feature/ids.go
  controllers/datadogagent/feature/types.go
  controllers/datadogagent/merger/fake/port_manager.go
  controllers/datadogagent/merger/port.go
  controllers/datadogagent/merger/port_test.go
  docs/configuration.v2alpha1.md
Labels: enhancement, component/controller

#517 feat(ksmcore): enable ingress metrics
  controllers/datadogagent/feature/kubernetesstatecore/configmap.go
Labels: enhancement, component/controller

#519 [feature/eventcollection] Add missing nil check
  controllers/datadogagent/feature/eventcollection/feature.go
Labels: bug, component/controller

#521 [v2alpha1] Fix issues so agent and DCA boot without errors
  controllers/datadogagent/component/agent/default.go
  controllers/datadogagent/component/clusteragent/utils.go
  controllers/datadogagent/component/clusterchecksrunner/default.go
  controllers/datadogagent/feature/enabledefault/feature.go
  controllers/datadogagent/feature/enabledefault/rbac.go
  controllers/datadogagent/feature/eventcollection/feature.go
  controllers/datadogagent/feature/eventcollection/feature_test.go
  controllers/datadogagent/override/global.go
  controllers/datadogagent/service.go
Labels: bug

#501 Update system-probe secccomp profile
  controllers/datadogagent/systemprobe.go
Labels: bug

#523 Update base image to fix CVEs
  Dockerfile
Labels: tooling

#522 CWS: fix runtime policies loading, when no config map is defined
  controllers/datadogagent/utils.go
Labels: bug

#530 Update base image to fix CVEs (#523)
  Dockerfile
Labels: tooling

#529 CWS: fix runtime policies loading, when no config map is defined (#522)
  controllers/datadogagent/utils.go
Labels: bug

#528 Update system-probe secccomp profile (#501)
  controllers/datadogagent/systemprobe.go
Labels: bug

#505 Upgrade tooling to work with new RedHat certification workflow
  .gitignore
  .gitlab-ci.yml
  Makefile
  RELEASING.md
  apis/datadoghq/v2alpha1/datadogagent_types.go
  bundle-redhat/manifests/datadog-operator.clusterserviceversion.yaml
  bundle-redhat/manifests/datadoghq.com_datadogagents.yaml
  bundle-redhat/manifests/datadoghq.com_datadogmetrics.yaml
  bundle-redhat/manifests/datadoghq.com_datadogmonitors.yaml
  bundle-redhat/metadata/annotations.yaml
  bundle-redhat/tests/scorecard/config.yaml
  bundle.redhat.Dockerfile
  bundle/manifests/datadog-operator.clusterserviceversion.yaml
  bundle/manifests/datadoghq.com_datadogagents.yaml
  bundle/metadata/annotations.yaml
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  go.mod
  go.sum
  hack/install-openshift-preflight.sh
  hack/install-operator-manifest-tools.sh
  hack/patch-bundle.sh
  hack/redhat-bundle.sh
Labels: tooling

#534 [ci] fix following bundle changes
  .gitlab-ci.yml
  Makefile
Labels: tooling
