Repository DataDog/datadog-operator, pull requests merged in 2022-09, with the labels that each got.

#607 update v2 status
  apis/datadoghq/v2alpha1/datadogagent_types.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  controllers/datadogagent/controller_reconcile_v2_common.go
Labels: bug, component/controller

#609 Default Agent and Cluster-Agent image to 7.39.0
  pkg/defaulting/images.go
Labels: enhancement

#612 update golang version to 1.18.6
  .gitlab-ci.yml
  Dockerfile
  check-operator.Dockerfile
  go.mod
Labels: enhancement

#597 Add OTLP ingest feature
  apis/datadoghq/common/const.go
  apis/datadoghq/common/envvar.go
  apis/datadoghq/v1alpha1/datadogagent_default.go
  apis/datadoghq/v1alpha1/datadogagent_default_test.go
  apis/datadoghq/v1alpha1/datadogagent_types.go
  apis/datadoghq/v1alpha1/zz_generated.deepcopy.go
  apis/datadoghq/v1alpha1/zz_generated.openapi.go
  apis/datadoghq/v2alpha1/datadogagent_default.go
  apis/datadoghq/v2alpha1/datadogagent_default_test.go
  apis/datadoghq/v2alpha1/datadogagent_types.go
  apis/datadoghq/v2alpha1/zz_generated.deepcopy.go
  apis/datadoghq/v2alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  controllers/datadogagent/feature/ids.go
  controllers/datadogagent/feature/otlp/feature.go
  controllers/datadogagent/feature/otlp/feature_test.go
  docs/configuration.v1alpha1.md
  docs/configuration.v2alpha1.md
  examples/datadogagent/datadog-agent-otlp.yaml
Labels: enhancement

#613 [metrics_forwarder] Add missing nil check in setupV2
  pkg/controller/utils/datadog/metrics_forwarder.go
Labels: bug

#610 fix dca default token
  apis/datadoghq/v2alpha1/datadogagent_types.go
  apis/datadoghq/v2alpha1/secret.go
  apis/datadoghq/v2alpha1/zz_generated.deepcopy.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  controllers/datadogagent/controller_reconcile_v2.go
  controllers/datadogagent/feature/enabledefault/feature.go
  controllers/datadogagent/merger/secret.go
  docs/configuration.v2alpha1.md
Labels: enhancement

#617 Add feature-specific network policies
  apis/datadoghq/v1alpha1/utils.go
  apis/datadoghq/v2alpha1/utils.go
  controllers/datadogagent/agent.go
  controllers/datadogagent/feature/apm/feature.go
  controllers/datadogagent/feature/clusterchecks/feature.go
Labels: enhancement

#618 Fix conversion from v1 to v2
  apis/datadoghq/v1alpha1/datadogagent_conversion.go
Labels: bug

#616 support custom checks and configuration
  apis/datadoghq/v1alpha1/datadogagent_conversion.go
  apis/datadoghq/v2alpha1/const.go
  apis/datadoghq/v2alpha1/datadogagent_types.go
  apis/datadoghq/v2alpha1/zz_generated.deepcopy.go
  apis/datadoghq/v2alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  controllers/datadogagent/common_configmap.go
  controllers/datadogagent/common_configmap_test.go
  controllers/datadogagent/component/agent/default.go
  controllers/datadogagent/component/utils.go
  controllers/datadogagent/feature/kubernetesstatecore/configmap.go
  controllers/datadogagent/feature/kubernetesstatecore/configmap_test.go
  controllers/datadogagent/feature/orchestratorexplorer/configmap.go
  controllers/datadogagent/feature/orchestratorexplorer/configmap_test.go
  controllers/datadogagent/object/configmap/configmap.go
  controllers/datadogagent/object/volume/volumes.go
  controllers/datadogagent/override/dependencies.go
  controllers/datadogagent/override/dependencies_test.go
  controllers/datadogagent/override/podtemplatespec.go
  controllers/datadogagent/override/podtemplatespec_test.go
Labels: enhancement
