Repository DataDog/datadog-operator, pull requests merged in 2023-08, with the labels that each got.

#877 Add(check-operator): patch-crd sub command
  cmd/check-operator/patchcrd/patchcrd.go
  cmd/check-operator/root/root.go
  cmd/check-operator/upgrade/upgrade.go
  pkg/plugin/common/options.go
Labels: documentation, enhancement, component/plugin

#872 Improve internal image tagging
  .gitlab-ci.yml
Labels: tooling, qa/skip-qa

#878 Update pr template and add check for milestone
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/pr-linter.yml
Labels: tooling, qa/skip-qa

#881 [tooling] Add more descriptive error message
  .github/workflows/pr-linter.yml
Labels: tooling, qa/skip-qa

#886 [datadogmonitor] update dd api client
  LICENSE-3rdparty.csv
  controllers/datadogmonitor/controller.go
  controllers/datadogmonitor/controller_test.go
  controllers/datadogmonitor/monitor.go
  controllers/datadogmonitor/monitor_test.go
  controllers/datadogmonitor_controller.go
  controllers/setup.go
  go.mod
  go.sum
  pkg/datadogclient/client.go
Labels: enhancement, component/controller, feature/datadog-monitor

#887 Update operator-hub bundle examples
  bundle/manifests/datadog-operator.clusterserviceversion.yaml
  config/samples/datadog-operator-hub-example.yaml
Labels: documentation, qa/skip-qa

#889 [gitlab] fix image name
  .gitlab-ci.yml
Labels: tooling, qa/skip-qa

#888 fix parsing of EDS flag options
  controllers/datadogagent/component/agent/new.go
  controllers/datadogagent/component/agent/new_test.go
Labels: bug, component/controller

#884 update openshift install docs and example
  docs/install-openshift.md
  examples/datadogagent/v2alpha1/datadog-agent-openshift.yaml
Labels: documentation, qa/skip-qa

#891 [ci] update publish_redhat_public_tag job
  .gitlab-ci.yml
Labels: tooling, qa/skip-qa
