Repository DataDog/datadog-operator, pull requests merged in 2023-03, with the labels that each got.

#722 Fix annotation key form MD5 annotation
  controllers/datadogagent/override/podtemplatespec.go
Labels: bug

#727 fix: docker image in gitlab-ci
  .gitlab-ci.yml
Labels: bug, tooling

#726 fix: make capability unique in securityContext
  controllers/datadogagent/clusteragent_test.go
  controllers/datadogagent/clusterchecksrunner_test.go
  controllers/datadogagent/merger/security_context.go
  controllers/datadogagent/merger/security_context_test.go
Labels: bug

#729 cherry-pick #727 on v0.8
  .gitlab-ci.yml
Labels: bug

#732 [defaulting/images] Update agents to 7.43.1
  pkg/defaulting/images.go
Labels: enhancement

#730 Update install-yq.sh to support arm64
  Makefile
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogmetrics.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogmonitors.yaml
  hack/install-openshift-preflight.sh
  hack/install-operator-manifest-tools.sh
  hack/install-operator-sdk.sh
  hack/install-wwhrd.sh
  hack/install-yq.sh
  hack/license.sh
  hack/os-env.sh
  hack/patch-bundle.sh
  hack/patch-crds.sh
  hack/redhat-bundle.sh
  hack/verify-license.sh
Labels: bug

#733 clamoriniere/v0.8/fix seccomp
  controllers/datadogagent/systemprobe.go
Labels: bug

#728 feat: mount custom datadog.yaml in system-probe
  controllers/datadogagent/utils.go
Labels: bug

#737 Change datadogMonitorEnabled to false, incorrectly set in #731
  main.go
Labels: bug

#740 Cluster Agent Auth Lifecycle Improvment
  apis/datadoghq/v1alpha1/datadogagent_conversion.go
  apis/datadoghq/v1alpha1/testdata/all.expected.yaml
  apis/datadoghq/v1alpha1/testdata/all.yaml
  controllers/datadogagent/feature/enabledefault/feature.go
  controllers/datadogagent/feature/externalmetrics/feature.go
  controllers/datadogagent/merger/secret.go
  controllers/datadogagent/merger/secret_test.go
Labels: bug, enhancement

#738 Add `nodeLabelsAsTags` and `namespaceLabelsAsTags` conversion fields
  apis/datadoghq/v1alpha1/datadogagent_conversion_agent.go
  apis/datadoghq/v1alpha1/datadogagent_default_test.go
  apis/datadoghq/v1alpha1/testdata/all.expected.yaml
  apis/datadoghq/v1alpha1/testdata/all.yaml
  apis/datadoghq/v2alpha1/datadogagent_types.go
  apis/datadoghq/v2alpha1/zz_generated.deepcopy.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  controllers/datadogagent/controller_test.go
  controllers/datadogagent/override/global.go
  controllers/testutils/agent.go
  docs/configuration.v2alpha1.md
Labels: bug

#741 Aggregating Dependabot updates
  LICENSE-3rdparty.csv
  go.mod
  go.sum
Labels: dependencies

#743 fix(release): support yq v4 in *bundle.sh scripts
  hack/patch-bundle.sh
  hack/redhat-bundle.sh
Labels: bug, tooling

#665 Update doc generator to add `override` section to `v2alpha1` config d…
  apis/datadoghq/v2alpha1/datadogagent_types.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  docs/configuration.v2alpha1.md
  hack/generate-docs.go
  hack/generate-docs/v2alpha1_overrides.markdown
Labels: documentation

#745 Parametrize maximuGoroutines
  main.go
Labels: enhancement
