Repository DataDog/datadog-operator, pull requests merged in 2023-06, with the labels that each got.

#781 Add Tracefs mount for CWS
  apis/datadoghq/common/const.go
  controllers/datadogagent/feature/cws/feature.go
  controllers/datadogagent/feature/cws/feature_test.go
Labels: enhancement

#804 update channel to stable for bundle images
  Makefile
Labels: enhancement

#805 Remove duplicate flags
  main.go
Labels: bug

#806 fix bundle patch for csv
  hack/patch-bundle-csv-scc.yaml
  hack/patch-bundle.sh
Labels: bug, tooling

#810 [v1.0] fix CSV
  bundle/manifests/datadog-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  hack/os-env.sh
  hack/patch-bundle.sh
Labels: bug

#811 feat: default agent/dca to 7.45.0
  pkg/defaulting/images.go
Labels: enhancement, component/controller

#816 [tools] fix sed cmd for ARM and fix redhat bundle script
  hack/os-env.sh
  hack/redhat-bundle.sh
Labels: bug, tooling

#818 Add list type for custom resources
  apis/datadoghq/v2alpha1/datadogagent_types.go
  apis/datadoghq/v2alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
Labels: bug

#822 [CWS] Add time related syscalls to system-probe-seccomp
  controllers/datadogagent/component/agent/default.go
Labels: enhancement

#769 Use kube-system namespace for clusterrolebinding reference to horizontal-pod-autoscaler service account
  controllers/datadogagent/feature/externalmetrics/feature.go
Labels: bug

#791 [datadogmonitor] add periodic forced sync of API monitor
  apis/datadoghq/v1alpha1/datadogmonitor_types.go
  apis/datadoghq/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/v1/datadoghq.com_datadogmonitors.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogmonitors.yaml
  controllers/datadogmonitor/controller.go
Labels: enhancement, feature/datadog-monitor

#825 Update bundles for latest release
  bundle.Dockerfile
  bundle/manifests/datadog-operator-webhook-service_v1_service.yaml
  bundle/manifests/datadog-operator.clusterserviceversion.yaml
  bundle/manifests/datadoghq.com_datadogagents.yaml
  bundle/manifests/datadoghq.com_datadogmetrics.yaml
  bundle/manifests/datadoghq.com_datadogmonitors.yaml
  bundle/metadata/annotations.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/manifests/bases/datadog-operator.clusterserviceversion.yaml
  hack/patch-bundle.sh
Labels: tooling

#824 fix image pullpolicy and pullsecrets overrides
  controllers/datadogagent/override/podtemplatespec.go
  controllers/datadogagent/override/podtemplatespec_test.go
Labels: bug

#799 [RBAC][KSM] Update KSM RBAC and config to monitor `crd` and `apiservices`
  config/rbac/role.yaml
  controllers/datadogagent/component/utils.go
  controllers/datadogagent/feature/kubernetesstatecore/configmap.go
  controllers/datadogagent/feature/kubernetesstatecore/configmap_test.go
  controllers/datadogagent/feature/kubernetesstatecore/feature.go
  controllers/datadogagent/feature/kubernetesstatecore/rbac.go
  controllers/datadogagent/testdata/ksm_clusterrole.yaml
  controllers/datadogagent_controller.go
  pkg/kubernetes/rbac/const.go
Labels: enhancement
