Repository DataDog/datadog-operator, pull requests merged in 2023-11, with the labels that each got.

#968 [defaulting/images] Set default version of agent and cluster agent to `7.49.0`
  pkg/defaulting/images.go
Labels: enhancement

#836 Allow enabling SBOM collection for host and container images
  apis/datadoghq/common/envvar.go
  apis/datadoghq/v2alpha1/datadogagent_types.go
  apis/datadoghq/v2alpha1/zz_generated.deepcopy.go
  apis/datadoghq/v2alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  controllers/datadogagent/controller.go
  controllers/datadogagent/feature/ids.go
  controllers/datadogagent/feature/sbom/feature.go
  controllers/datadogagent/feature/sbom/feature_test.go
  docs/configuration.v2alpha1.md
Labels: enhancement

#970 Bump go-grpc to 1.56.3
  go.mod
  go.sum
Labels: dependencies, qa/skip-qa

#966 Add profiles base
  PROJECT
  apis/datadoghq/v1alpha1/datadogagentprofile_types.go
  apis/datadoghq/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/v1/datadoghq.com_datadogagentprofiles.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagentprofiles.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_datadoghq_datadogagentprofiles.yaml
  config/crd/patches/webhook_in_datadoghq_datadogagentprofiles.yaml
  config/rbac/datadoghq_datadogagentprofile_editor_role.yaml
  config/rbac/datadoghq_datadogagentprofile_viewer_role.yaml
  config/samples/datadoghq_v1alpha1_datadogagentprofile.yaml
  config/samples/kustomization.yaml
  controllers/datadogagent/controller.go
  controllers/datadogagent/controller_reconcile_v2.go
  controllers/datadogagentprofile/controller.go
  controllers/datadogagentprofile_controller.go
  controllers/setup.go
Labels: enhancement, component/controller, qa/skip-qa

#974 DatadogAgentProfile sample manifest
  config/samples/datadoghq_v1alpha1_datadogagentprofile.yaml
Labels: tooling, qa/skip-qa

#978 Add GCR EU and Asia registries with auto defaulting
  apis/datadoghq/common/const.go
  apis/datadoghq/v2alpha1/datadogagent_default.go
  apis/datadoghq/v2alpha1/datadogagent_default_test.go
  apis/datadoghq/v2alpha1/datadogagent_types.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  docs/configuration.v2alpha1.md
Labels: enhancement

#976 First version to support Agent profiles
  config/rbac/role.yaml
  controllers/datadogagent/controller_reconcile_agent.go
  controllers/datadogagent/controller_reconcile_v2.go
  controllers/datadogagent/override/container.go
  controllers/datadogagent/override/container_test.go
  controllers/datadogagent/override/daemonset.go
  controllers/datadogagent_controller.go
  pkg/agentprofile/agent_profile.go
  pkg/agentprofile/agent_profile_test.go
Labels: enhancement, qa/skip-qa

#980 update examples for v2 datadogagent
  examples/datadogagent/v2alpha1/datadog-agent-all.yaml
  examples/datadogagent/v2alpha1/datadog-agent-logs.yaml
  examples/datadogagent/v2alpha1/datadog-agent-minimum.yaml
  examples/datadogagent/v2alpha1/datadog-agent-on-openshift.yaml
  examples/datadogagent/v2alpha1/datadog-agent-with-apm-hostport.yaml
  examples/datadogagent/v2alpha1/datadog-agent-with-cluster-agent-confd.yaml
  examples/datadogagent/v2alpha1/datadog-agent-with-extraconfd.yaml
  examples/datadogagent/v2alpha1/datadog-agent-with-ksm-core-custom-conf.yaml
  examples/datadogagent/v2alpha1/datadog-agent-with-logs-apm.yaml
  examples/datadogagent/v2alpha1/datadog-agent-with-orchestrator-custom-conf.yaml
  examples/datadogagent/v2alpha1/datadog-agent-with-otlp.yaml
  examples/datadogagent/v2alpha1/datadog-agent-with-secret-backend.yaml
  examples/datadogagent/v2alpha1/datadog-agent-with-secret-keys.yaml
  examples/datadogagent/v2alpha1/datadog-agent-with-unix-socket.yaml
Labels: documentation, qa/skip-qa

#984 Update default Agent/DCA version to 7.49.1
  pkg/defaulting/images.go
Labels: enhancement

#983 Enable by default container-image collection
  apis/datadoghq/common/envvar.go
  controllers/datadogagent/component/agent/default.go
Labels: bug

#991 [Docs] OpenShift docs update
  docs/assets/datadognamespace.png
  docs/assets/openshiftoperatornamespace.png
  docs/assets/operatorhub.png
  docs/install-openshift.md
Labels: documentation, qa/skip-qa

#985 Update integrations_autodiscovery.md
  docs/integrations_autodiscovery.md
Labels: documentation, qa/skip-qa

#990 update patch-bundle script to include spec.replaces field in bundle
  hack/patch-bundle.sh
Labels: tooling

#994 [cherry-pick] update examples for v2 datadogagent (#980)
  examples/datadogagent/v2alpha1/datadog-agent-all.yaml
  examples/datadogagent/v2alpha1/datadog-agent-logs.yaml
  examples/datadogagent/v2alpha1/datadog-agent-minimum.yaml
  examples/datadogagent/v2alpha1/datadog-agent-on-openshift.yaml
  examples/datadogagent/v2alpha1/datadog-agent-with-apm-hostport.yaml
  examples/datadogagent/v2alpha1/datadog-agent-with-cluster-agent-confd.yaml
  examples/datadogagent/v2alpha1/datadog-agent-with-extraconfd.yaml
  examples/datadogagent/v2alpha1/datadog-agent-with-ksm-core-custom-conf.yaml
  examples/datadogagent/v2alpha1/datadog-agent-with-logs-apm.yaml
  examples/datadogagent/v2alpha1/datadog-agent-with-orchestrator-custom-conf.yaml
  examples/datadogagent/v2alpha1/datadog-agent-with-otlp.yaml
  examples/datadogagent/v2alpha1/datadog-agent-with-secret-backend.yaml
  examples/datadogagent/v2alpha1/datadog-agent-with-secret-keys.yaml
  examples/datadogagent/v2alpha1/datadog-agent-with-unix-socket.yaml
Labels: tooling, qa/skip-qa

#987 cherry-pick: Update default Agent/DCA version to 7.49.1 (#984)
  pkg/defaulting/images.go
Labels: enhancement

#988 cherry-pick: Enable by default container-image collection (#983)
  apis/datadoghq/common/envvar.go
  controllers/datadogagent/component/agent/default.go
Labels: bug

#996 [cherry-pick] Update integrations_autodiscovery.md (#985)
  docs/integrations_autodiscovery.md
Labels: documentation

#993 [cherry-pick] update patch-bundle script to include spec.replaces field in bundle (#990)
  hack/patch-bundle.sh
Labels: tooling

#997 Support `CanaryAutoPauseMaxSlowStartDuration` option
  controllers/datadogagent/component/agent/new.go
  controllers/setup.go
  main.go
Labels: enhancement

#1000 [profiles] Add label to DaemonSets
  controllers/datadogagent/controller_reconcile_agent.go
  pkg/agentprofile/agent_profile.go
  pkg/agentprofile/agent_profile_test.go
Labels: enhancement, qa/skip-qa

#992 [profiles] Add integration tests
  controllers/datadogagent_controller_v2_profiles_test.go
  controllers/datadogagent_controller_v2_test.go
Labels: enhancement, qa/skip-qa
