Repository DataDog/datadog-operator, pull requests merged in 2023-01, with the labels that each got.

#678 Ensure all fields are taken into account with NPM
  controllers/datadogagent/feature/npm/feature.go
  controllers/datadogagent/feature/npm/feature_test.go
Labels: bug

#676 Fixing the defaulting and support of the udsHostFilePath
  apis/datadoghq/common/const.go
  apis/datadoghq/common/v1/types.go
  apis/datadoghq/v2alpha1/datadogagent_default.go
  apis/datadoghq/v2alpha1/datadogagent_default_test.go
  controllers/datadogagent/component/utils.go
  controllers/datadogagent/feature/apm/feature.go
  controllers/datadogagent/feature/apm/feature_test.go
  controllers/datadogagent/feature/dogstatsd/feature.go
  controllers/datadogagent/feature/dogstatsd/feature_test.go
  controllers/datadogagent/utils.go
Labels: bug

#677 Fix admission controller default settings panic
  apis/datadoghq/v2alpha1/datadogagent_default.go
  apis/datadoghq/v2alpha1/datadogagent_default_test.go
Labels: bug

#681 Fix incorrect variable used in test
  apis/datadoghq/v2alpha1/datadogagent_default_test.go
Labels: bug

#682 Operator SDK only supports arm starting on 1.23
  Makefile
Labels: component/olm

#679 [orchestrator] Add VPAs for orchestrator RBAC
  controllers/datadogagent/feature/orchestratorexplorer/rbac.go
  controllers/datadogagent/orchestrator.go
  controllers/datadogagent/testdata/orchestrator_clusterrole.yaml
Labels: enhancement

#685 Fix duplicate RBAC breaking External Metrics Provider
  controllers/datadogagent/clusteragent.go
  controllers/datadogagent/feature/externalmetrics/feature.go
  controllers/datadogagent/feature/externalmetrics/rbac.go
  controllers/datadogagent/feature/orchestratorexplorer/rbac.go
  controllers/datadogagent_controller.go
Labels: bug, component/controller

#686 Remove Get verb from Orchestrator Explorer RBAC
  controllers/datadogagent/orchestrator.go
  controllers/datadogagent/testdata/orchestrator_clusterrole.yaml
Labels: bug

#683 Manage either `v1` or `v1beta1` PDB based on current Kubernetes API version
  Makefile
  controllers/datadogagent/controller.go
  controllers/datadogagent/controller_reconcile_v2.go
  controllers/datadogagent/controller_test.go
  controllers/datadogagent/dependencies/store.go
  controllers/datadogagent/finalizer.go
  controllers/datadogagent/poddisruptionbudget.go
  controllers/datadogagent_controller.go
  controllers/setup.go
  pkg/equality/equality.go
  pkg/kubernetes/objects.go
  pkg/kubernetes/objectslist.go
  pkg/kubernetes/platforminfo.go
  pkg/kubernetes/platforminfo_test.go
Labels: bug

#688 Avoid PodSecurityPolicy cleanup if the resource is not supported by Kubernetes API
  controllers/datadogagent/dependencies/store.go
  pkg/kubernetes/const.go
  pkg/kubernetes/platforminfo.go
  pkg/kubernetes/platforminfo_test.go
Labels: bug

#690 Add vpa config to ksm core
  controllers/datadogagent/dependencies/store.go
  controllers/datadogagent/feature/kubernetesstatecore/configmap.go
  controllers/datadogagent/feature/kubernetesstatecore/configmap_test.go
  controllers/datadogagent/feature/kubernetesstatecore/feature.go
  pkg/kubernetes/platforminfo.go
Labels: enhancement

#687 Add devcontainer vscode config
  .devcontainer/devcontainer.json
  Dockerfile
Labels: tooling

#692 Fixing comment for HostPort being disabled
  Makefile
  apis/datadoghq/v2alpha1/datadogagent_types.go
  apis/datadoghq/v2alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
Labels: documentation

#694 Adding hostport for OTLP
  controllers/datadogagent/feature/otlp/feature.go
  controllers/datadogagent/feature/otlp/feature_test.go
Labels: bug, component/controller

#695 [CWS] fix auth token access for system-probe
  controllers/datadogagent/agent_test.go
  controllers/datadogagent/component/agent/default.go
  controllers/datadogagent/utils.go
Labels: bug
