Repository DataDog/datadog-operator, pull requests merged in 2023-12, with the labels that each got.

#989 add dependabot.yaml file
  .github/dependabot.yaml
Labels: dependencies, qa/skip-qa

#973 Profile manifest validation
  apis/datadoghq/v1alpha1/datadogagentprofile_validation.go
  apis/datadoghq/v1alpha1/datadogagentprofile_validation_test.go
Labels: enhancement, qa/skip-qa

#1006 Enabling APM by default
  apis/datadoghq/v2alpha1/datadogagent_default.go
  apis/datadoghq/v2alpha1/datadogagent_default_test.go
  apis/datadoghq/v2alpha1/datadogagent_types.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  docs/configuration.v2alpha1.md
Labels: enhancement

#1009 add dependabot.yaml file (#989)
  .github/dependabot.yaml
Labels: dependencies, qa/skip-qa

#1011 Enabling APM by default (#1006)
  apis/datadoghq/v2alpha1/datadogagent_default.go
  apis/datadoghq/v2alpha1/datadogagent_default_test.go
  apis/datadoghq/v2alpha1/datadogagent_types.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  docs/configuration.v2alpha1.md
Labels: enhancement

#1002 [profiles] Create default profile with a node anti affinity
  config/rbac/role.yaml
  controllers/datadogagent/controller_reconcile_agent.go
  controllers/datadogagent/controller_reconcile_v2.go
  controllers/datadogagent/finalizer.go
  controllers/datadogagent/finalizer_test.go
  controllers/datadogagent/testutils/client_utils.go
  controllers/datadogagent_controller.go
  controllers/datadogagent_controller_v2_profiles_test.go
  pkg/agentprofile/agent_profile.go
  pkg/agentprofile/agent_profile_test.go
Labels: enhancement, qa/skip-qa

#1004 [override/podtemplatespec] Merge affinities
  controllers/datadogagent/override/podtemplatespec.go
  controllers/datadogagent/override/podtemplatespec_test.go
Labels: enhancement, qa/skip-qa

#1003 [profiles] Add pod anti-affinity to agent pods
  controllers/datadogagent_controller_v2_profiles_test.go
  pkg/agentprofile/agent_profile.go
  pkg/agentprofile/agent_profile_test.go
Labels: enhancement, qa/skip-qa

#1013 [CECO-836] DCA namespace resources env var added for V2
  controllers/datadogagent/clusteragent.go
  controllers/datadogagent/component/clusteragent/default.go
Labels: enhancement

#1012 [APMON-406] Set Datadog namespace env variable on Cluster Agent
  apis/datadoghq/common/envvar.go
  controllers/datadogagent/agent_test.go
  controllers/datadogagent/clusteragent_test.go
  controllers/datadogagent/component/clusteragent/default.go
  pkg/controller/utils/shared_utils.go
Labels: enhancement

#1018 Add `createdAd`, `support` fields to bundle CSV file
  hack/patch-bundle.sh
Labels: tooling, qa/skip-qa

#1015 update feature default values and tests
  apis/datadoghq/v2alpha1/datadogagent_default.go
  apis/datadoghq/v2alpha1/datadogagent_default_test.go
Labels: enhancement

#1014 [CECO-754][introspection] Clean up unused ds/eds
  controllers/datadogagent/controller.go
  controllers/datadogagent/controller_reconcile_agent.go
  controllers/datadogagent/controller_reconcile_agent_test.go
  controllers/datadogagent/controller_reconcile_v2.go
  controllers/datadogagent_controller.go
  controllers/setup.go
  pkg/kubernetes/provider.go
  pkg/kubernetes/provider_test.go
Labels: enhancement

#1021 [CECO-755][introspection] Limit provider values using allowlist
  pkg/kubernetes/provider.go
  pkg/kubernetes/provider_test.go
Labels: enhancement

#998 Provide default probe handler httpGet values if not configured in override
  controllers/datadogagent/override/container.go
  controllers/datadogagent/override/container_test.go
Labels: bug

#1019 Update bundles to match 1.3.0 release
  bundle/manifests/datadog-operator.clusterserviceversion.yaml
  bundle/manifests/datadoghq.com_datadogagents.yaml
  bundle/manifests/datadoghq.com_datadogslos.yaml
  config/manager/kustomization.yaml
Labels: tooling, qa/skip-qa

#1026 Fix patch_bundle.sh `spec.replaces` formatting
  hack/patch-bundle.sh
Labels: tooling, qa/skip-qa

#1023 [CECO-849][introspection] Remove unused ds status
  controllers/datadogagent/controller_reconcile_agent.go
  controllers/datadogagent/controller_reconcile_agent_test.go
  controllers/datadogagent/controller_reconcile_v2.go
Labels: bug
