Repository DataDog/datadog-operator, pull requests merged in 2023-09, with the labels that each got.

#893 Fix initContainer overrides
  .gitignore
  controllers/datadogagent/component/agent/new_test.go
  controllers/datadogagent/feature/clusterchecks/feature_test.go
  controllers/datadogagent/feature/fake/PodTemplateManagers.go
  controllers/datadogagent/feature/test/testsuite.go
  controllers/datadogagent/merger/fake/envvar_manager.go
  controllers/datadogagent/merger/fake/volume_mount_manager.go
  controllers/datadogagent/override/container.go
  controllers/datadogagent/override/container_test.go
  controllers/datadogagent/override/podtemplatespec_test.go
  go.mod
  go.sum
Labels: bug, component/controller

#906 default agent/dca to 7.47.0
  pkg/defaulting/images.go
Labels: enhancement, component/controller

#905 Update OpenShift install docs and example for proper DCA behaviour
  docs/install-openshift.md
  examples/datadogagent/v2alpha1/datadog-agent-openshift.yaml
Labels: documentation, qa/skip-qa

#883 upgrade(remote-config): Create cluster agent volume when Remote Config is enabled
  controllers/datadogagent/feature/remoteconfig/feature.go
  controllers/datadogagent/feature/remoteconfig/feature_test.go
Labels: bug

#909 [kustomize] comment out webhook and certmanager config
  config/default/kustomization.yaml
Labels: tooling, qa/skip-qa

#837 Update contribution guide
  docs/how-to-contribute.md
Labels: documentation, qa/skip-qa

#882 Mirza.nurkic/add link to integrations
  docs/getting_started.md
Labels: documentation, qa/skip-qa

#902 Add ochestrator_explorer.enabled for datadog-agent
  controllers/datadogagent/feature/orchestratorexplorer/feature.go
  examples/datadogagent/v2alpha1/datadog-agent-all.yaml
Labels: enhancement

#910 Add rule to allow agent role to curl `/metrics/slis`
  config/rbac/role.yaml
  controllers/datadogagent/component/agent/rbac.go
  pkg/kubernetes/rbac/const.go
Labels: enhancement

#913 [features][admission controller] update rbac for mutating webhook
  apis/datadoghq/common/const.go
  apis/datadoghq/common/envvar.go
  apis/datadoghq/v2alpha1/datadogagent_types.go
  apis/datadoghq/v2alpha1/zz_generated.deepcopy.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  controllers/datadogagent/clusteragent_test.go
  controllers/datadogagent/feature/admissioncontroller/feature.go
  controllers/datadogagent/feature/admissioncontroller/feature_test.go
  controllers/datadogagent/feature/admissioncontroller/rbac.go
  docs/configuration.v2alpha1.md
Labels: enhancement

#894 [datadogmonitor] Return matching downtimes and show downtime status
  apis/datadoghq/v1alpha1/datadogmonitor_types.go
  apis/datadoghq/v1alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogmonitors.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogmonitors.yaml
  controllers/datadogmonitor/controller.go
  controllers/datadogmonitor/controller_test.go
  controllers/datadogmonitor/monitor.go
  controllers/datadogmonitor/monitor_test.go
Labels: enhancement, feature/datadog-monitor

#908 feat(remote-config): Enable Remote Config by default
  apis/datadoghq/v2alpha1/datadogagent_default.go
  apis/datadoghq/v2alpha1/datadogagent_default_test.go
  controllers/datadogagent/feature/remoteconfig/feature.go
  controllers/datadogagent/feature/remoteconfig/feature_test.go
Labels: enhancement

#900 Allow enabling CSPM host benchmarks
  apis/datadoghq/common/envvar.go
  apis/datadoghq/v2alpha1/datadogagent_types.go
  apis/datadoghq/v2alpha1/zz_generated.deepcopy.go
  apis/datadoghq/v2alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  controllers/datadogagent/agent_test.go
  controllers/datadogagent/feature/cspm/feature.go
  controllers/datadogagent/feature/cspm/feature_test.go
  docs/configuration.v2alpha1.md
Labels: enhancement

#916 Add local agent service selector
  controllers/datadogagent/component/utils.go
  controllers/datadogagent/feature/apm/feature.go
  controllers/datadogagent/feature/dogstatsd/feature.go
  controllers/datadogagent/feature/otlp/feature.go
Labels: bug

#915 Add a startup log for V2APIEnabled flag deprecation
  main.go
Labels: enhancement

#875 Add(doc): custom operator image
  docs/custom-operator-image.md
  docs/installation.md
Labels: documentation, qa/skip-qa

#871 [CWS] Added option to disable remote configuration for CWS
  apis/datadoghq/v2alpha1/datadogagent_types.go
  apis/datadoghq/v2alpha1/zz_generated.deepcopy.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  controllers/datadogagent/feature/cws/feature.go
  docs/configuration.v2alpha1.md
Labels: enhancement

#892 Add support for ebpf check
  apis/datadoghq/common/envvar.go
  apis/datadoghq/v2alpha1/datadogagent_types.go
  apis/datadoghq/v2alpha1/zz_generated.deepcopy.go
  apis/datadoghq/v2alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  controllers/datadogagent/controller.go
  controllers/datadogagent/feature/ebpfcheck/feature.go
  controllers/datadogagent/feature/ebpfcheck/feature_test.go
  controllers/datadogagent/feature/ids.go
  controllers/datadogagent_controller_v2_test.go
  controllers/testutils/agent.go
  docs/configuration.v2alpha1.md
Labels: enhancement

#922 [datadogmonitor] Recreate monitor if deleted in the UI
  controllers/datadogmonitor/controller.go
Labels: bug

#920 Docs updates
  apis/datadoghq/common/v1/agent_types.go
  apis/datadoghq/v2alpha1/datadogagent_types.go
  apis/datadoghq/v2alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  docs/configuration.v1alpha1.md
  docs/configuration.v2alpha1.md
  hack/generate-docs/v2alpha1_overrides.markdown
Labels: documentation

#923 Fix Admission Controller default value doc/comment
  apis/datadoghq/v2alpha1/datadogagent_types.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  docs/configuration.v2alpha1.md
Labels: documentation, qa/skip-qa

#925 fix spaces after periods and small wording tweak
  main.go
Labels: documentation

#926 fix spaces after periods and small wording tweak (#925)
  main.go
Labels: documentation

#932 Revert "[datadogmonitor] Return matching downtimes and show downtime status (#894)"
  apis/datadoghq/v1alpha1/datadogmonitor_types.go
  apis/datadoghq/v1alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogmonitors.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogmonitors.yaml
  controllers/datadogmonitor/controller.go
  controllers/datadogmonitor/controller_test.go
  controllers/datadogmonitor/monitor.go
  controllers/datadogmonitor/monitor_test.go
Labels: bug, feature/datadog-monitor

#933 Revert "[datadogmonitor] Return matching downtimes and show downtime status (#894)" (#932)
  apis/datadoghq/v1alpha1/datadogmonitor_types.go
  apis/datadoghq/v1alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogmonitors.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogmonitors.yaml
  controllers/datadogmonitor/controller.go
  controllers/datadogmonitor/controller_test.go
  controllers/datadogmonitor/monitor.go
  controllers/datadogmonitor/monitor_test.go
Labels: bug, feature/datadog-monitor

#930 [defaulting/images] Update agents to 7.47.1
  pkg/defaulting/images.go
Labels: enhancement

#934 [defaulting/images] Update agents to 7.47.1 (#930)
  pkg/defaulting/images.go
Labels: enhancement

#927 [PROCS-1464] Add Process Discovery Feature to Operator
  README.md
  apis/datadoghq/common/envvar.go
  apis/datadoghq/v2alpha1/datadogagent_default.go
  apis/datadoghq/v2alpha1/datadogagent_default_test.go
  apis/datadoghq/v2alpha1/datadogagent_types.go
  apis/datadoghq/v2alpha1/zz_generated.deepcopy.go
  apis/datadoghq/v2alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  controllers/datadogagent/controller.go
  controllers/datadogagent/feature/ids.go
  controllers/datadogagent/feature/processdiscovery/feature.go
  controllers/datadogagent/feature/processdiscovery/feature_test.go
  docs/configuration.v2alpha1.md
Labels: enhancement, mergequeue-status: waiting
