Repository DataDog/datadog-operator, pull requests merged in 2023-10, with the labels that each got.

#938 Update bundles to match 1.2.0 release
  bundle/manifests/datadog-operator.clusterserviceversion.yaml
  bundle/manifests/datadoghq.com_datadogagents.yaml
  bundle/manifests/datadoghq.com_datadogmonitors.yaml
  config/manager/kustomization.yaml
Labels: tooling, qa/skip-qa

#942 Remove ksm `telemetry` parameter
  controllers/datadogagent/feature/kubernetesstatecore/configmap.go
  docs/kubernetes_state_metrics.md
Labels: bug

#936 [CECO-639] Dogstatsd tag cardinality feature
  apis/datadoghq/common/envvar.go
  apis/datadoghq/v2alpha1/datadogagent_types.go
  apis/datadoghq/v2alpha1/test/builder.go
  apis/datadoghq/v2alpha1/zz_generated.deepcopy.go
  apis/datadoghq/v2alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  controllers/datadogagent/feature/dogstatsd/feature.go
  controllers/datadogagent/feature/dogstatsd/feature_test.go
  docs/configuration.v2alpha1.md
Labels: enhancement, component/controller

#941 [docs] update a few docs
  docs/getting_started.md
  docs/how-to-contribute.md
  docs/installation.md
Labels: documentation, qa/skip-qa

#945 fix(remoteConfig): Fix documentation on default behaviour
  apis/datadoghq/v2alpha1/datadogagent_types.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  docs/configuration.v2alpha1.md
Labels: documentation, qa/skip-qa

#928 fix(clusterchecksrunner): Disable Remote Config
  controllers/datadogagent/clusterchecksrunner.go
  controllers/datadogagent/clusterchecksrunner_test.go
Labels: bug

#946 update gitlab runner image to golang 1.19-bullseye
  .gitlab-ci.yml
Labels: tooling, qa/skip-qa

#948 Use Agent default for kubelet client CA and move CA logic to override/global.go
  apis/datadoghq/v2alpha1/datadogagent_default.go
  controllers/datadogagent/override/global.go
Labels: component/controller, refactoring

#949 update default liveness and readiness probes
  apis/datadoghq/common/common.go
  apis/datadoghq/v1alpha1/datadogagent_default.go
  apis/datadoghq/v1alpha1/datadogagent_default_test.go
  controllers/datadogagent/component/agent/default.go
Labels: bug

#950 [kubelet] Add kubelet CA volume mount to security Agent container
  controllers/datadogagent/override/global.go
Labels: bug, component/controller

#943 update agents images to 7.48.0
  pkg/defaulting/images.go
Labels: enhancement

#954 [CECO-721] Operator metrics forwarder : drop application key dependency
  pkg/controller/utils/datadog/metrics_forwarder.go
  pkg/controller/utils/datadog/metrics_forwarder_test.go
Labels: enhancement, component/controller

#956 Update bundles to match v1.2.1 release
  bundle/manifests/datadog-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
Labels: tooling, qa/skip-qa

#957 Update bundle examples config to include DatadogAgent v2alpha1
  config/samples/datadog-operator-hub-example-v1alpha1.yaml
  config/samples/datadog-operator-hub-example-v2alpha1.yaml
  config/samples/kustomization.yaml
Labels: tooling, qa/skip-qa

#955 Check CRD status for reconcile errors in upgrade hook
  cmd/check-operator/upgrade/upgrade.go
  pkg/plugin/common/statuswrapper.go
Labels: enhancement

#807 Adding Service Level Objective CRD and Controller
  apis/datadoghq/v1alpha1/datadogslo_types.go
  apis/datadoghq/v1alpha1/datadogslo_validation.go
  apis/datadoghq/v1alpha1/datadogslo_validation_test.go
  apis/datadoghq/v1alpha1/zz_generated.deepcopy.go
  apis/datadoghq/v1alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogslos.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogslos.yaml
  config/crd/kustomization.yaml
  config/rbac/role.yaml
  controllers/datadogmonitor/controller.go
  controllers/datadogslo/controller.go
  controllers/datadogslo/controller_test.go
  controllers/datadogslo/slo.go
  controllers/datadogslo/slo_test.go
  controllers/datadogslo_controller.go
  controllers/finalizer/finalizer.go
  controllers/finalizer/finalizer_test.go
  controllers/setup.go
  controllers/utils/tag.go
  examples/datadogslo/metric-example.yaml
  examples/datadogslo/metric-usm-example.yaml
  examples/datadogslo/monitor-example.yaml
  go.mod
  go.sum
  main.go
  pkg/controller/utils/condition/condition_generic.go
  pkg/controller/utils/const.go
  pkg/controller/utils/list.go
  pkg/datadogclient/client.go
Labels: enhancement, editorial review

#963 [slo] fix generated files
  apis/datadoghq/v1alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogslos.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogslos.yaml
Labels: bug
