Repository DataDog/datadog-operator, pull requests merged in 2023-07, with the labels that each got.

#794 [datadogmonitor] add option in spec to disable required tags
  apis/datadoghq/v1alpha1/datadogmonitor_types.go
  apis/datadoghq/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/v1/datadoghq.com_datadogmonitors.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogmonitors.yaml
  controllers/datadogmonitor/controller.go
Labels: enhancement, feature/datadog-monitor

#834 feat: default agent/dca to 7.46.0
  pkg/defaulting/images.go
Labels: enhancement, component/controller

#835 update feature factory to process feature if disabled but configured
  controllers/datadogagent/controller_reconcile_agent.go
  controllers/datadogagent/controller_reconcile_ccr.go
  controllers/datadogagent/controller_reconcile_dca.go
  controllers/datadogagent/feature/factory.go
  controllers/datadogagent/feature/types.go
  controllers/datadogagent/feature/types_test.go
Labels: bug, component/controller

#829 Disable conversion webhook by default
  main.go
Labels: refactoring

#839 upgrade(remoteConfig): Explicitly disable Remote Configuration when …
  controllers/datadogagent/feature/remoteconfig/feature.go
  controllers/datadogagent/feature/remoteconfig/feature_test.go
Labels: enhancement

#838 [datadogmonitor] add support for site envvar
  controllers/setup.go
  pkg/config/config.go
  pkg/controller/utils/datadog/metrics_forwarder.go
  pkg/datadogclient/client.go
Labels: bug

#840 [v1.1][datadogmonitor] add support for site envvar
  controllers/setup.go
  pkg/config/config.go
  pkg/controller/utils/datadog/metrics_forwarder.go
  pkg/datadogclient/client.go
Labels: bug

#842 fix log monitor example
  examples/datadogmonitor/log-alert-monitor-test.yaml
Labels: documentation

#828 Add grpc port and http port to service when otlp is enabled
  controllers/datadogagent/feature/otlp/feature.go
Labels: bug

#843 Force pretty print CRDs for consistent formatting
  config/crd/bases/v1/datadoghq.com_datadogmetrics.yaml
  config/crd/bases/v1/datadoghq.com_datadogmonitors.yaml
  hack/patch-crds.sh
Labels: refactoring

#844 Fix orchestrator explorer default panic
  apis/datadoghq/v2alpha1/datadogagent_default.go
  apis/datadoghq/v2alpha1/datadogagent_default_test.go
Labels: bug

#848 [v1.1] add grpc port and http port to service when otlp is enabled (#828)
  controllers/datadogagent/feature/otlp/feature.go
Labels: bug

#851 Fix EDS canary panic
  controllers/datadogagent/component/agent/new.go
Labels: bug

#852 [tooling] ci lint fix
  .golangci.toml
Labels: tooling, qa/skip-qa

#849 update dsd and apm socket paths
  apis/datadoghq/common/const.go
  apis/datadoghq/v2alpha1/datadogagent_default.go
  controllers/datadogagent/agent_test.go
  controllers/datadogagent/component/agent/default.go
  controllers/datadogagent/feature/apm/feature.go
  controllers/datadogagent/feature/apm/feature_test.go
  controllers/datadogagent/feature/dogstatsd/feature.go
  controllers/datadogagent/feature/dogstatsd/feature_test.go
  controllers/datadogagent/merger/volume_mount.go
  controllers/datadogagent/utils_test.go
Labels: bug, component/controller

#847 [CONT-4042] Pass its pod name to the cluster-agent
  apis/datadoghq/common/envvar.go
  controllers/datadogagent/clusteragent.go
  controllers/datadogagent/clusteragent_test.go
  controllers/datadogagent/component/clusteragent/default.go
Labels: enhancement, component/controller

#853 [v1.1] update dsd and apm socket paths (#849)
  apis/datadoghq/common/const.go
  apis/datadoghq/v2alpha1/datadogagent_default.go
  controllers/datadogagent/agent_test.go
  controllers/datadogagent/component/agent/default.go
  controllers/datadogagent/feature/apm/feature.go
  controllers/datadogagent/feature/apm/feature_test.go
  controllers/datadogagent/feature/dogstatsd/feature.go
  controllers/datadogagent/feature/dogstatsd/feature_test.go
  controllers/datadogagent/merger/volume_mount.go
  controllers/datadogagent/utils_test.go
Labels: bug

#854 [v1.1] Pass pod name to the cluster-agent
  apis/datadoghq/common/envvar.go
  controllers/datadogagent/clusteragent.go
  controllers/datadogagent/clusteragent_test.go
  controllers/datadogagent/component/clusteragent/default.go
Labels: bug

#850 [ksmfeature] fix recognition of default image
  controllers/datadogagent/feature/kubernetesstatecore/feature.go
Labels: bug

#846 add default clusterrole creation for cluster checks runner
  controllers/datadogagent/component/clusterchecksrunner/default.go
  controllers/datadogagent/feature/enabledefault/feature.go
Labels: bug

#856 [v1.1] add default clusterrole creation for cluster checks runner
  controllers/datadogagent/component/clusterchecksrunner/default.go
  controllers/datadogagent/feature/enabledefault/feature.go
Labels: bug

#858 Fix agent local service creation for dogstatsd and apm (#841)
  apis/datadoghq/common/const.go
  controllers/datadogagent/component/utils.go
  controllers/datadogagent/feature/apm/feature.go
  controllers/datadogagent/feature/dogstatsd/feature.go
  controllers/datadogagent/feature/dogstatsd/feature_test.go
Labels: bug

#860 Set local internal traffic policy for relevant features
  controllers/datadogagent/feature/apm/feature.go
  controllers/datadogagent/feature/otlp/feature.go
Labels: bug

#859 instruct the core agent that CWS/CSPM is enabled
  controllers/datadogagent/feature/cspm/feature.go
  controllers/datadogagent/feature/cws/feature.go
Labels: bug

#861 [ksmfeature] fix bug where service account was being overwritten
  controllers/datadogagent/feature/kubernetesstatecore/feature.go
Labels: bug

#866 [v1.1][ksmfeature] fix bug where service account was being overwritten
  controllers/datadogagent/feature/kubernetesstatecore/feature.go
Labels: bug

#867 [v1.1] format agent version check
  pkg/utils/version.go
  pkg/utils/version_test.go
Labels: enhancement

#868 add additional permissions to CCR clusterrole
  controllers/datadogagent/component/clusterchecksrunner/default.go
Labels: bug

#869 [v1.1] add additional permissions to ccr clusterrole (#868)
  controllers/datadogagent/component/clusterchecksrunner/default.go
Labels: bug

#870 Allow manual push to staging
  .gitlab-ci.yml
Labels: tooling
