Repository DataDog/datadog-operator, pull requests merged in 2024-07, with the labels that each got.

#1255 [external metrics] fix configuration when registerAPIService is false
  controllers/datadogagent/feature/externalmetrics/feature.go
Labels: bug

#1257 add datadog agent profiles CRD to bundle, and update bundle make command to build multiarch image
  Makefile
  bundle/manifests/datadoghq.com_datadogagentprofiles.yaml
Labels: tooling, qa/skip-qa

#1258 remove v1alpha1 datadogagent examples
  config/samples/datadog-agent-apm.yaml
  config/samples/datadog-agent-logs-apm.yaml
  config/samples/datadog-agent-logs.yaml
  config/samples/datadog-agent-openshift.yaml
  config/samples/datadog-agent-with-clusteragent-with-orchestrator.yaml
  config/samples/datadog-agent-with-clusteragent.yaml
  config/samples/datadog-agent-with-dca-clusterchecksrunner.yaml
  config/samples/datadog-agent-with-tolerations.yaml
  config/samples/datadog-agent.yaml
  config/samples/datadog-operator-hub-example-v1alpha1.yaml
  examples/datadogagent/datadog-agent-all.yaml
  examples/datadogagent/datadog-agent-minimum.yaml
  examples/datadogagent/datadog-agent-on-openshift.yaml
  examples/datadogagent/datadog-agent-with-apm-hostport.yaml
  examples/datadogagent/datadog-agent-with-cluster-agent-confd.yaml
  examples/datadogagent/datadog-agent-with-clusteragent.yaml
  examples/datadogagent/datadog-agent-with-credential-secret.yaml
  examples/datadogagent/datadog-agent-with-dca-clusterchecksrunner.yaml
  examples/datadogagent/datadog-agent-with-dca-with-orchestrator-explorer.yaml
  examples/datadogagent/datadog-agent-with-extraconfd.yaml
  examples/datadogagent/datadog-agent-with-ksm-core-custom-conf.yaml
  examples/datadogagent/datadog-agent-with-logs-apm.yaml
  examples/datadogagent/datadog-agent-with-orchestrator-custom-conf.yaml
  examples/datadogagent/datadog-agent-with-otlp.yaml
  examples/datadogagent/datadog-agent-with-prometheus-autodiscovery-advanced-config.yaml
  examples/datadogagent/datadog-agent-with-prometheus-autodiscovery.yaml
  examples/datadogagent/datadog-agent-with-registry.yaml
  examples/datadogagent/datadog-agent-with-remote-configuration.yaml
  examples/datadogagent/datadog-agent-with-secret-backend.yaml
  examples/datadogagent/datadog-agent-with-secret-keys.yaml
  examples/datadogagent/datadog-agent-with-tolerations.yaml
  examples/datadogagent/datadog-agent-with-unix-socket.yaml
  examples/datadogagent/v1alpha1/datadog-agent-all.yaml
  examples/datadogagent/v1alpha1/datadog-agent-apm.yaml
  examples/datadogagent/v1alpha1/datadog-agent-cluster-agent-confd.yaml
  examples/datadogagent/v1alpha1/datadog-agent-ksm-core-custom-conf.yaml
  examples/datadogagent/v1alpha1/datadog-agent-logs-apm.yaml
  examples/datadogagent/v1alpha1/datadog-agent-logs.yaml
  examples/datadogagent/v1alpha1/datadog-agent-openshift.yaml
  examples/datadogagent/v1alpha1/datadog-agent-orchestrator-custom-conf.yaml
  examples/datadogagent/v1alpha1/datadog-agent-otlp.yaml
  examples/datadogagent/v1alpha1/datadog-agent-secret-backend.yaml
  examples/datadogagent/v1alpha1/datadog-agent-unix-socket.yaml
  examples/datadogagent/v1alpha1/datadog-agent-with-clusteragent.yaml
  examples/datadogagent/v1alpha1/datadog-agent-with-credential-secret.yaml
  examples/datadogagent/v1alpha1/datadog-agent-with-dca-clusterchecksrunner.yaml
  examples/datadogagent/v1alpha1/datadog-agent-with-dca-with-orchestrator-explorer.yaml
  examples/datadogagent/v1alpha1/datadog-agent-with-prometheus-autodiscovery-advanced-config.yaml
  examples/datadogagent/v1alpha1/datadog-agent-with-prometheus-autodiscovery.yaml
  examples/datadogagent/v1alpha1/datadog-agent-with-registry.yaml
  examples/datadogagent/v1alpha1/datadog-agent-with-tolerations.yaml
  examples/datadogagent/v1alpha1/datadog-agent.yaml
Labels: documentation, qa/skip-qa

#1265 [docs] fix broken links to examples
  docs/cluster_agent_setup.md
  docs/configuration.v2alpha1.md
  docs/getting_started.md
  docs/how-to-contribute.md
  hack/generate-docs/v2alpha1_footer.markdown
Labels: documentation, qa/skip-qa

#1252 [gitlab] add support for multiarch images in redhat
  .gitlab-ci.yml
  Makefile
  config/manifests/bases/datadog-operator.clusterserviceversion.yaml
Labels: tooling

#1260 fix bundle examples
  config/samples/datadog-operator-hub-example-v2alpha1.yaml
  config/samples/datadoghq_v1alpha1_datadogmetric.yaml
  config/samples/datadoghq_v2alpha1_datadogagent.yaml
  config/samples/kustomization.yaml
Labels: tooling, qa/skip-qa

#1264 [profiles] Remove validation for container resource
  apis/datadoghq/v1alpha1/datadogagentprofile_validation.go
  apis/datadoghq/v1alpha1/datadogagentprofile_validation_test.go
Labels: bug

#1244 Adding strategy override to DCA and CLC
  apis/datadoghq/v2alpha1/datadogagent_types.go
  apis/datadoghq/v2alpha1/zz_generated.deepcopy.go
  apis/datadoghq/v2alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  config/manager/kustomization.yaml
  controllers/datadogagent/override/daemonset.go
  controllers/datadogagent/override/daemonset_test.go
  controllers/datadogagent/override/deploymentspec.go
  controllers/datadogagent/override/deploymentspec_test.go
  docs/configuration.v2alpha1.md
Labels: enhancement

#1270 Pin kube-openapi version
  Makefile
Labels: dependencies, qa/skip-qa

#1273 Run go mod tidy and add dependabot label
  .github/dependabot.yaml
  go.mod
Labels: tooling, qa/skip-qa

#1279 fix(kustomization): fix deploy file
  config/manager/kustomization.yaml
Labels: bug, qa/skip-qa

#1272 update datadog-agent remote config package dependency
  LICENSE-3rdparty.csv
  go.mod
  go.sum
  go.work.sum
  pkg/remoteconfig/updater.go
Labels: dependencies

#1234 feat(probe): add startup probes
  apis/datadoghq/common/common.go
  apis/datadoghq/common/const.go
  controllers/datadogagent/agent_test.go
  controllers/datadogagent/clusteragent_test.go
  controllers/datadogagent/component/agent/default.go
  controllers/datadogagent/component/clusteragent/default.go
  controllers/datadogagent/component/clusteragent/default_test.go
  controllers/datadogagent/component/clusterchecksrunner/default.go
Labels: enhancement, mergequeue-status: waiting

#1277 chore(devcontainer): bump Go version to 1.22
  .devcontainer/devcontainer.json
  .github/CODEOWNERS
Labels: tooling, qa/skip-qa

#1195 [CONTP-136] Add Language Detection Config to APM SSI
  apis/datadoghq/common/envvar.go
  apis/datadoghq/v2alpha1/datadogagent_default.go
  apis/datadoghq/v2alpha1/datadogagent_default_test.go
  apis/datadoghq/v2alpha1/datadogagent_types.go
  apis/datadoghq/v2alpha1/test/builder.go
  apis/datadoghq/v2alpha1/zz_generated.deepcopy.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  controllers/datadogagent/feature/apm/const.go
  controllers/datadogagent/feature/apm/feature.go
  controllers/datadogagent/feature/apm/feature_test.go
  controllers/datadogagent/feature/apm/rbac.go
  docs/configuration.v2alpha1.md
  pkg/kubernetes/rbac/const.go
Labels: enhancement

#1282 fix default agent test
  apis/datadoghq/v2alpha1/datadogagent_default_test.go
Labels: bug, qa/skip-qa

#1281 fix kustomize manager tag
  config/manager/kustomization.yaml
Labels: tooling, qa/skip-qa

#1230 [CECO-1240] Rename profile label key
  controllers/datadogagent/controller_reconcile_agent.go
  controllers/datadogagent/controller_reconcile_v2.go
  controllers/datadogagent/controller_reconcile_v2_common.go
  controllers/datadogagent/controller_test.go
  controllers/datadogagent/finalizer.go
  pkg/agentprofile/agent_profile.go
  pkg/agentprofile/agent_profile_test.go
Labels: enhancement

#1254 [profiles] Improve DAP name length error
  pkg/agentprofile/agent_profile.go
  pkg/agentprofile/agent_profile_test.go
Labels: enhancement

#1256 [profiles] Override node agent env vars with profiles
  apis/datadoghq/v1alpha1/datadogagentprofile_types.go
  apis/datadoghq/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/v1/datadoghq.com_datadogagentprofiles.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagentprofiles.yaml
  controllers/datadogagent_controller_v2_profiles_test.go
  pkg/agentprofile/agent_profile.go
Labels: enhancement

#1278 Update CODEOWNERS remove container-integrations from owners
  .github/CODEOWNERS
Labels: tooling, qa/skip-qa, mergequeue-status: removed

#1253 [CONTP-266] Add namespaceAnnotationsAsTags to operator
  apis/datadoghq/common/envvar.go
  apis/datadoghq/v1alpha1/datadogagent_types.go
  apis/datadoghq/v1alpha1/zz_generated.deepcopy.go
  apis/datadoghq/v1alpha1/zz_generated.openapi.go
  apis/datadoghq/v2alpha1/datadogagent_types.go
  apis/datadoghq/v2alpha1/zz_generated.deepcopy.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  controllers/datadogagent/controller_test.go
  controllers/datadogagent/override/global.go
  controllers/datadogagent/utils.go
  controllers/datadogagent/utils_test.go
  controllers/testutils/agent.go
  docs/configuration.v2alpha1.md
  go.work.sum
Labels: enhancement

#1285 Update make bundle command to include `--apis-dir` flag
  Makefile
Labels: tooling

#1245 DatadogAgentProfiles valid metric
  controllers/datadogagent/controller_reconcile_v2.go
  controllers/datadogagent_controller.go
  controllers/metrics/const.go
  controllers/metrics/datadogagentprofile.go
  pkg/agentprofile/agent_profile.go
Labels: enhancement

#1201 Add uncompressed layers support using either mounts or overlayfs
  apis/datadoghq/common/const.go
  apis/datadoghq/common/envvar.go
  apis/datadoghq/v2alpha1/datadogagent_types.go
  apis/datadoghq/v2alpha1/zz_generated.deepcopy.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  controllers/datadogagent/feature/sbom/feature.go
  controllers/datadogagent/feature/sbom/feature_test.go
  docs/configuration.v2alpha1.md
  pkg/remoteconfig/updater.go
Labels: enhancement

#1269 Add minimal OTel Agent container
  apis/datadoghq/common/const.go
  apis/datadoghq/common/v1/types.go
  controllers/datadogagent/component/agent/default.go
  controllers/datadogagent/controller.go
  controllers/datadogagent/feature/enabledefault/feature.go
  controllers/datadogagent/feature/types.go
  controllers/datadogagent/merger/utils.go
  controllers/setup.go
  main.go
Labels: enhancement

#1235 Support for CRD-specific watch namespaces configuration
  main.go
  pkg/config/config.go
  pkg/config/config_test.go
Labels: enhancement

#1225 Add kubelet check e2e test
  Makefile
  config/e2e/e2e-manager.yaml
  config/e2e/kustomization.yaml
  go.mod
  go.work.sum
  test/e2e/common_test.go
  test/e2e/go.mod
  test/e2e/go.sum
  test/e2e/kind_e2e_test.go
Labels: tooling, qa/skip-qa

#1118 Add DatadogPodAutoscaler resource
  PROJECT
  apis/datadoghq/v1alpha1/datadogpodautoscaler_types.go
  apis/datadoghq/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/v1/datadoghq.com_datadogpodautoscalers.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogpodautoscalers.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_datadoghq_datadogpodautoscalers.yaml
  config/crd/patches/webhook_in_datadoghq_datadogpodautoscalers.yaml
  config/rbac/datadoghq_datadogpodautoscaler_editor_role.yaml
  config/rbac/datadoghq_datadogpodautoscaler_viewer_role.yaml
  config/samples/datadoghq_v1alpha1_datadogpodautoscaler.yaml
  config/samples/kustomization.yaml
  hack/patch-crds.sh
Labels: enhancement, qa/skip-qa

#1287 Bump default Agent version to 7.55
  pkg/defaulting/images.go
Labels: enhancement

#1259 [datadogmonitor] Adding renotifyStatuses and indicating Locked is deprecated
  apis/datadoghq/v1alpha1/datadogmonitor_types.go
  apis/datadoghq/v1alpha1/zz_generated.deepcopy.go
  apis/datadoghq/v1alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogmonitors.yaml
  controllers/datadogmonitor/monitor.go
  controllers/datadogmonitor/monitor_test.go
Labels: enhancement

#1291 [profiles] Add label overrides for profiles
  apis/datadoghq/v1alpha1/datadogagentprofile_types.go
  apis/datadoghq/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/v1/datadoghq.com_datadogagentprofiles.yaml
  pkg/agentprofile/agent_profile.go
  pkg/agentprofile/agent_profile_test.go
Labels: enhancement

#1292 fix generated controller manager rbacs
  Makefile
  config/rbac/role.yaml
  controllers/datadogagent_controller.go
Labels: bug, tooling

#1293 add service catalog file
  service.datadog.yaml
Labels: tooling, qa/skip-qa

#1289 Add support for workload autoscaling feature
  apis/datadoghq/common/envvar.go
  apis/datadoghq/v2alpha1/datadogagent_types.go
  apis/datadoghq/v2alpha1/zz_generated.deepcopy.go
  apis/datadoghq/v2alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/rbac/role.yaml
  controllers/datadogagent/feature/autoscaling/feature.go
  controllers/datadogagent/feature/autoscaling/feature_test.go
  controllers/datadogagent/feature/autoscaling/rbac.go
  controllers/datadogagent/feature/ids.go
  controllers/datadogagent/feature/test/testsuite.go
  controllers/datadogagent/utils.go
  controllers/datadogagent_controller.go
  docs/configuration.v2alpha1.md
  pkg/kubernetes/rbac/const.go
Labels: enhancement

#1295 Add support for unbundled events in event collection
  apis/datadoghq/common/const.go
  apis/datadoghq/v2alpha1/datadogagent_default.go
  apis/datadoghq/v2alpha1/datadogagent_types.go
  apis/datadoghq/v2alpha1/test/builder.go
  apis/datadoghq/v2alpha1/zz_generated.deepcopy.go
  apis/datadoghq/v2alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/rbac/role.yaml
  controllers/datadogagent/controller.go
  controllers/datadogagent/feature/eventcollection/configmap.go
  controllers/datadogagent/feature/eventcollection/const.go
  controllers/datadogagent/feature/eventcollection/feature.go
  controllers/datadogagent/feature/eventcollection/feature_test.go
  controllers/datadogagent/feature/ids.go
  controllers/datadogagent/feature/orchestratorexplorer/configmap.go
  controllers/datadogagent_controller.go
  docs/configuration.v2alpha1.md
Labels: enhancement, component/controller

#1296 Use emptyDir for auth_token in Cluster Agent (aligned with Agent)
  controllers/datadogagent/clusteragent_test.go
  controllers/datadogagent/component/clusteragent/default.go
  controllers/datadogagent/component/clusteragent/default_test.go
  controllers/datadogagent/feature/logcollection/feature.go
Labels: bug, mergequeue-status: waiting

#1297 use service catalog schema version v2
  service.datadog.yaml
Labels: tooling, qa/skip-qa

#1298 [service catalog] update fields for v2 schema
  service.datadog.yaml
Labels: tooling, qa/skip-qa

#1300 update gitlab jobs for nightly deploy
  .gitlab-ci.yml
Labels: tooling, qa/skip-qa

#1301 [conductor] add test target
  service.datadog.yaml
Labels: tooling, qa/skip-qa

#1308 Improve resource.Quantity to float conversion for SLOs
  controllers/datadogslo/slo.go
  controllers/datadogslo/slo_test.go
Labels: bug

#1310 Add more profiler types
  main.go
Labels: enhancement

#1312 rename Language Detection struct (#1307)
  apis/datadoghq/v2alpha1/datadogagent_default.go
  apis/datadoghq/v2alpha1/datadogagent_default_test.go
  apis/datadoghq/v2alpha1/datadogagent_types.go
  apis/datadoghq/v2alpha1/test/builder.go
  apis/datadoghq/v2alpha1/zz_generated.deepcopy.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  docs/configuration.v2alpha1.md
Labels: refactoring, qa/skip-qa

#1286 [cleanup] remove unused v1alpha1 code
  .golangci.toml
  controllers/datadogagent/agent.go
  controllers/datadogagent/agent_eds_test.go
  controllers/datadogagent/agent_rbac.go
  controllers/datadogagent/agent_test.go
  controllers/datadogagent/clusteragent.go
  controllers/datadogagent/clusteragent_metricsserver.go
  controllers/datadogagent/clusteragent_test.go
  controllers/datadogagent/clusterchecksrunner.go
  controllers/datadogagent/clusterchecksrunner_rbac.go
  controllers/datadogagent/clusterchecksrunner_test.go
  controllers/datadogagent/common_configmap.go
  controllers/datadogagent/common_configmap_test.go
  controllers/datadogagent/common_networkpolicy.go
  controllers/datadogagent/common_rbac.go
  controllers/datadogagent/common_rbac_test.go
  controllers/datadogagent/controller.go
  controllers/datadogagent/controller_test.go
  controllers/datadogagent/controller_v2_test.go
  controllers/datadogagent/finalizer.go
  controllers/datadogagent/finalizer_test.go
  controllers/datadogagent/orchestrator.go
  controllers/datadogagent/orchestrator_test.go
  controllers/datadogagent/poddisruptionbudget.go
  controllers/datadogagent/secret.go
  controllers/datadogagent/secret_agent.go
  controllers/datadogagent/secret_clusteragent.go
  controllers/datadogagent/secret_test.go
  controllers/datadogagent/service.go
  controllers/datadogagent/systemprobe.go
  controllers/datadogagent/utils.go
  controllers/datadogagent/utils_kubelet.go
  controllers/datadogagent/utils_test.go
  controllers/datadogagent_controller.go
  controllers/setup.go
  pkg/controller/utils/datadog/forwarders_manager.go
  pkg/controller/utils/datadog/metrics_forwarder.go
  pkg/controller/utils/datadog/metrics_forwarder_test.go
Labels: refactoring

#1311 [gitlab] update nightly operator deployment job
  .gitlab-ci.yml
  service.datadog.yaml
Labels: tooling, qa/skip-qa

#1313 [cleanup] rm v2 from function names in metrics forwarder
  pkg/controller/utils/datadog/metrics_forwarder.go
  pkg/controller/utils/datadog/metrics_forwarder_test.go
Labels: refactoring

#1314 [conductor] disable failure notifications for now
  service.datadog.yaml
Labels: tooling, qa/skip-qa

#1319 [temp] output env in gitlab job
  .gitlab-ci.yml
Labels: tooling, qa/skip-qa

#1302 [profiles] Add profile label key to node affinity
  controllers/datadogagent_controller_v2_profiles_test.go
  pkg/agentprofile/agent_profile.go
  pkg/agentprofile/agent_profile_test.go
Labels: enhancement

#1320 [profiles] Use deepcopy for patch
  controllers/datadogagent/controller_reconcile_agent.go
  controllers/datadogagent/finalizer.go
Labels: bug

#1321 [gitlab] fix conductor envvar
  .gitlab-ci.yml
Labels: tooling, qa/skip-qa

#1326 [gitlab] fix incorrect var
  .gitlab-ci.yml
Labels: bug, tooling, qa/skip-qa

#1323 Add more profiler types (#1310)
  main.go
Labels: enhancement, qa/skip-qa

#1324 Add profile label key to node affinity (#1302)
  controllers/datadogagent_controller_v2_profiles_test.go
  pkg/agentprofile/agent_profile.go
  pkg/agentprofile/agent_profile_test.go
Labels: enhancement

#1325 [profiles] Use deepcopy for patch (#1320)
  controllers/datadogagent/controller_reconcile_agent.go
  controllers/datadogagent/finalizer.go
Labels: bug

#1317 [profiles] Reduce patch frequency
  controllers/datadogagent/controller_reconcile_agent.go
  controllers/datadogagent/controller_reconcile_agent_test.go
Labels: bug

#1328 [gitlab] small fixes for gitlab job rules
  .gitlab-ci.yml
Labels: tooling, qa/skip-qa

#1331 [sdp] adjust cron schedule for nightly
  service.datadog.yaml
Labels: tooling, qa/skip-qa

#1332 Bump default Agent version to 7.55.2
  pkg/defaulting/images.go
Labels: enhancement, mergequeue-status: removed

#1158 Add details regarding watched namespaces for the DatadogMonitor objects
  docs/datadog_monitor.md
Labels: documentation, qa/skip-qa

#1336 [Tooling] Remove some OpenAPI warning and docker build warning
  apis/datadoghq/v1alpha1/datadogmonitor_types.go
  apis/datadoghq/v1alpha1/zz_generated.openapi.go
  check-operator.Dockerfile
  config/crd/bases/v1/datadoghq.com_datadogmonitors.yaml
Labels: tooling, qa/skip-qa
