Repository DataDog/datadog-operator, pull requests merged in 2024-02, with the labels that each got.

#1066 Correct a malformed example command in installation.md
  docs/installation.md
Labels: documentation, qa/skip-qa

#1065 [profiles] Reduce mem usage in pods cleanup
  controllers/datadogagent/controller_reconcile_agent.go
  controllers/datadogagent/controller_reconcile_v2.go
  controllers/datadogagent_controller.go
  main.go
Labels: enhancement, qa/skip-qa

#1070 [profiles] Replace custom node cache with k8s client one
  config/rbac/role.yaml
  controllers/datadogagent/controller.go
  controllers/datadogagent/controller_reconcile_agent.go
  controllers/datadogagent/controller_reconcile_v2.go
  controllers/datadogagent/finalizer.go
  controllers/datadogagent_controller.go
  controllers/datadogagent_controller_v2_profiles_test.go
  controllers/datadogagentprofile_controller.go
  controllers/setup.go
  main.go
  pkg/agentprofile/agent_profile.go
  pkg/agentprofile/agent_profile_test.go
  pkg/kubernetes/nodestore.go
  pkg/kubernetes/nodestore_test.go
Labels: enhancement, qa/skip-qa

#1071 [profiles] Change node labels to use dap ns-name format
  controllers/datadogagent/controller_reconcile_agent.go
  controllers/datadogagent/controller_test.go
Labels: enhancement, qa/skip-qa

#1073 [cherry-pick][defaulting/images] Update agents to 7.50.3 (#1038)
  pkg/defaulting/images.go
Labels: enhancement

#1075 chore(golangci-lint): bump from v1.51.0 to v1.56.0
  .golangci.toml
  Makefile
Labels: tooling, qa/skip-qa

#1067 Fix hostport custom port settings
  apis/datadoghq/v2alpha1/test/builder.go
  controllers/datadogagent/feature/apm/feature.go
  controllers/datadogagent/feature/apm/feature_test.go
  controllers/datadogagent/feature/dogstatsd/feature.go
  controllers/datadogagent/feature/dogstatsd/feature_test.go
  controllers/datadogagent/feature/dogstatsd/feature_v1alpha1_test.go
Labels: bug

#1080 Clean up cos_containerd provider name (#1077)
  controllers/datadogagent/controller_reconcile_agent_test.go
  controllers/datadogagent/feature/oomkill/feature.go
  controllers/datadogagent/feature/tcpqueuelength/feature.go
  pkg/kubernetes/provider.go
  pkg/kubernetes/provider_test.go
Labels: refactoring

#1081 [cherry-pick] Fix hostport custom port settings (#1067)
  apis/datadoghq/v2alpha1/test/builder.go
  controllers/datadogagent/feature/apm/feature.go
  controllers/datadogagent/feature/apm/feature_test.go
  controllers/datadogagent/feature/dogstatsd/feature.go
  controllers/datadogagent/feature/dogstatsd/feature_test.go
  controllers/datadogagent/feature/dogstatsd/feature_v1alpha1_test.go
Labels: bug

#1082 [cherry-pick] add option in DatadogAgent CRD to disable nonResourceRules (#1074)
  apis/datadoghq/v2alpha1/datadogagent_types.go
  apis/datadoghq/v2alpha1/zz_generated.deepcopy.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  controllers/datadogagent/clusteragent.go
  controllers/datadogagent/component/agent/rbac.go
  controllers/datadogagent/component/clusterchecksrunner/default.go
  controllers/datadogagent/feature/enabledefault/feature.go
  docs/configuration.v2alpha1.md
Labels: enhancement

#1036 Add gitlab post-release job to create community operator PRs
  .gitlab-ci.yml
  Makefile
  hack/publish-community-bundles.sh
Labels: tooling, qa/skip-qa

#1087 Add gitlab post-release job to create community operator PRs (#1036)
  .gitlab-ci.yml
  Makefile
  hack/publish-community-bundles.sh
Labels: tooling, qa/skip-qa

#1084 feat(dogstatsd): activate Origin Detection with UDP
  apis/datadoghq/common/const.go
  apis/datadoghq/common/envvar.go
  controllers/datadogagent/agent_test.go
  controllers/datadogagent/feature/dogstatsd/feature.go
  controllers/datadogagent/feature/dogstatsd/feature_test.go
  controllers/datadogagent/feature/dogstatsd/feature_v1alpha1_test.go
  controllers/datadogagent/utils.go
Labels: enhancement

#1090 [defaulting/images] Update agents to 7.51.0
  pkg/defaulting/images.go
Labels: enhancement

#1095 update bundle script and base bundle (#1094)
  bundle/manifests/datadoghq.com_datadogagents.yaml
  hack/patch-bundle.sh
  hack/redhat-bundle.sh
Labels: bug, enhancement, qa/skip-qa

#1072 Add SLI metrics URL to clc rbac
  controllers/datadogagent/component/clusterchecksrunner/default.go
Labels: enhancement

#1096 fix publish-community-bundles script
  hack/publish-community-bundles.sh
Labels: bug, tooling, qa/skip-qa

#1097 fix publish-community-bundles script (#1096)
  hack/publish-community-bundles.sh
Labels: tooling, qa/skip-qa

#1069 [CECO-941][docs] Add introspection docs
  docs/introspection.md
Labels: documentation, qa/skip-qa

#1086 [introspection][profiles][CECO-851] Refactor introspection
  controllers/datadogagent/controller.go
  controllers/datadogagent/controller_reconcile_agent.go
  controllers/datadogagent/controller_reconcile_agent_test.go
  controllers/datadogagent/controller_reconcile_v2.go
  controllers/datadogagent/controller_v2_test.go
  controllers/datadogagent_controller.go
  controllers/setup.go
  pkg/agentprofile/agent_profile.go
  pkg/kubernetes/provider.go
  pkg/kubernetes/provider_test.go
Labels: enhancement

#1098 [profiles][CECO-925] Add flag to enable DAP
  controllers/datadogagent/controller.go
  controllers/datadogagent/controller_reconcile_agent.go
  controllers/datadogagent/controller_reconcile_v2.go
  controllers/datadogagent_controller.go
  controllers/setup.go
  controllers/suite_v2_test.go
  main.go
  pkg/agentprofile/agent_profile.go
  pkg/agentprofile/agent_profile_test.go
Labels: enhancement

#1076 feat: add OnMissingData to monitor options
  apis/datadoghq/v1alpha1/datadogmonitor_types.go
  apis/datadoghq/v1alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogmonitors.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogmonitors.yaml
  controllers/datadogmonitor/monitor.go
  controllers/datadogmonitor/monitor_test.go
Labels: enhancement, feature/datadog-monitor

#1063 [CECO-180] Add FIPS support
  apis/datadoghq/common/const.go
  apis/datadoghq/common/envvar.go
  apis/datadoghq/common/v1/types.go
  apis/datadoghq/v2alpha1/datadogagent_default.go
  apis/datadoghq/v2alpha1/datadogagent_default_test.go
  apis/datadoghq/v2alpha1/datadogagent_types.go
  apis/datadoghq/v2alpha1/test/builder.go
  apis/datadoghq/v2alpha1/zz_generated.deepcopy.go
  apis/datadoghq/v2alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  controllers/datadogagent/controller_reconcile_agent.go
  controllers/datadogagent/controller_reconcile_dca.go
  controllers/datadogagent/controller_v2_test.go
  controllers/datadogagent/merger/envvars.go
  controllers/datadogagent/merger/envvars_test.go
  controllers/datadogagent/merger/utils.go
  controllers/datadogagent/merger/volume_mount.go
  controllers/datadogagent/merger/volume_mount_test.go
  controllers/datadogagent/override/fips.go
  controllers/datadogagent/override/fips_test.go
  controllers/datadogagent/override/global.go
  docs/configuration.v2alpha1.md
  pkg/defaulting/images.go
Labels: enhancement

#1031 Adding support for Single Step Instrumentation in the operator
  apis/datadoghq/common/envvar.go
  apis/datadoghq/v2alpha1/datadogagent_default.go
  apis/datadoghq/v2alpha1/datadogagent_default_test.go
  apis/datadoghq/v2alpha1/datadogagent_types.go
  apis/datadoghq/v2alpha1/test/builder.go
  apis/datadoghq/v2alpha1/zz_generated.deepcopy.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  controllers/datadogagent/feature/apm/feature.go
  controllers/datadogagent/feature/apm/feature_test.go
  docs/configuration.v2alpha1.md
Labels: enhancement

#1088 Fix publish-community-bundles script
  .gitlab-ci.yml
  hack/publish-community-bundles.sh
Labels: bug, tooling, qa/skip-qa

#1103 [gitlab] replace docker tag calls for k8s runners
  .gitlab-ci.yml
Labels: tooling, qa/skip-qa

#1104 [gitlab] load bundle image
  .gitlab-ci.yml
  Makefile
Labels: tooling, qa/skip-qa

#1105 [gitlab] fix make task
  .gitlab-ci.yml
  Makefile
Labels: bug, tooling, qa/skip-qa
