Repository DataDog/datadog-operator, pull requests merged in 2024-12, with the labels that each got.

#1542 (backport) [tooling] use generated GITHUB_TOKEN for authentication (#1541)
  .github/workflows/release.yaml
Labels: tooling, qa/skip-qa

#1543 (backport) update default fips-proxy image version to 1.1.6
  pkg/defaulting/images.go
Labels: enhancement, mergequeue-status: in_progress

#1513 Add `Local` as valid type for autoscaler source
  api/datadoghq/v1alpha1/datadogpodautoscaler_types.go
Labels: enhancement, qa/skip-qa

#1546 Support runtimeClassName override (including in DAP)
  api/datadoghq/v1alpha1/datadogagentprofile_types.go
  api/datadoghq/v1alpha1/zz_generated.deepcopy.go
  api/datadoghq/v2alpha1/datadogagent_types.go
  api/datadoghq/v2alpha1/zz_generated.deepcopy.go
  config/crd/bases/v1/datadoghq.com_datadogagentprofiles.yaml
  config/crd/bases/v1/datadoghq.com_datadogagentprofiles_v1alpha1.json
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1/datadoghq.com_datadogagents_v2alpha1.json
  docs/configuration.v2alpha1.md
  docs/datadog_agent_profiles.md
  internal/controller/datadogagent/override/podtemplatespec.go
  internal/controller/datadogagent/override/podtemplatespec_test.go
  pkg/agentprofile/agent_profile.go
  pkg/agentprofile/agent_profile_test.go
Labels: enhancement, mergequeue-status: in_progress

#1557 move metrics forwarder conditions and incorporate error type
  api/datadoghq/v1alpha1/datadogagent_types.go
  api/datadoghq/v2alpha1/condition.go
  pkg/controller/utils/datadog/metrics_forwarder.go
Labels: bug, refactoring

#1527 Fix publish-community-prs job
  hack/publish-community-bundles.sh
Labels: bug, tooling

#1555 [documentation] Secrets management in Operator 1.11+
  docs/secret_management.md
Labels: documentation, qa/skip-qa

#1564 fix bundle name for rh-certified PRs (#1527)
  hack/publish-community-bundles.sh
Labels: bug, tooling

#1567 Update the default (cluster-)Agent version to 7.60.0
  pkg/defaulting/images.go
Labels: enhancement

#1566 [documentation] Secrets management in Operator 1.11+ (#1555)
  docs/secret_management.md
Labels: documentation, qa/skip-qa

#1568 [backport] Update Agent and cluster Agent to `7.60.0`
  pkg/defaulting/images.go
Labels: enhancement

#1569 release v1.11.0-rc.3
  bundle-community-operators/manifests/datadog-operator.clusterserviceversion.yaml
  bundle/manifests/datadog-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
Labels: dependencies, qa/skip-qa

#1538 [datadog-monitor] Init fake client store with test objects instead of using create
  internal/controller/datadogmonitor/finalizer_test.go
Labels: refactoring, fixed, qa/skip-qa

#1579 release v1.11.0
  bundle-community-operators/manifests/datadog-operator.clusterserviceversion.yaml
  bundle/manifests/datadog-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
Labels: dependencies, qa/skip-qa

#1578 Change Operator Check base image to ubi9
  check-operator.Dockerfile
Labels: tooling, qa/skip-qa

#1575 [CONTP-519] Support k8s admin events in operator
  api/datadoghq/v2alpha1/datadogagent_default.go
  api/datadoghq/v2alpha1/datadogagent_default_test.go
  api/datadoghq/v2alpha1/datadogagent_types.go
  api/datadoghq/v2alpha1/zz_generated.deepcopy.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1/datadoghq.com_datadogagents_v2alpha1.json
  docs/configuration.v2alpha1.md
  internal/controller/datadogagent/feature/admissioncontroller/envvar.go
  internal/controller/datadogagent/feature/admissioncontroller/feature.go
Labels: enhancement

#1580 Revert "[cleanup] remove unused v1beta1 version of PDB (#1468)"
  internal/controller/datadogagent/component/clusteragent/default_test.go
  internal/controller/datadogagent/component/clusteragent/utils.go
  internal/controller/datadogagent/component/clusterchecksrunner/default.go
  internal/controller/datadogagent/component/clusterchecksrunner/default_test.go
  internal/controller/datadogagent/override/dependencies.go
  internal/controller/datadogagent/testutils/client_utils.go
  internal/controller/datadogagent_controller.go
  pkg/equality/equality.go
  pkg/kubernetes/objects.go
  pkg/kubernetes/objectslist.go
  pkg/kubernetes/platforminfo.go
  pkg/kubernetes/platforminfo_test.go
Labels: bug

#1582 [backport] PDB v1beta1 support fix
  internal/controller/datadogagent/component/clusteragent/default_test.go
  internal/controller/datadogagent/component/clusteragent/utils.go
  internal/controller/datadogagent/component/clusterchecksrunner/default.go
  internal/controller/datadogagent/component/clusterchecksrunner/default_test.go
  internal/controller/datadogagent/override/dependencies.go
  internal/controller/datadogagent/testutils/client_utils.go
  internal/controller/datadogagent_controller.go
  pkg/equality/equality.go
  pkg/kubernetes/objects.go
  pkg/kubernetes/objectslist.go
  pkg/kubernetes/platforminfo.go
  pkg/kubernetes/platforminfo_test.go
Labels: bug

#1583 release v1.11.1-rc.1
  bundle-community-operators/manifests/datadog-operator.clusterserviceversion.yaml
  bundle/manifests/datadog-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
Labels: dependencies, qa/skip-qa

#1584 Regenerate stale datadogpodautoscalers CRD
  config/crd/bases/v1/datadoghq.com_datadogpodautoscalers_v1alpha1.json
Labels: bug, qa/skip-qa

#1585 [chore] Release v1.11.1
  bundle-community-operators/manifests/datadog-operator.clusterserviceversion.yaml
  bundle/manifests/datadog-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
Labels: dependencies, qa/skip-qa

#1559 OTel Agent Feature Support
  api/datadoghq/v2alpha1/const.go
  api/datadoghq/v2alpha1/datadogagent_default.go
  api/datadoghq/v2alpha1/datadogagent_default_test.go
  api/datadoghq/v2alpha1/datadogagent_types.go
  api/datadoghq/v2alpha1/envvar.go
  api/datadoghq/v2alpha1/test/builder.go
  api/datadoghq/v2alpha1/zz_generated.deepcopy.go
  api/datadoghq/v2alpha1/zz_generated.openapi.go
  cmd/main.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1/datadoghq.com_datadogagents_v2alpha1.json
  docs/configuration.v2alpha1.md
  examples/datadogagent/datadog-agent-with-otel-agent-annotations.yaml
  examples/datadogagent/datadog-agent-with-otel-agent-configmap.yaml
  examples/datadogagent/datadog-agent-with-otel-agent.yaml
  internal/controller/datadogagent/component/agent/default.go
  internal/controller/datadogagent/controller.go
  internal/controller/datadogagent/feature/enabledefault/feature.go
  internal/controller/datadogagent/feature/ids.go
  internal/controller/datadogagent/feature/otelcollector/configmap_test.go
  internal/controller/datadogagent/feature/otelcollector/defaultconfig/defaultconfig.go
  internal/controller/datadogagent/feature/otelcollector/feature.go
  internal/controller/datadogagent/feature/otelcollector/feature_test.go
  internal/controller/datadogagent/feature/test/factory_test.go
  internal/controller/datadogagent/feature/types.go
  internal/controller/setup.go
  pkg/defaulting/images.go
Labels: enhancement

#1551 Remove kube-rbac-proxy image
  LICENSE-3rdparty.csv
  cmd/main.go
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/default/manager_metrics_patch.yaml
  config/default/metrics_service.yaml
  config/manager/manager.yaml
  config/rbac/auth_proxy_client_clusterrole.yaml
  config/rbac/kustomization.yaml
  config/rbac/metrics_auth_role.yaml
  config/rbac/metrics_auth_role_binding.yaml
  config/rbac/metrics_reader_role.yaml
  config/test-v1/kustomization.yaml
  config/test-v1/manager_auth_proxy_patch.yaml
  go.mod
  go.sum
Labels: enhancement

#1591 feat(admission): add delete RBAC for datadog-webhook
  internal/controller/datadogagent/feature/admissioncontroller/rbac.go
Labels: enhancement, mergequeue-status: in_progress
