Repository DataDog/datadog-operator, pull requests merged in 2024-09, with the labels that each got.

#1388 [default/images] Bump default agent/cluster agent version to `7.56.2`
  pkg/defaulting/images.go
Labels: enhancement, mergequeue-status: in_progress

#1377 feat(admission controller): add ValidatingWebhookConfigurations RBAC
  bundle/manifests/datadog-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/datadogagent/controller_test.go
  controllers/datadogagent/feature/admissioncontroller/rbac.go
  controllers/datadogagent_controller.go
  pkg/equality/equality.go
  pkg/kubernetes/const.go
  pkg/kubernetes/objects.go
  pkg/kubernetes/objectslist.go
Labels: enhancement

#1365 [profiles] DAP slow rollout on DS creation
  apis/datadoghq/common/envvar.go
  apis/datadoghq/v1alpha1/datadogagentprofile_types.go
  apis/datadoghq/v1alpha1/zz_generated.deepcopy.go
  apis/datadoghq/v1alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagentprofiles.yaml
  controllers/datadogagent/controller_reconcile_agent.go
  controllers/datadogagent/controller_reconcile_v2.go
  controllers/datadogagent/controller_reconcile_v2_common.go
  controllers/datadogagent/controller_reconcile_v2_common_test.go
  controllers/datadogagent/controller_reconcile_v2_test.go
  pkg/agentprofile/agent_profile.go
  pkg/agentprofile/agent_profile_test.go
  pkg/agentprofile/status.go
  pkg/agentprofile/status_test.go
Labels: enhancement

#1352 Adding Dashboard CRD + Controller
  PROJECT
  apis/datadoghq/v1alpha1/datadogdashboard_types.go
  apis/datadoghq/v1alpha1/datadogdashboard_validation.go
  apis/datadoghq/v1alpha1/datadogdashboard_validation_test.go
  apis/datadoghq/v1alpha1/zz_generated.deepcopy.go
  apis/datadoghq/v1alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogdashboards.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_datadoghq_datadogdashboards.yaml
  config/crd/patches/webhook_in_datadoghq_datadogdashboards.yaml
  config/rbac/datadoghq_datadogdashboard_editor_role.yaml
  config/rbac/datadoghq_datadogdashboard_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/datadoghq_v1alpha1_datadogdashboard.yaml
  config/samples/kustomization.yaml
  controllers/datadogdashboard/controller.go
  controllers/datadogdashboard/controller_test.go
  controllers/datadogdashboard/dashboard.go
  controllers/datadogdashboard/dashboard_test.go
  controllers/datadogdashboard/finalizer.go
  controllers/datadogdashboard/finalizer_test.go
  controllers/datadogdashboard/widgets.json
  controllers/datadogdashboard_controller.go
  controllers/setup.go
  examples/datadogdashboard/simple-dashboard.yaml
  go.mod
  go.sum
  go.work.sum
  main.go
  pkg/datadogclient/client.go
Labels: enhancement

#1392 [docs] add note about upgrading to 1.8.0 in openshift
  docs/assets/openshift_1.8.0_crd_error.png
  docs/assets/openshift_1.8.0_upgrade.png
  docs/install-openshift.md
Labels: documentation, qa/skip-qa, mergequeue-status: in_progress

#1393 Remove community operator bundles
  bundle-community-operators/manifests/datadog-operator-webhook-service_v1_service.yaml
  bundle-community-operators/manifests/datadog-operator.clusterserviceversion.yaml
  bundle-community-operators/manifests/datadoghq.com_datadogagentprofiles.yaml
  bundle-community-operators/manifests/datadoghq.com_datadogagents.yaml
  bundle-community-operators/manifests/datadoghq.com_datadogdashboards.yaml
  bundle-community-operators/manifests/datadoghq.com_datadogmetrics.yaml
  bundle-community-operators/manifests/datadoghq.com_datadogmonitors.yaml
  bundle-community-operators/manifests/datadoghq.com_datadogpodautoscalers.yaml
  bundle-community-operators/manifests/datadoghq.com_datadogslos.yaml
  bundle-community-operators/metadata/annotations.yaml
  bundle-community-operators/tests/scorecard/config.yaml
Labels: tooling, qa/skip-qa

#1399 [cleanup] reorganize constant files
  api/datadoghq/common/const.go
  api/datadoghq/v2alpha1/const.go
  internal/controller/datadogagent/common/const.go
  internal/controller/datadogagent/const.go
  internal/controller/datadogagent/controller_reconcile_agent.go
  internal/controller/datadogagent/controller_reconcile_ccr.go
  internal/controller/datadogagent/controller_reconcile_dca.go
  internal/controller/datadogagent/controller_reconcile_v2_common.go
  internal/controller/datadogagent/finalizer_test.go
  internal/controller/datadogagent/override/const.go
  internal/controller/datadogagent/override/dependencies.go
  internal/controller/datadogagent/override/podtemplatespec.go
  pkg/kubernetes/const.go
  pkg/kubernetes/rbac/const.go
Labels: refactoring

#1403 Remove "v" in image tag
  Makefile
Labels: tooling, qa/skip-qa

#1405 Bump Go to 1.22.7; CVE-2024-34156, VULN-8399 (#1402)
  .gitlab-ci.yml
  Dockerfile
  check-operator.Dockerfile
  go.mod
  go.work
  test/e2e/go.mod
Labels: tooling, qa/skip-qa

#1410 [Dashboard] Replace DashboardLastForceSyncTime with LastForceSyncTime
  api/datadoghq/v1alpha1/datadogdashboard_types.go
  api/datadoghq/v1alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogdashboards.yaml
Labels: enhancement, component/controller, fixed, qa/skip-qa, mergequeue-status: in_progress

#1411 [Dashboard] Replace DashboardLastForceSyncTime with LastForceSyncTime
  api/datadoghq/v1alpha1/datadogdashboard_types.go
  api/datadoghq/v1alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogdashboards.yaml
Labels: enhancement, component/controller, fixed, qa/skip-qa, mergequeue-status: in_progress

#1398 [Dashboard CRD] Use fully-qualified domain name finalizer
  internal/controller/datadogdashboard/controller_test.go
  internal/controller/datadogdashboard/finalizer.go
Labels: enhancement, component/controller, qa/skip-qa, mergequeue-status: error

#1400 rename dependencies pkg to store
  internal/controller/datadogagent/controller_reconcile_v2.go
  internal/controller/datadogagent/feature/apm/feature_test.go
  internal/controller/datadogagent/feature/autoscaling/feature_test.go
  internal/controller/datadogagent/feature/eventcollection/feature_test.go
  internal/controller/datadogagent/feature/externalmetrics/feature_test.go
  internal/controller/datadogagent/feature/helmcheck/feature_test.go
  internal/controller/datadogagent/feature/test/testsuite.go
  internal/controller/datadogagent/feature/types.go
  internal/controller/datadogagent/finalizer.go
  internal/controller/datadogagent/merger/apiservice.go
  internal/controller/datadogagent/merger/cilium.go
  internal/controller/datadogagent/merger/cilium_test.go
  internal/controller/datadogagent/merger/configmap.go
  internal/controller/datadogagent/merger/configmap_test.go
  internal/controller/datadogagent/merger/network_policy.go
  internal/controller/datadogagent/merger/network_policy_test.go
  internal/controller/datadogagent/merger/pod_security.go
  internal/controller/datadogagent/merger/rbac.go
  internal/controller/datadogagent/merger/rbac_test.go
  internal/controller/datadogagent/merger/secret.go
  internal/controller/datadogagent/merger/secret_test.go
  internal/controller/datadogagent/merger/service.go
  internal/controller/datadogagent/merger/service_test.go
  internal/controller/datadogagent/override/dependencies_test.go
  internal/controller/datadogagent/override/fips_test.go
  internal/controller/datadogagent/override/global_test.go
  internal/controller/datadogagent/store/doc.go
  internal/controller/datadogagent/store/store.go
  internal/controller/datadogagent/store/store_test.go
Labels: refactoring

#1413 [profiles] Update UpdateStrategy description
  api/datadoghq/v1alpha1/datadogagentprofile_types.go
  config/crd/bases/v1/datadoghq.com_datadogagentprofiles.yaml
Labels: enhancement, qa/skip-qa

#1415 Remove "v" in image tag (#1403)
  Makefile
Labels: tooling, qa/skip-qa

#1414 [profiles] Fall back to EDS options if needed
  api/utils/utils.go
  api/utils/utils_test.go
  internal/controller/datadogagent/component/agent/new.go
  internal/controller/datadogagent/controller_reconcile_v2.go
  pkg/agentprofile/agent_profile.go
  pkg/agentprofile/agent_profile_test.go
Labels: enhancement

#1416 [profiles] Rename slow start to create strategy
  api/datadoghq/common/envvar.go
  api/datadoghq/v1alpha1/datadogagentprofile_types.go
  api/datadoghq/v1alpha1/zz_generated.deepcopy.go
  api/datadoghq/v1alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagentprofiles.yaml
  internal/controller/datadogagent/controller_reconcile_v2_common.go
  internal/controller/datadogagent/controller_reconcile_v2_common_test.go
  pkg/agentprofile/agent_profile.go
  pkg/agentprofile/agent_profile_test.go
  pkg/agentprofile/status.go
  pkg/agentprofile/status_test.go
Labels: enhancement

#1418 [profiles] Update UpdateStrategy description (#1413)
  api/datadoghq/v1alpha1/datadogagentprofile_types.go
  config/crd/bases/v1/datadoghq.com_datadogagentprofiles.yaml
Labels: enhancement, qa/skip-qa

#1406 Add global environment variable config
  api/datadoghq/v2alpha1/datadogagent_types.go
  api/datadoghq/v2alpha1/test/builder.go
  api/datadoghq/v2alpha1/zz_generated.deepcopy.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  docs/configuration.v2alpha1.md
  internal/controller/datadogagent/override/global.go
  internal/controller/datadogagent/override/global_test.go
  internal/controller/testutils/agent.go
Labels: enhancement

#1419 Fall back to eds options if needed (#1414)
  api/utils/utils.go
  api/utils/utils_test.go
  internal/controller/datadogagent/component/agent/new.go
  internal/controller/datadogagent/controller_reconcile_v2.go
  pkg/agentprofile/agent_profile.go
  pkg/agentprofile/agent_profile_test.go
Labels: enhancement, qa/skip-qa

#1420 Change slow start to create strategy (#1416)
  api/datadoghq/common/envvar.go
  api/datadoghq/v1alpha1/datadogagentprofile_types.go
  api/datadoghq/v1alpha1/zz_generated.deepcopy.go
  api/datadoghq/v1alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagentprofiles.yaml
  internal/controller/datadogagent/controller_reconcile_v2_common.go
  internal/controller/datadogagent/controller_reconcile_v2_common_test.go
  pkg/agentprofile/agent_profile.go
  pkg/agentprofile/agent_profile_test.go
  pkg/agentprofile/status.go
  pkg/agentprofile/status_test.go
Labels: enhancement, qa/skip-qa

#1423 Remove capitalization for profile field
  api/datadoghq/v1alpha1/datadogagentprofile_types.go
  api/datadoghq/v1alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagentprofiles.yaml
Labels: bug

#1424 [profiles] Update DatadogAgentProfile docs for 1.9.0
  docs/datadog_agent_profiles.md
Labels: documentation, qa/skip-qa

#1426 [cleanup] shuffle constants in pkg/config
  api/datadoghq/common/envvar.go
  pkg/config/config.go
  pkg/config/creds.go
  pkg/datadogclient/client.go
Labels: refactoring

#1430 Update Agent/cluster Agent to 7.57.2
  pkg/defaulting/images.go
Labels: enhancement

#1434 [profiles] Don't update status for default profile
  internal/controller/datadogagent/controller_reconcile_v2.go
Labels: bug

#1433 Remove capitalization for profile field (#1423)
  api/datadoghq/v1alpha1/datadogagentprofile_types.go
  api/datadoghq/v1alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagentprofiles.yaml
Labels: bug, qa/skip-qa

#1431 Update Agent/cluster Agent to `7.57.2`
  pkg/defaulting/images.go
Labels: enhancement

#1435 Don't update status for default profile (#1434)
  internal/controller/datadogagent/controller_reconcile_v2.go
Labels: bug, qa/skip-qa

#1432 [cleanup] move some common constants to v2alpha1
  api/datadoghq/common/const.go
  api/datadoghq/v2alpha1/const.go
  api/datadoghq/v2alpha1/datadogagent_default.go
  api/datadoghq/v2alpha1/datadogagent_default_test.go
  api/datadoghq/v2alpha1/secret.go
  api/datadoghq/v2alpha1/utils.go
  api/datadoghq/v2alpha1/utils_test.go
  internal/controller/datadogagent/common/utils.go
  internal/controller/datadogagent/component/agent/default.go
  internal/controller/datadogagent/component/clusteragent/default.go
  internal/controller/datadogagent/component/clusteragent/default_test.go
  internal/controller/datadogagent/component/clusteragent/utils.go
  internal/controller/datadogagent/component/clusterchecksrunner/default.go
  internal/controller/datadogagent/component/objects/network.go
  internal/controller/datadogagent/controller_reconcile_agent.go
  internal/controller/datadogagent/controller_reconcile_agent_test.go
  internal/controller/datadogagent/controller_reconcile_v2.go
  internal/controller/datadogagent/feature/admissioncontroller/feature.go
  internal/controller/datadogagent/feature/clusterchecks/feature.go
  internal/controller/datadogagent/feature/clusterchecks/feature_test.go
  internal/controller/datadogagent/feature/cspm/feature.go
  internal/controller/datadogagent/feature/cws/feature.go
  internal/controller/datadogagent/feature/dogstatsd/feature.go
  internal/controller/datadogagent/feature/dogstatsd/feature_test.go
  internal/controller/datadogagent/feature/ebpfcheck/feature.go
  internal/controller/datadogagent/feature/ebpfcheck/feature_test.go
  internal/controller/datadogagent/feature/enabledefault/feature.go
  internal/controller/datadogagent/feature/enabledefault/rbac.go
  internal/controller/datadogagent/feature/eventcollection/feature.go
  internal/controller/datadogagent/feature/externalmetrics/feature.go
  internal/controller/datadogagent/feature/externalmetrics/feature_test.go
  internal/controller/datadogagent/feature/helmcheck/configmap_test.go
  internal/controller/datadogagent/feature/helmcheck/feature.go
  internal/controller/datadogagent/feature/helmcheck/feature_test.go
  internal/controller/datadogagent/feature/kubernetesstatecore/configmap_test.go
  internal/controller/datadogagent/feature/kubernetesstatecore/feature.go
  internal/controller/datadogagent/feature/npm/feature.go
  internal/controller/datadogagent/feature/npm/feature_test.go
  internal/controller/datadogagent/feature/oomkill/feature.go
  internal/controller/datadogagent/feature/oomkill/feature_test.go
  internal/controller/datadogagent/feature/orchestratorexplorer/configmap_test.go
  internal/controller/datadogagent/feature/orchestratorexplorer/feature.go
  internal/controller/datadogagent/feature/tcpqueuelength/feature.go
  internal/controller/datadogagent/feature/tcpqueuelength/feature_test.go
  internal/controller/datadogagent/feature/usm/feature.go
  internal/controller/datadogagent/feature/usm/feature_test.go
  internal/controller/datadogagent/override/global.go
  pkg/config/config.go
  pkg/defaulting/images.go
Labels: refactoring

#1437 release v1.9.0-rc.3
  bundle/manifests/datadog-operator.clusterserviceversion.yaml
  bundle/manifests/datadoghq.com_datadogagentprofiles.yaml
  config/manager/kustomization.yaml
Labels: tooling, qa/skip-qa
