Repository DataDog/datadog-operator, pull requests merged in 2024-01, with the labels that each got.

#1028 [CECO-841] Add DAP validation before applying profiles
  controllers/datadogagent/controller_reconcile_v2.go
  pkg/agentprofile/agent_profile.go
  pkg/agentprofile/agent_profile_test.go
Labels: enhancement, qa/skip-qa

#1029 [defaulting/images] Update agents to 7.50.1
  pkg/defaulting/images.go
Labels: enhancement

#921 ContainerProcessStrategy, allow running non-privileged agents in one container
  apis/datadoghq/common/v1/types.go
  apis/datadoghq/v2alpha1/datadogagent_default.go
  apis/datadoghq/v2alpha1/datadogagent_types.go
  apis/datadoghq/v2alpha1/test/builder.go
  apis/datadoghq/v2alpha1/zz_generated.deepcopy.go
  apis/datadoghq/v2alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  controllers/datadogagent/component/agent/default.go
  controllers/datadogagent/controller_reconcile_agent.go
  controllers/datadogagent/controller_reconcile_ccr.go
  controllers/datadogagent/controller_reconcile_dca.go
  controllers/datadogagent/controller_reconcile_v2.go
  controllers/datadogagent/controller_v2_test.go
  controllers/datadogagent/feature/admissioncontroller/feature.go
  controllers/datadogagent/feature/apm/feature.go
  controllers/datadogagent/feature/apm/feature_test.go
  controllers/datadogagent/feature/clusterchecks/feature.go
  controllers/datadogagent/feature/clusterchecks/feature_test.go
  controllers/datadogagent/feature/cspm/feature.go
  controllers/datadogagent/feature/cws/feature.go
  controllers/datadogagent/feature/dogstatsd/feature.go
  controllers/datadogagent/feature/dummy/feature.go
  controllers/datadogagent/feature/ebpfcheck/feature.go
  controllers/datadogagent/feature/enabledefault/feature.go
  controllers/datadogagent/feature/eventcollection/feature.go
  controllers/datadogagent/feature/externalmetrics/feature.go
  controllers/datadogagent/feature/factory.go
  controllers/datadogagent/feature/kubernetesstatecore/feature.go
  controllers/datadogagent/feature/kubernetesstatecore/feature_test.go
  controllers/datadogagent/feature/livecontainer/feature.go
  controllers/datadogagent/feature/livecontainer/feature_test.go
  controllers/datadogagent/feature/liveprocess/feature.go
  controllers/datadogagent/feature/logcollection/feature.go
  controllers/datadogagent/feature/npm/feature.go
  controllers/datadogagent/feature/oomkill/feature.go
  controllers/datadogagent/feature/orchestratorexplorer/feature.go
  controllers/datadogagent/feature/otlp/feature.go
  controllers/datadogagent/feature/otlp/feature_test.go
  controllers/datadogagent/feature/processdiscovery/feature.go
  controllers/datadogagent/feature/prometheusscrape/feature.go
  controllers/datadogagent/feature/remoteconfig/feature.go
  controllers/datadogagent/feature/sbom/feature.go
  controllers/datadogagent/feature/tcpqueuelength/feature.go
  controllers/datadogagent/feature/test/factory_test.go
  controllers/datadogagent/feature/test/testsuite.go
  controllers/datadogagent/feature/types.go
  controllers/datadogagent/feature/usm/feature.go
  controllers/datadogagent/override/global.go
  controllers/datadogagent/override/global_test.go
  docs/configuration.v2alpha1.md
Labels: enhancement

#1033 [defaulting/images] Update agents to 7.50.2
  pkg/defaulting/images.go
Labels: enhancement

#1035 [introspection] Add flag, fix types, override name
  apis/datadoghq/v2alpha1/datadogagent_types.go
  apis/datadoghq/v2alpha1/zz_generated.deepcopy.go
  apis/datadoghq/v2alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  controllers/datadogagent/component/agent/default.go
  controllers/datadogagent/component/agent/new.go
  controllers/datadogagent/component/new.go
  controllers/datadogagent/component/utils.go
  controllers/datadogagent/controller.go
  controllers/datadogagent/controller_reconcile_agent.go
  controllers/datadogagent/controller_reconcile_agent_test.go
  controllers/datadogagent/controller_reconcile_v2.go
  controllers/datadogagent/controller_reconcile_v2_common.go
  controllers/datadogagent_controller_v2_test.go
  controllers/setup.go
  main.go
  pkg/controller/utils/datadog/metrics_forwarder.go
  pkg/kubernetes/provider.go
  pkg/kubernetes/provider_test.go
  pkg/plugin/common/statuswrapper.go
Labels: bug, qa/skip-qa

#1034 [Onboarding telemetry] Set install id, install time and install type env variables
  apis/datadoghq/common/envvar.go
  apis/datadoghq/v1alpha1/test/new.go
  controllers/datadogagent/agent_test.go
  controllers/datadogagent/clusteragent_test.go
  controllers/datadogagent/component/agent/default.go
  controllers/datadogagent/component/clusteragent/default.go
  controllers/datadogagent/component/utils.go
Labels: enhancement

#817 [CECO-570] Add operator introspection
  apis/datadoghq/common/const.go
  apis/datadoghq/v2alpha1/condition.go
  apis/datadoghq/v2alpha1/datadogagent_types.go
  apis/datadoghq/v2alpha1/zz_generated.deepcopy.go
  apis/datadoghq/v2alpha1/zz_generated.openapi.go
  cmd/kubectl-datadog/get/get.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  controllers/datadogagent/component/agent/new.go
  controllers/datadogagent/component/new.go
  controllers/datadogagent/component/utils.go
  controllers/datadogagent/controller.go
  controllers/datadogagent/controller_reconcile_agent.go
  controllers/datadogagent/controller_reconcile_agent_test.go
  controllers/datadogagent/controller_reconcile_v2.go
  controllers/datadogagent/controller_reconcile_v2_common.go
  controllers/datadogagent/feature/admissioncontroller/feature.go
  controllers/datadogagent/feature/apm/feature.go
  controllers/datadogagent/feature/clusterchecks/feature.go
  controllers/datadogagent/feature/cspm/feature.go
  controllers/datadogagent/feature/cws/feature.go
  controllers/datadogagent/feature/dogstatsd/feature.go
  controllers/datadogagent/feature/dummy/feature.go
  controllers/datadogagent/feature/ebpfcheck/feature.go
  controllers/datadogagent/feature/enabledefault/feature.go
  controllers/datadogagent/feature/eventcollection/feature.go
  controllers/datadogagent/feature/externalmetrics/feature.go
  controllers/datadogagent/feature/kubernetesstatecore/feature.go
  controllers/datadogagent/feature/livecontainer/feature.go
  controllers/datadogagent/feature/liveprocess/feature.go
  controllers/datadogagent/feature/logcollection/feature.go
  controllers/datadogagent/feature/npm/feature.go
  controllers/datadogagent/feature/oomkill/feature.go
  controllers/datadogagent/feature/orchestratorexplorer/feature.go
  controllers/datadogagent/feature/otlp/feature.go
  controllers/datadogagent/feature/processdiscovery/feature.go
  controllers/datadogagent/feature/prometheusscrape/feature.go
  controllers/datadogagent/feature/remoteconfig/feature.go
  controllers/datadogagent/feature/sbom/feature.go
  controllers/datadogagent/feature/tcpqueuelength/feature.go
  controllers/datadogagent/feature/test/testsuite.go
  controllers/datadogagent/feature/types.go
  controllers/datadogagent/feature/usm/feature.go
  controllers/datadogagent_controller.go
  controllers/setup.go
  main.go
  pkg/controller/utils/datadog/metrics_forwarder.go
  pkg/controller/utils/datadog/metrics_forwarder_test.go
  pkg/kubernetes/provider.go
  pkg/kubernetes/provider_test.go
Labels: enhancement, component/controller

#1038 [defaulting/images] Update agents to 7.50.3
  pkg/defaulting/images.go
Labels: enhancement

#1032 [profiles] Add support for EDS
  controllers/datadogagent/controller_reconcile_agent.go
  controllers/datadogagent/testutils/client_utils.go
Labels: enhancement, qa/skip-qa

#1039 [gitlab] Add nightly operator and operator_check jobs
  .gitlab-ci.yml
Labels: tooling, qa/skip-qa

#1040 update non-privileged to unprivileged
  apis/datadoghq/common/v1/types.go
  apis/datadoghq/v2alpha1/datadogagent_types.go
  apis/datadoghq/v2alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  docs/configuration.v2alpha1.md
Labels: enhancement

#1041 [cherry-pick] update non-privileged to unprivileged (#1040)
  apis/datadoghq/common/v1/types.go
  apis/datadoghq/v2alpha1/datadogagent_types.go
  apis/datadoghq/v2alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  docs/configuration.v2alpha1.md
Labels: enhancement

#1043 [profiles] Fix Watches call for Profiles
  controllers/datadogagent_controller.go
Labels: enhancement, qa/skip-qa

#1046 [introspection] Change gcp to gke
  controllers/datadogagent/controller_reconcile_agent_test.go
  controllers/datadogagent/feature/oomkill/feature.go
  controllers/datadogagent/feature/tcpqueuelength/feature.go
  pkg/kubernetes/provider.go
  pkg/kubernetes/provider_test.go
Labels: enhancement

#1047 [cherry-pick][introspection] Change gcp to gke
  controllers/datadogagent/controller_reconcile_agent_test.go
  controllers/datadogagent/feature/oomkill/feature.go
  controllers/datadogagent/feature/tcpqueuelength/feature.go
  pkg/kubernetes/provider.go
  pkg/kubernetes/provider_test.go
Labels: enhancement

#1044 Mount host files for proper os detection in SBOMs
  apis/datadoghq/common/const.go
  controllers/datadogagent/feature/sbom/feature.go
  controllers/datadogagent/feature/sbom/feature_test.go
Labels: bug, mergequeue-status: waiting

#1048 [gitlab] auto push nightly image
  .gitlab-ci.yml
Labels: tooling, qa/skip-qa

#1049 [introspection] Fix override name combining
  apis/datadoghq/v2alpha1/test/builder.go
  controllers/datadogagent/controller_reconcile_agent.go
  controllers/datadogagent/controller_v2_test.go
Labels: bug

#1050 [cherry-pick][introspection] Fix override name combining (#1049)
  apis/datadoghq/v2alpha1/test/builder.go
  controllers/datadogagent/controller_reconcile_agent.go
  controllers/datadogagent/controller_v2_test.go
Labels: bug

#1051 [cherry-pick][override/podtemplatespec] Merge affinities (#1004)
  controllers/datadogagent/override/podtemplatespec.go
  controllers/datadogagent/override/podtemplatespec_test.go
Labels: enhancement

#1052 [override/podtemplatespec] Merge affinities (#1004)
  controllers/datadogagent/override/podtemplatespec.go
  controllers/datadogagent/override/podtemplatespec_test.go
Labels: enhancement

#1053 [backport] Mount host files for proper os detection in SBOMs
  apis/datadoghq/common/const.go
  controllers/datadogagent/feature/sbom/feature.go
  controllers/datadogagent/feature/sbom/feature_test.go
Labels: bug

#1054 [override/container] Fix container resources override with 0
  controllers/datadogagent/override/container.go
  controllers/datadogagent/override/container_test.go
Labels: enhancement, qa/skip-qa

#1056 [gitlab] update runners for build jobs
  .gitlab-ci.yml
  Makefile
Labels: tooling, qa/skip-qa

#1057 [gitlab] add missing parameter in gitlab jobs
  Makefile
Labels: bug, tooling, qa/skip-qa

#1061 [cherry-pick] update monocontainer config (#1059)
  apis/datadoghq/common/v1/types.go
  apis/datadoghq/v2alpha1/datadogagent_default.go
  apis/datadoghq/v2alpha1/datadogagent_types.go
  apis/datadoghq/v2alpha1/test/builder.go
  apis/datadoghq/v2alpha1/zz_generated.deepcopy.go
  apis/datadoghq/v2alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  controllers/datadogagent/component/agent/default.go
  controllers/datadogagent/controller_reconcile_agent.go
  controllers/datadogagent/controller_v2_test.go
  controllers/datadogagent/feature/admissioncontroller/feature.go
  controllers/datadogagent/feature/apm/feature.go
  controllers/datadogagent/feature/apm/feature_test.go
  controllers/datadogagent/feature/clusterchecks/feature.go
  controllers/datadogagent/feature/clusterchecks/feature_test.go
  controllers/datadogagent/feature/cspm/feature.go
  controllers/datadogagent/feature/cws/feature.go
  controllers/datadogagent/feature/dogstatsd/feature.go
  controllers/datadogagent/feature/dummy/feature.go
  controllers/datadogagent/feature/ebpfcheck/feature.go
  controllers/datadogagent/feature/enabledefault/feature.go
  controllers/datadogagent/feature/eventcollection/feature.go
  controllers/datadogagent/feature/externalmetrics/feature.go
  controllers/datadogagent/feature/factory.go
  controllers/datadogagent/feature/kubernetesstatecore/feature.go
  controllers/datadogagent/feature/kubernetesstatecore/feature_test.go
  controllers/datadogagent/feature/livecontainer/feature.go
  controllers/datadogagent/feature/livecontainer/feature_test.go
  controllers/datadogagent/feature/liveprocess/feature.go
  controllers/datadogagent/feature/logcollection/feature.go
  controllers/datadogagent/feature/npm/feature.go
  controllers/datadogagent/feature/oomkill/feature.go
  controllers/datadogagent/feature/orchestratorexplorer/feature.go
  controllers/datadogagent/feature/otlp/feature.go
  controllers/datadogagent/feature/otlp/feature_test.go
  controllers/datadogagent/feature/processdiscovery/feature.go
  controllers/datadogagent/feature/prometheusscrape/feature.go
  controllers/datadogagent/feature/remoteconfig/feature.go
  controllers/datadogagent/feature/sbom/feature.go
  controllers/datadogagent/feature/tcpqueuelength/feature.go
  controllers/datadogagent/feature/test/factory_test.go
  controllers/datadogagent/feature/test/testsuite.go
  controllers/datadogagent/feature/types.go
  controllers/datadogagent/feature/usm/feature.go
  controllers/datadogagent/override/global.go
  controllers/datadogagent/override/global_test.go
  docs/configuration.v2alpha1.md
Labels: refactoring
