Repository DataDog/datadog-operator, pull requests merged in 2024-04, with the labels that each got.

#1132 [docs][CECO-729] Add DAP docs
  docs/datadog_agent_profiles.md
Labels: documentation, qa/skip-qa

#1134 Use agent config for service activation
  Makefile
  apis/datadoghq/common/v1/zz_generated.deepcopy.go
  apis/datadoghq/v1alpha1/zz_generated.deepcopy.go
  apis/datadoghq/v2alpha1/datadogagent_types.go
  apis/datadoghq/v2alpha1/zz_generated.deepcopy.go
  config/crd/bases/v1/datadoghq.com_datadogagentprofiles.yaml
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1/datadoghq.com_datadogmetrics.yaml
  config/crd/bases/v1/datadoghq.com_datadogmonitors.yaml
  config/crd/bases/v1/datadoghq.com_datadogslos.yaml
  config/manager/kustomization.yaml
  controllers/datadogagent/controller.go
  controllers/datadogagent/controller_reconcile_v2.go
  docs/configuration.v1alpha1.md
  docs/configuration.v2alpha1.md
  go.mod
  go.sum
  main.go
  pkg/remoteconfig/updater.go
Labels: enhancement, dependencies, qa/skip-qa, mergequeue-status: rejected

#1131 [PROCS-3710] Add ability to run Processes features on Core Agent
  apis/datadoghq/common/envvar.go
  apis/datadoghq/v2alpha1/test/builder.go
  controllers/datadogagent/controller.go
  controllers/datadogagent/feature/livecontainer/feature.go
  controllers/datadogagent/feature/livecontainer/feature_test.go
  controllers/datadogagent/feature/liveprocess/feature.go
  controllers/datadogagent/feature/liveprocess/feature_test.go
  controllers/datadogagent/feature/liveprocess/feature_v1alpha1_test.go
  controllers/datadogagent/feature/orchestratorexplorer/feature.go
  controllers/datadogagent/feature/processdiscovery/feature.go
  controllers/datadogagent/feature/processdiscovery/feature_test.go
  controllers/datadogagent/feature/test/testsuite.go
  controllers/datadogagent/feature/types.go
  controllers/datadogagent/feature/utils/utils.go
  controllers/setup.go
  main.go
Labels: enhancement

#1139 Update agents to 7.52.1
  pkg/defaulting/images.go
Labels: enhancement

#1140 Add datadogslo sample
  config/samples/datadoghq_v1alpha1_datadogslo.yaml
  config/samples/kustomization.yaml
Labels: tooling, qa/skip-qa

#1138 [profiles][CECO-1085] Add priority class name to dap
  apis/datadoghq/v1alpha1/datadogagentprofile_types.go
  apis/datadoghq/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/v1/datadoghq.com_datadogagentprofiles.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagentprofiles.yaml
  controllers/datadogagent/controller_reconcile_agent.go
  pkg/agentprofile/agent_profile.go
  pkg/agentprofile/agent_profile_test.go
Labels: enhancement

#1142 [remote config] move initialization to be independent of agent reconciler
  apis/datadoghq/common/v1/zz_generated.deepcopy.go
  apis/datadoghq/v1alpha1/zz_generated.deepcopy.go
  apis/datadoghq/v2alpha1/zz_generated.deepcopy.go
  config/crd/bases/v1/datadoghq.com_datadogagentprofiles.yaml
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1/datadoghq.com_datadogmetrics.yaml
  config/crd/bases/v1/datadoghq.com_datadogmonitors.yaml
  config/crd/bases/v1/datadoghq.com_datadogslos.yaml
  controllers/datadogagent/controller.go
  controllers/datadogagent/controller_reconcile_v2.go
  docs/configuration.v1alpha1.md
  docs/configuration.v2alpha1.md
  go.sum
  main.go
  pkg/remoteconfig/updater.go
Labels: enhancement, qa/skip-qa

#1100 [CECO-848] Combine DS cleanup methods
  controllers/datadogagent/controller_reconcile_agent.go
  controllers/datadogagent/controller_reconcile_agent_test.go
  controllers/datadogagent/controller_reconcile_v2.go
Labels: bug, enhancement

#1152 [profiles][CECO-1085] Add priority class name to dap (#1138)
  apis/datadoghq/v1alpha1/datadogagentprofile_types.go
  apis/datadoghq/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/v1/datadoghq.com_datadogagentprofiles.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagentprofiles.yaml
  controllers/datadogagent/controller_reconcile_agent.go
  pkg/agentprofile/agent_profile.go
  pkg/agentprofile/agent_profile_test.go
Labels: enhancement

#1153 Combine DS cleanup methods (#1100)
  controllers/datadogagent/controller_reconcile_agent.go
  controllers/datadogagent/controller_reconcile_agent_test.go
  controllers/datadogagent/controller_reconcile_v2.go
Labels: enhancement

#1133 Disable provenance in gitlab
  Makefile
Labels: tooling, qa/skip-qa

#1159 [orchestrator check] Update RBACs for storageclass and limitrange collection
  controllers/datadogagent/orchestrator.go
  controllers/datadogagent/testdata/orchestrator_clusterrole.yaml
  controllers/datadogagent_controller.go
Labels: enhancement

#1160 Update agent image versions to 7.53
  pkg/defaulting/images.go
Labels: enhancement

#1161 Update RBACs for storageclass and limitrange collection (#1159)
  controllers/datadogagent/orchestrator.go
  controllers/datadogagent/testdata/orchestrator_clusterrole.yaml
  controllers/datadogagent_controller.go
Labels: enhancement, qa/skip-qa

#1162 Bump agent image versions to 7.53 (#1160)
  pkg/defaulting/images.go
Labels: enhancement, qa/skip-qa
