Repository DataDog/datadog-operator, pull requests merged in 2024-11, with the labels that each got.

#1502 Bump agent and cluster-agent image version to 7.58.2 (#1499)
  pkg/defaulting/images.go
Labels: enhancement

#1460 Update openshift preflight version
  Makefile
Labels: tooling, qa/skip-qa

#1506 pin goreleaser v2.4.1 for release workflow
  .github/workflows/release.yaml
Labels: tooling

#1507 Update openshift preflight version (#1460)
  Makefile
Labels: tooling, qa/skip-qa

#1508 pin goreleaser v2.4.1 for release workflow (#1506)
  .github/workflows/release.yaml
Labels: tooling, qa/skip-qa

#1505 [Orch] Set CRDs in cases of revoking config
  pkg/remoteconfig/orchestrator_k8s_crd.go
Labels: bug

#1510 [Orch] Set CRDs in cases of revoking config (#1505)
  pkg/remoteconfig/orchestrator_k8s_crd.go
Labels: bug

#1503 update generate-docs script
  api/datadoghq/v2alpha1/datadogagent_types.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  docs/configuration.v2alpha1.md
  go.mod
  hack/generate-docs.go
  hack/generate-docs/updated_descriptions.json
Labels: documentation, tooling, qa/skip-qa

#1477 [DatadogAgent][Flare] Additional environment variables and RBAC to permit user manifests retrieval
  internal/controller/datadogagent/feature/enabledefault/const.go
  internal/controller/datadogagent/feature/enabledefault/feature.go
  internal/controller/datadogagent/feature/enabledefault/rbac.go
  internal/controller/datadogagent/feature/enabledefault/utils.go
  internal/controller/datadogagent/feature/enabledefault/utils_test.go
  pkg/kubernetes/rbac/const.go
Labels: enhancement

#1512 release v1.10.0-rc.4
  bundle/manifests/datadog-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
Labels: enhancement

#1517 Update the default `(cluster-)agent` version to `7.59.0`
  pkg/defaulting/images.go
Labels: dependencies

#1520 release v1.10.0
  bundle/manifests/datadog-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
Labels: enhancement

#1516 Configure Github workflow and job level permissions
  .github/workflows/build.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/main.yml
  .github/workflows/pr-linter.yml
  .github/workflows/release.yaml
Labels: tooling, qa/skip-qa

#1454 create Pod Disruption Budget for DCA and CCR deployments
  api/datadoghq/v2alpha1/datadogagent_types.go
  api/datadoghq/v2alpha1/zz_generated.deepcopy.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  docs/configuration.v2alpha1.md
  internal/controller/datadogagent/component/clusteragent/default.go
  internal/controller/datadogagent/component/clusteragent/default_test.go
  internal/controller/datadogagent/component/clusteragent/utils.go
  internal/controller/datadogagent/component/clusterchecksrunner/default.go
  internal/controller/datadogagent/component/clusterchecksrunner/default_test.go
  internal/controller/datadogagent/controller_reconcile_v2.go
  internal/controller/datadogagent/controller_v2_test.go
  internal/controller/datadogagent/feature/enabledefault/feature.go
  internal/controller/datadogagent/override/dependencies.go
  internal/controller/datadogagent/override/dependencies_test.go
Labels: enhancement

#1521 [tooling][gitlab] automatically trigger release candidate workflow
  .gitlab-ci.yml
Labels: tooling, qa/skip-qa

#1449 service discovery: Add operator support
  api/datadoghq/common/envvar.go
  api/datadoghq/v2alpha1/datadogagent_default.go
  api/datadoghq/v2alpha1/datadogagent_default_test.go
  api/datadoghq/v2alpha1/datadogagent_types.go
  api/datadoghq/v2alpha1/zz_generated.deepcopy.go
  api/datadoghq/v2alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  docs/configuration.v2alpha1.md
  examples/datadogagent/datadog-agent-all.yaml
  internal/controller/datadogagent/controller.go
  internal/controller/datadogagent/feature/ids.go
  internal/controller/datadogagent/feature/servicediscovery/feature.go
  internal/controller/datadogagent/feature/servicediscovery/feature_test.go
  internal/controller/datadogagent_controller_test.go
  internal/controller/testutils/agent.go
Labels: enhancement

#1518 enhancement: add experimental support for Agent Data Plane
  api/datadoghq/common/types.go
  api/datadoghq/v2alpha1/const.go
  api/datadoghq/v2alpha1/utils.go
  internal/controller/datadogagent/component/agent/default.go
  internal/controller/datadogagent/feature/dogstatsd/feature.go
  internal/controller/datadogagent/feature/enabledefault/feature.go
  internal/controller/datadogagent/feature/test/factory_test.go
  internal/controller/datadogagent/feature/utils/utils.go
  internal/controller/datadogagent/merger/utils.go
Labels: enhancement, qa/skip-qa

#1524 small doc fix
  docs/how-to-contribute.md
Labels: documentation, qa/skip-qa

#1528 Update bundle and manager config from v1.10
  bundle/manifests/datadog-operator.clusterserviceversion.yaml
  bundle/manifests/datadoghq.com_datadogagents.yaml
  config/manager/kustomization.yaml
Labels: enhancement, qa/skip-qa

#1531 Fix pr-linter workflow
  .github/workflows/pr-linter.yml
Labels: tooling, qa/skip-qa

#1309 [CECO-1238] Configure checks tag cardinality within `spec.global.checksTagCardinality`
  api/datadoghq/common/envvar.go
  api/datadoghq/v2alpha1/datadogagent_types.go
  api/datadoghq/v2alpha1/test/builder.go
  api/datadoghq/v2alpha1/zz_generated.deepcopy.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  docs/configuration.v2alpha1.md
  internal/controller/datadogagent/override/global.go
  internal/controller/datadogagent/override/global_test.go
Labels: enhancement, mergequeue-status: in_progress

#1498 Add autodiscovery e2e test
  test/e2e/kind_test.go
  test/e2e/manifests/autodiscovery-annotation.yaml
Labels: tooling, qa/skip-qa

#1532 fix: include ADP container in certain pod-wide volume mount overrides
  internal/controller/datadogagent/override/global.go
Labels: bug, qa/skip-qa

#1533 fix: specify 'run' subcommand to ADP binary
  internal/controller/datadogagent/component/agent/default.go
Labels: bug, qa/skip-qa, mergequeue-status: in_progress

#1148 Add JSON Schema generation for V1 CRDs
  Makefile
  config/crd/bases/v1/datadoghq.com_datadogagentprofiles_v1alpha1.json
  config/crd/bases/v1/datadoghq.com_datadogagents_v1alpha1.json
  config/crd/bases/v1/datadoghq.com_datadogagents_v2alpha1.json
  config/crd/bases/v1/datadoghq.com_datadogdashboards_v1alpha1.json
  config/crd/bases/v1/datadoghq.com_datadogmetrics_v1alpha1.json
  config/crd/bases/v1/datadoghq.com_datadogmonitors_v1alpha1.json
  config/crd/bases/v1/datadoghq.com_datadogpodautoscalers_v1alpha1.json
  config/crd/bases/v1/datadoghq.com_datadogslos_v1alpha1.json
  hack/generate-docs/generate-docs.go
  hack/jsonschema/openapi2jsonschema.go
  hack/patch-crds.sh
Labels: tooling, qa/skip-qa, mergequeue-status: in_progress

#1455 [PROCS-4000] Update CRD to add new `ProcessChecksInCoreAgentEnabled` option in `global` section
  api/datadoghq/v2alpha1/datadogagent_default.go
  api/datadoghq/v2alpha1/datadogagent_types.go
  api/datadoghq/v2alpha1/test/builder.go
  api/datadoghq/v2alpha1/zz_generated.deepcopy.go
  cmd/main.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  docs/configuration.v2alpha1.md
  internal/controller/datadogagent/controller.go
  internal/controller/datadogagent/feature/apm/feature.go
  internal/controller/datadogagent/feature/apm/feature_test.go
  internal/controller/datadogagent/feature/livecontainer/feature.go
  internal/controller/datadogagent/feature/livecontainer/feature_test.go
  internal/controller/datadogagent/feature/liveprocess/feature.go
  internal/controller/datadogagent/feature/liveprocess/feature_test.go
  internal/controller/datadogagent/feature/processdiscovery/feature.go
  internal/controller/datadogagent/feature/processdiscovery/feature_test.go
  internal/controller/datadogagent/feature/types.go
  internal/controller/setup.go
Labels: enhancement, mergequeue-status: rejected

#1491 Add pod logs e2e test
  config/crd/bases/v1/datadoghq.com_datadogagents_v2alpha1.json
  test/e2e/kind_test.go
  test/e2e/manifests/datadog-agent-logs.yaml
Labels: tooling, qa/skip-qa

#1514 allow forwarder to be used by all controllers
  internal/controller/datadogagent/controller.go
  internal/controller/datadogagent_controller.go
  internal/controller/setup.go
  pkg/controller/utils/datadog/forwarders_manager.go
  pkg/controller/utils/datadog/metrics_forwarder.go
  pkg/controller/utils/datadog/metrics_forwarder_test.go
Labels: enhancement, refactoring

#1509 Use same instance label value for network policies
  internal/controller/datadogagent/component/objects/network.go
Labels: bug

#1522 move processing of labels and annotations as tags
  internal/controller/datadogagent/feature/enabledefault/feature.go
  internal/controller/datadogagent/feature/enabledefault/rbac.go
  internal/controller/datadogagent/feature/enabledefault/rbac_test.go
  internal/controller/datadogagent/override/global.go
  internal/controller/datadogagent/override/rbac.go
Labels: bug

#1515 Add network policies for admission controller feature
  internal/controller/datadogagent/feature/admissioncontroller/feature.go
Labels: enhancement

#1536 [CONTP-508] Supporting startupProbe in operator
  api/datadoghq/v2alpha1/datadogagent_types.go
  api/datadoghq/v2alpha1/zz_generated.deepcopy.go
  api/datadoghq/v2alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1/datadoghq.com_datadogagents_v2alpha1.json
  docs/configuration.v2alpha1.md
  internal/controller/datadogagent/component/agent/default.go
  internal/controller/datadogagent/override/container.go
  internal/controller/datadogagent/override/container_test.go
  internal/controller/testutils/agent.go
Labels: enhancement, mergequeue-status: rejected

#1537 add allowmap for container image overrides
  api/datadoghq/common/types.go
  internal/controller/datadogagent/override/container.go
  internal/controller/datadogagent/override/podtemplatespec.go
  internal/controller/datadogagent/override/podtemplatespec_test.go
Labels: enhancement, mergequeue-status: rejected

#1461 feat(admission controller): Add new webhook settings
  api/datadoghq/common/envvar.go
  api/datadoghq/v2alpha1/datadogagent_default.go
  api/datadoghq/v2alpha1/datadogagent_default_test.go
  api/datadoghq/v2alpha1/datadogagent_types.go
  api/datadoghq/v2alpha1/test/builder.go
  api/datadoghq/v2alpha1/zz_generated.deepcopy.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1/datadoghq.com_datadogagents_v2alpha1.json
  docs/configuration.v2alpha1.md
  internal/controller/datadogagent/feature/admissioncontroller/feature.go
  internal/controller/datadogagent/feature/admissioncontroller/feature_test.go
  internal/controller/datadogagent/feature/types.go
Labels: enhancement

#1540 update default fips-proxy image version to 1.1.6
  pkg/defaulting/images.go
Labels: enhancement

#1541 [tooling] use generated GITHUB_TOKEN for authentication
  .github/workflows/release.yaml
Labels: tooling, qa/skip-qa
