Repository DataDog/datadog-operator, pull requests merged in 2024-08, with the labels that each got.

#1339 Remove XValidation rule in DPA as requires K8S >= 1.25
  apis/datadoghq/v1alpha1/datadogpodautoscaler_types.go
  config/crd/bases/v1/datadoghq.com_datadogpodautoscalers.yaml
Labels: bug, qa/skip-qa

#1344 [cleanup] cleanup unused constant files
  apis/datadoghq/common/const.go
  apis/datadoghq/v1alpha1/const.go
  controllers/datadogagent/component/const.go
  controllers/datadogagent/object/rbac/clusterrolebinding.go
  controllers/datadogagent/object/volume/volumes.go
  controllers/datadogagent/orchestrator/envs.go
  controllers/datadogagent_controller_profiles_test.go
  controllers/datadogagent_controller_test.go
  controllers/datadogagent_controller_v2_test.go
  controllers/suite_test.go
Labels: refactoring

#1345 Use `unknown` tool version when env var is not set
  controllers/datadogagent/feature/enabledefault/feature.go
  controllers/datadogagent/feature/enabledefault/feature_test.go
Labels: enhancement

#1346 Bump default Agent version to 7.55.2 (#1332)
  pkg/defaulting/images.go
Labels: enhancement

#1347 Remove XValidation rule as requires K8S >= 1.25 (#1339)
  apis/datadoghq/v1alpha1/datadogpodautoscaler_types.go
  config/crd/bases/v1/datadoghq.com_datadogpodautoscalers.yaml
Labels: bug, qa/skip-qa

#1348 Use `unknown` tool version when env var is not set (#1345)
  controllers/datadogagent/feature/enabledefault/feature.go
  controllers/datadogagent/feature/enabledefault/feature_test.go
Labels: enhancement

#1349 Bump Go version in go.mod and Dockerfiles to 1.22.4
  Dockerfile
  check-operator.Dockerfile
  go.mod
Labels: tooling

#1350 Bump Go version in go.mod and Dockerfiles to 1.22.4 (#1349)
  Dockerfile
  check-operator.Dockerfile
  go.mod
Labels: tooling

#1316 Minimal dashboard
  PROJECT
  apis/datadoghq/v1alpha1/datadogdashboard_types.go
  apis/datadoghq/v1alpha1/datadogdashboard_validation.go
  apis/datadoghq/v1alpha1/zz_generated.deepcopy.go
  apis/datadoghq/v1alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogdashboards.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_datadoghq_datadogdashboards.yaml
  config/crd/patches/webhook_in_datadoghq_datadogdashboards.yaml
  config/rbac/datadoghq_datadogdashboard_editor_role.yaml
  config/rbac/datadoghq_datadogdashboard_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/datadoghq_v1alpha1_datadogdashboard.yaml
  config/samples/kustomization.yaml
  controllers/datadogdashboard/controller.go
  controllers/datadogdashboard/dashboard.go
  controllers/datadogdashboard/finalizer.go
  controllers/datadogdashboard_controller.go
  controllers/setup.go
  go.mod
  go.sum
  go.work.sum
  main.go
  pkg/datadogclient/client.go
Labels: enhancement, qa/skip-qa

#1294 Support custom e2e kustomization resources
  .gitlab-ci.yml
  Makefile
  go.work.sum
  test/e2e/common.go
  test/e2e/go.mod
  test/e2e/go.sum
  test/e2e/kind_e2e_test.go
  test/e2e/main.go
  test/e2e/manifests/datadog-agent-minimum.yaml
Labels: tooling, qa/skip-qa

#1354 [cleanup] rm unused apis code
  apis/datadoghq/v1alpha1/datadogagent_conversion.go
  apis/datadoghq/v1alpha1/datadogagent_conversion_agent.go
  apis/datadoghq/v1alpha1/datadogagent_conversion_ccr.go
  apis/datadoghq/v1alpha1/datadogagent_conversion_dca.go
  apis/datadoghq/v1alpha1/datadogagent_conversion_test.go
  apis/datadoghq/v1alpha1/datadogagent_default.go
  apis/datadoghq/v1alpha1/datadogagent_default_test.go
  apis/datadoghq/v1alpha1/datadogagent_types.go
  apis/datadoghq/v1alpha1/datadogagent_validation.go
  apis/datadoghq/v1alpha1/patch/datadogagent.go
  apis/datadoghq/v1alpha1/patch/datadogagent_test.go
  apis/datadoghq/v1alpha1/secret.go
  apis/datadoghq/v1alpha1/test/new.go
  apis/datadoghq/v1alpha1/testdata/all.expected.yaml
  apis/datadoghq/v1alpha1/testdata/all.yaml
  apis/datadoghq/v1alpha1/testdata/empty.expected.yaml
  apis/datadoghq/v1alpha1/testdata/empty.yaml
  apis/datadoghq/v1alpha1/testdata/featureOvr.expected.yaml
  apis/datadoghq/v1alpha1/testdata/featureOvr.yaml
  apis/datadoghq/v1alpha1/utils.go
  apis/datadoghq/v1alpha1/utils_test.go
  apis/datadoghq/v1alpha1/zz_generated.deepcopy.go
  apis/datadoghq/v1alpha1/zz_generated.openapi.go
  cmd/check-operator/upgrade/upgrade.go
  cmd/kubectl-datadog/agent/upgrade/upgrade.go
  cmd/kubectl-datadog/agent/upgrade/upgrade_test.go
  cmd/kubectl-datadog/clusteragent/upgrade/upgrade.go
  cmd/kubectl-datadog/clusteragent/upgrade/upgrade_test.go
  cmd/kubectl-datadog/flare/flare.go
  cmd/kubectl-datadog/get/get.go
  controllers/testutils/new.go
  pkg/controller/utils/condition/condition.go
  pkg/plugin/common/options.go
  pkg/plugin/common/statuswrapper.go
  pkg/plugin/common/v2support.go
Labels: refactoring

#1359 [docs] Update dap docs for 1.8.0 release
  docs/datadog_agent_profiles.md
Labels: documentation, qa/skip-qa

#1353 Adding vital widgets
  apis/datadoghq/v1alpha1/datadogdashboard_types.go
  apis/datadoghq/v1alpha1/zz_generated.deepcopy.go
  apis/datadoghq/v1alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogdashboards.yaml
  controllers/datadogdashboard/dashboard.go
Labels: enhancement, qa/skip-qa

#1363 [default/images] Bump default agent/cluster agent version to `7.56.0`
  pkg/defaulting/images.go
Labels: enhancement, mergequeue-status: removed

#1364 Update operator-manifest-tools args for 0.6.0
  hack/redhat-bundle.sh
Labels: tooling, qa/skip-qa

#1362 Adding Tests to Dashboard CRD
  apis/datadoghq/v1alpha1/datadogdashboard_validation_test.go
  controllers/datadogdashboard/controller.go
  controllers/datadogdashboard/controller_test.go
  controllers/datadogdashboard/dashboard_test.go
  controllers/datadogdashboard/finalizer_test.go
  controllers/datadogdashboard_controller.go
Labels: enhancement, qa/skip-qa

#1367 Supporting JSON string to make Dashboards
  apis/datadoghq/v1alpha1/datadogdashboard_types.go
  apis/datadoghq/v1alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogdashboards.yaml
  controllers/datadogdashboard/controller.go
  controllers/datadogdashboard/dashboard.go
  controllers/datadogdashboard/dashboard.json
  controllers/datadogdashboard/dashboard_test.go
Labels: enhancement, qa/skip-qa

#1351 [cleanup] reorganize rbac-related methods
  controllers/datadogagent/common/const.go
  controllers/datadogagent/common/utils.go
  controllers/datadogagent/common/volumes.go
  controllers/datadogagent/component/agent/default.go
  controllers/datadogagent/component/agent/new.go
  controllers/datadogagent/component/agent/rbac.go
  controllers/datadogagent/component/clusteragent/default.go
  controllers/datadogagent/component/clusteragent/default_test.go
  controllers/datadogagent/component/clusteragent/utils.go
  controllers/datadogagent/component/clusterchecksrunner/default.go
  controllers/datadogagent/component/clusterchecksrunner/default_test.go
  controllers/datadogagent/component/new.go
  controllers/datadogagent/component/objects/network.go
  controllers/datadogagent/controller_reconcile_agent.go
  controllers/datadogagent/dependencies/store.go
  controllers/datadogagent/feature/apm/feature.go
  controllers/datadogagent/feature/clusterchecks/feature.go
  controllers/datadogagent/feature/dogstatsd/feature.go
  controllers/datadogagent/feature/enabledefault/configmap.go
  controllers/datadogagent/feature/enabledefault/feature.go
  controllers/datadogagent/feature/enabledefault/rbac.go
  controllers/datadogagent/feature/externalmetrics/feature.go
  controllers/datadogagent/feature/kubernetesstatecore/feature.go
  controllers/datadogagent/feature/orchestratorexplorer/feature.go
  controllers/datadogagent/feature/otlp/feature.go
  controllers/datadogagent/feature/utils/utils.go
  controllers/datadogagent/override/dependencies.go
  controllers/datadogagent/override/global.go
  controllers/datadogagent_controller_profiles_test.go
Labels: refactoring

#1366 [PROCS-4294] Add ability to run Language Detection in Core Agent
  controllers/datadogagent/feature/apm/feature.go
  controllers/datadogagent/feature/apm/feature_test.go
  controllers/datadogagent/feature/livecontainer/feature_test.go
  controllers/datadogagent/feature/liveprocess/feature_test.go
  controllers/datadogagent/feature/processdiscovery/feature_test.go
  controllers/datadogagent/feature/utils/utils.go
Labels: enhancement

#1376 chore(lint): fix FromAsCasing warnings
  Dockerfile
  check-operator.Dockerfile
Labels: bug, qa/skip-qa

#1378 Move UpdateStrategy from v2alpha1 to common/v1
  apis/datadoghq/common/v1/agent_types.go
  apis/datadoghq/common/v1/zz_generated.deepcopy.go
  apis/datadoghq/v2alpha1/datadogagent_types.go
  apis/datadoghq/v2alpha1/zz_generated.deepcopy.go
  apis/datadoghq/v2alpha1/zz_generated.openapi.go
  controllers/datadogagent/override/daemonset_test.go
Labels: refactoring, qa/skip-qa

#1373 [profiles] Add update strategy overrides to profiles
  apis/datadoghq/v1alpha1/datadogagentprofile_types.go
  apis/datadoghq/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/v1/datadoghq.com_datadogagentprofiles.yaml
  pkg/agentprofile/agent_profile.go
  pkg/agentprofile/agent_profile_test.go
Labels: enhancement

#1374 [CONS-6524] Standardize OpenShift examples
  docs/install-openshift.md
  examples/datadogagent/datadog-agent-on-openshift.yaml
Labels: documentation, qa/skip-qa

#1385 Increase waitFor duration for KSM E2E tests
  test/e2e/kind_test.go
Labels: bug, qa/skip-qa

#1384 Update mergequeue configuration
  repository.datadog.yml
Labels: bug, qa/skip-qa

#1382 fix Go module files
  go.mod
  test/e2e/go.mod
Labels: tooling, qa/skip-qa

#1375 fix: support lease obj in kubectl datadog clusteragent leader cmd
  .devcontainer/devcontainer.json
  cmd/kubectl-datadog/clusteragent/leader/leader.go
  pkg/plugin/common/options.go
Labels: bug, mergequeue-status: in_progress

#1386 Do not rebuild image during merge-queue workflow
  .gitlab-ci.yml
Labels: enhancement, tooling, qa/skip-qa, mergequeue-status: in_progress
