Repository DataDog/datadog-operator, pull requests merged in 2024-03, with the labels that each got.

#1106 [CECO-1015] Propagate edsMaxPodUnavailable value to DS
  controllers/datadogagent/component/agent/default.go
  controllers/datadogagent/component/agent/new.go
  controllers/datadogagent/controller_reconcile_agent.go
Labels: enhancement

#1107 [tooling] update bundle script to include webhook and required annotations
  config/default/kustomization.yaml
  config/manager/manager.yaml
  hack/patch-bundle.sh
Labels: tooling, qa/skip-qa

#1109 [tooling] update bundle script to include webhook and required annotations (#1107)
  config/default/kustomization.yaml
  config/manager/manager.yaml
  hack/patch-bundle.sh
Labels: tooling, qa/skip-qa

#1110 [tooling] update bundle script to include webhook and required annotations (#1107)
  config/default/kustomization.yaml
  config/manager/manager.yaml
  hack/patch-bundle.sh
Labels: tooling, qa/skip-qa

#1108 [profiles] Stop using pod indexer
  controllers/datadogagent/controller_reconcile_agent.go
  controllers/datadogagent_controller.go
Labels: enhancement

#1112 [tooling] small fix for bundle generation (certs)
  config/default/kustomization.yaml
Labels: tooling, qa/skip-qa

#1114 [tooling] another small fix for bundle (#1112)
  config/default/kustomization.yaml
Labels: tooling, qa/skip-qa

#1115 Fix log line formatting for conflicting profiles
  pkg/agentprofile/agent_profile.go
Labels: bug

#1111 Add md5 hash config annotation to helm check
  controllers/datadogagent/feature/helmcheck/feature.go
  controllers/datadogagent/feature/helmcheck/feature_test.go
Labels: bug

#1117 Add md5 hash config annotation to helm check (#1111)
  controllers/datadogagent/feature/helmcheck/feature.go
  controllers/datadogagent/feature/helmcheck/feature_test.go
Labels: bug

#1122 SBOM: limit env injection for SBOM feature to core agent
  controllers/datadogagent/feature/sbom/feature.go
  controllers/datadogagent/feature/sbom/feature_test.go
Labels: bug

#1119 Fix readinessprobe and livenessprobe for non-nil probehandler overrides
  controllers/datadogagent/override/container.go
  controllers/datadogagent/override/container_test.go
  controllers/datadogagent/override/utils.go
Labels: bug

#1124 Fix readinessprobe and livenessprobe for non-nil probehandler overrides (#1119)
  controllers/datadogagent/override/container.go
  controllers/datadogagent/override/container_test.go
  controllers/datadogagent/override/utils.go
Labels: bug

#1126 [add-remote-config] initial commit
  .golangci.toml
  LICENSE-3rdparty.csv
  go.mod
  go.sum
  main.go
  pkg/remoteconfig/updater.go
Labels: enhancement, qa/skip-qa

#1129 Pin setup-envtest version
  Makefile
Labels: tooling, qa/skip-qa

#1123 Add notify_by, groupby_simple_monitor, & renotify_occurrences config options to monitors crd
  apis/datadoghq/v1alpha1/datadogmonitor_types.go
  apis/datadoghq/v1alpha1/zz_generated.deepcopy.go
  apis/datadoghq/v1alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogmonitors.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogmonitors.yaml
  controllers/datadogmonitor/monitor.go
  controllers/datadogmonitor/monitor_test.go
Labels: enhancement

#1125 [PROCS-3915] Add agent version check to Orchestrator Explorer feature to determine if process agent is required
  controllers/datadogagent/feature/orchestratorexplorer/feature.go
  controllers/datadogagent/feature/orchestratorexplorer/feature_test.go
Labels: enhancement, mergequeue-status: removed

#1128 [docs] Add migration instructions for introspection docs
  docs/introspection.md
Labels: documentation, qa/skip-qa
