Repository DataDog/datadog-operator, pull requests merged in 2024-10, with the labels that each got.

#1441 [docs] add doc for datadogdashboard
  docs/datadog_dashboard.md
  docs/datadog_monitor.md
Labels: documentation, qa/skip-qa

#1429 Load environment variables in override with `envFrom`
  api/datadoghq/v2alpha1/datadogagent_types.go
  api/datadoghq/v2alpha1/zz_generated.deepcopy.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  docs/configuration.v2alpha1.md
  internal/controller/datadogagent/feature/fake/PodTemplateManagers.go
  internal/controller/datadogagent/feature/types.go
  internal/controller/datadogagent/merger/envvarfrom.go
  internal/controller/datadogagent/merger/envvarfrom_test.go
  internal/controller/datadogagent/merger/envvars_test.go
  internal/controller/datadogagent/merger/fake/envfromvar_manager.go
  internal/controller/datadogagent/override/podtemplatespec.go
Labels: enhancement

#1395 [CECO-743] Secret backend configuration
  api/datadoghq/common/envvar.go
  api/datadoghq/v2alpha1/datadogagent_types.go
  api/datadoghq/v2alpha1/test/builder.go
  api/datadoghq/v2alpha1/zz_generated.deepcopy.go
  api/datadoghq/v2alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  docs/configuration.v2alpha1.md
  internal/controller/datadogagent/merger/rbac.go
  internal/controller/datadogagent/override/global.go
  internal/controller/datadogagent/override/global_test.go
Labels: enhancement, component/controller, mergequeue-status: in_progress

#1427 add metric for max goroutines set in the operator
  cmd/main.go
  internal/controller/metrics/datadogoperator.go
Labels: enhancement

#1436 Consolidate versionInfo and platformInfo
  internal/controller/datadogagent/controller.go
  internal/controller/datadogagent/controller_reconcile_v2.go
  internal/controller/datadogagent/feature/apm/feature.go
  internal/controller/datadogagent/feature/dogstatsd/feature.go
  internal/controller/datadogagent/feature/externalmetrics/feature.go
  internal/controller/datadogagent/feature/otlp/feature.go
  internal/controller/datadogagent/store/store.go
  internal/controller/datadogagent_controller.go
  internal/controller/datadogdashboard/controller.go
  internal/controller/datadogdashboard/controller_test.go
  internal/controller/datadogdashboard_controller.go
  internal/controller/datadogmonitor/controller.go
  internal/controller/datadogmonitor_controller.go
  internal/controller/datadogslo/controller.go
  internal/controller/datadogslo/controller_test.go
  internal/controller/datadogslo_controller.go
  internal/controller/setup.go
  pkg/kubernetes/platforminfo.go
Labels: refactoring

#1243 Add e2e tests for the remote config updater
  config/e2e/kustomization.yaml
  config/e2e/rc-e2e-manager.yaml
  docs/how-to-contribute.md
  pkg/remoteconfig/updater.go
  test/e2e/common.go
  test/e2e/kind_test.go
  test/e2e/manifests/datadog-agent-rc-updater.yaml
  test/e2e/rc-updater/api/client.go
  test/e2e/rc-updater/api/ddsql.go
  test/e2e/rc-updater/api/updater.go
  test/e2e/rc-updater/common.go
  test/e2e/rc_updater_test.go
Labels: tooling, qa/skip-qa

#1440 Allow the ability to disable or specify custom host ports for OTLP
  api/datadoghq/v2alpha1/datadogagent_default.go
  api/datadoghq/v2alpha1/datadogagent_default_test.go
  api/datadoghq/v2alpha1/datadogagent_types.go
  api/datadoghq/v2alpha1/test/builder.go
  api/datadoghq/v2alpha1/zz_generated.deepcopy.go
  api/datadoghq/v2alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  docs/configuration.v2alpha1.md
  internal/controller/datadogagent/feature/otlp/feature.go
  internal/controller/datadogagent/feature/otlp/feature_test.go
Labels: enhancement

#1450 [chore] Fix alignment of Reconciler struct init in SLO controller
  internal/controller/datadogslo/controller.go
Labels: component/controller, tooling, qa/skip-qa, mergequeue-status: in_progress

#1404 [CECO-2][DatadogMonitor] Configure force sync period
  docs/datadog_monitor.md
  internal/controller/datadogmonitor/controller.go
Labels: enhancement, feature/datadog-monitor, mergequeue-status: error

#1444 [cleanup] move constants to feature-specific files
  api/datadoghq/common/const.go
  api/datadoghq/v2alpha1/datadogagent_default.go
  api/datadoghq/v2alpha1/datadogagent_default_test.go
  internal/controller/datadogagent/common/volumes.go
  internal/controller/datadogagent/feature/admissioncontroller/const.go
  internal/controller/datadogagent/feature/admissioncontroller/feature.go
  internal/controller/datadogagent/feature/apm/const.go
  internal/controller/datadogagent/feature/apm/feature.go
  internal/controller/datadogagent/feature/apm/feature_test.go
  internal/controller/datadogagent/feature/cspm/const.go
  internal/controller/datadogagent/feature/cspm/feature.go
  internal/controller/datadogagent/feature/cspm/feature_test.go
  internal/controller/datadogagent/feature/cws/const.go
  internal/controller/datadogagent/feature/cws/feature.go
  internal/controller/datadogagent/feature/cws/feature_test.go
  internal/controller/datadogagent/feature/eventcollection/const.go
  internal/controller/datadogagent/feature/eventcollection/feature.go
  internal/controller/datadogagent/feature/externalmetrics/const.go
  internal/controller/datadogagent/feature/externalmetrics/feature.go
  internal/controller/datadogagent/feature/helmcheck/const.go
  internal/controller/datadogagent/feature/helmcheck/feature.go
  internal/controller/datadogagent/feature/kubernetesstatecore/const.go
  internal/controller/datadogagent/feature/kubernetesstatecore/feature.go
  internal/controller/datadogagent/feature/logcollection/const.go
  internal/controller/datadogagent/feature/logcollection/feature.go
  internal/controller/datadogagent/feature/logcollection/feature_test.go
  internal/controller/datadogagent/feature/orchestratorexplorer/const.go
  internal/controller/datadogagent/feature/orchestratorexplorer/feature.go
  internal/controller/datadogagent/feature/otlp/const.go
  internal/controller/datadogagent/feature/otlp/feature.go
  internal/controller/datadogagent/feature/otlp/feature_test.go
  internal/controller/datadogagent/feature/sbom/const.go
  internal/controller/datadogagent/feature/sbom/feature.go
  internal/controller/datadogagent/feature/sbom/feature_test.go
Labels: refactoring

#1453 [conductor] update workflow name
  service.datadog.yaml
Labels: tooling, qa/skip-qa

#1451 release v1.9.0
  bundle/manifests/datadog-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
Labels: enhancement

#1448 Fix behavior when overriding names of DCA and CCR components
  internal/controller/datadogagent/controller_reconcile_ccr.go
  internal/controller/datadogagent/controller_reconcile_ccr_test.go
  internal/controller/datadogagent/controller_reconcile_dca.go
  internal/controller/datadogagent/controller_reconcile_dca_test.go
  internal/controller/datadogagent/controller_reconcile_v2.go
Labels: bug, fixed

#1446 [gitlab] trigger operator release candidate workflow
  .gitlab-ci.yml
Labels: tooling, qa/skip-qa

#1425 Add ServiceAccountAnnotations override
  api/datadoghq/v2alpha1/datadogagent_types.go
  api/datadoghq/v2alpha1/utils.go
  api/datadoghq/v2alpha1/utils_test.go
  api/datadoghq/v2alpha1/zz_generated.deepcopy.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/manager/kustomization.yaml
  docs/configuration.v2alpha1.md
  internal/controller/datadogagent/feature/enabledefault/feature.go
  internal/controller/datadogagent/merger/rbac.go
  internal/controller/datadogagent/merger/rbac_test.go
Labels: documentation, enhancement

#1456 [gitlab] fix workflow name
  .gitlab-ci.yml
Labels: tooling, qa/skip-qa

#1379 expose kubernetes_resources_labels/annotations_as_tags
  api/datadoghq/common/envvar.go
  api/datadoghq/v2alpha1/datadogagent_types.go
  api/datadoghq/v2alpha1/zz_generated.deepcopy.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  docs/configuration.v2alpha1.md
  internal/controller/datadogagent/component/clusteragent/utils.go
  internal/controller/datadogagent/override/global.go
  internal/controller/datadogagent/override/rbac.go
  internal/controller/datadogagent/override/rbac_test.go
  internal/controller/testutils/agent.go
Labels: enhancement

#1462 [gitlab] fix conditional to run release candidate workflow
  .gitlab-ci.yml
Labels: tooling, qa/skip-qa

#1457 Fix CiliumNetworkPolicy not updating properly
  internal/controller/datadogagent/store/store.go
Labels: bug, fixed

#1459 [cleanup] remove unused Pod Security Policy
  config/rbac/role.yaml
  internal/controller/datadogagent/feature/cspm/const.go
  internal/controller/datadogagent/feature/cspm/feature.go
  internal/controller/datadogagent/feature/cspm/rbac.go
  internal/controller/datadogagent/feature/types.go
  internal/controller/datadogagent/merger/pod_security.go
  internal/controller/datadogagent/merger/pod_security_test.go
  internal/controller/datadogagent_controller.go
  pkg/equality/equality.go
  pkg/kubernetes/const.go
  pkg/kubernetes/objects.go
  pkg/kubernetes/objectslist.go
  pkg/kubernetes/platforminfo.go
  pkg/kubernetes/platforminfo_test.go
  pkg/kubernetes/rbac/const.go
Labels: refactoring

#1463 [cleanup] remove Pod Security Policy from `platforminfo_test`
  pkg/kubernetes/platforminfo_test.go
Labels: refactoring

#1443 Create different configmap names for Agent/Cluster Agent/CCR when using customConfigurations
  internal/controller/datadogagent/override/dependencies.go
  internal/controller/datadogagent/override/podtemplatespec.go
  internal/controller/datadogagent/override/podtemplatespec_test.go
Labels: bug, fixed

#1452 Include ports for networkpolicy or ciliumnetworkpolicy for OTLP ingest
  internal/controller/datadogagent/feature/otlp/feature.go
Labels: bug, enhancement

#1465 fix(kustomize): set correct image name and tag
  config/manager/kustomization.yaml
Labels: bug, qa/skip-qa, mergequeue-status: in_progress

#1469 Do not log error if sync variable is not set (#1466)
  internal/controller/datadogmonitor/controller.go
Labels: bug, mergequeue-status: in_progress

#1467 Implement label and annotation equality checking
  pkg/equality/equality.go
  pkg/equality/equality_test.go
Labels: bug, enhancement

#1470 Implement label and annotation equality checking (#1467)
  pkg/equality/equality.go
  pkg/equality/equality_test.go
Labels: bug, enhancement, qa/skip-qa

#1468 [cleanup] remove unused v1beta1 version of PDB
  internal/controller/datadogagent/testutils/client_utils.go
  internal/controller/datadogagent_controller.go
  pkg/equality/equality.go
  pkg/kubernetes/objects.go
  pkg/kubernetes/objectslist.go
  pkg/kubernetes/platforminfo.go
  pkg/kubernetes/platforminfo_test.go
Labels: refactoring

#1471 Fix secret equality checking
  pkg/equality/equality.go
  pkg/equality/equality_test.go
Labels: bug

#1340 [Orch] Add CRD RC handler
  go.mod
  go.sum
  go.work.sum
  internal/controller/datadogagent/feature/orchestratorexplorer/feature.go
  internal/controller/datadogagent/feature/orchestratorexplorer/feature_test.go
  pkg/remoteconfig/orchestrator_k8s_crd.go
  pkg/remoteconfig/updater.go
Labels: enhancement, mergequeue-status: removed

#1475 Enable otel-agent using DDA annotation
  api/datadoghq/v2alpha1/test/builder.go
  internal/controller/datadogagent/feature/enabledefault/feature.go
  internal/controller/datadogagent/feature/test/factory_test.go
Labels: enhancement

#1283 tool: script to update the golang version
  .github/workflows/build.yml
  .github/workflows/main.yml
  .github/workflows/release.yaml
  .gitlab-ci.yml
  Makefile
  docs/how-to-contribute.md
  go.mod
  go.sum
  go.work
  go.work.sum
  hack/install-jq.sh
  hack/update-golang.sh
  test/e2e/go.mod
  test/e2e/go.sum
Labels: enhancement, tooling

#1478 Update agent / cluster-agent to 7.58.0 (#1476)
  pkg/defaulting/images.go
Labels: enhancement

#1479 [Orch] Add CRD RC handler (#1340)
  go.mod
  go.sum
  go.work.sum
  internal/controller/datadogagent/feature/orchestratorexplorer/feature.go
  internal/controller/datadogagent/feature/orchestratorexplorer/feature_test.go
  pkg/remoteconfig/orchestrator_k8s_crd.go
  pkg/remoteconfig/updater.go
Labels: enhancement

#1480 Enable otel-agent using DDA annotation (#1475)
  api/datadoghq/v2alpha1/test/builder.go
  internal/controller/datadogagent/feature/enabledefault/feature.go
  internal/controller/datadogagent/feature/test/factory_test.go
Labels: enhancement

#1481 tool: script to update the golang version (#1283)
  .github/workflows/build.yml
  .github/workflows/main.yml
  .github/workflows/release.yaml
  .gitlab-ci.yml
  Makefile
  docs/how-to-contribute.md
  go.mod
  go.sum
  go.work
  go.work.sum
  hack/install-jq.sh
  hack/update-golang.sh
  test/e2e/go.mod
  test/e2e/go.sum
Labels: tooling

#1482 release v1.10.0-rc.2
  bundle/manifests/datadog-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
Labels: enhancement

#1445 [CONTINT-4412] Upgrade `k8s` dependencies
  .gitlab-ci.yml
  LICENSE-3rdparty.csv
  Makefile
  api/datadoghq/v1alpha1/zz_generated.openapi.go
  api/datadoghq/v2alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagentprofiles.yaml
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1/datadoghq.com_datadogdashboards.yaml
  config/crd/bases/v1/datadoghq.com_datadogmetrics.yaml
  config/crd/bases/v1/datadoghq.com_datadogmonitors.yaml
  config/crd/bases/v1/datadoghq.com_datadogpodautoscalers.yaml
  config/crd/bases/v1/datadoghq.com_datadogslos.yaml
  config/rbac/role.yaml
  docs/configuration.v2alpha1.md
  go.mod
  go.sum
  go.work.sum
  internal/controller/datadogagent/controller_reconcile_agent_test.go
  internal/controller/datadogagent/controller_reconcile_ccr_test.go
  internal/controller/datadogagent/controller_reconcile_dca_test.go
  pkg/plugin/common/client.go
  pkg/remoteconfig/updater.go
  test/e2e/go.mod
  test/e2e/go.sum
Labels: dependencies, mergequeue-status: in_progress

#1484 [v1.10] set resource settings for build and unit_tests in gitlab
  .gitlab-ci.yml
Labels: tooling, qa/skip-qa

#1486 add generation changed predicate to dda controller
  internal/controller/datadogagent_controller.go
Labels: enhancement

#1492 Bump default agent/DCA image version to 7.58.1
  pkg/defaulting/images.go
Labels: enhancement

#1494 Bump golangci-lint timeout to 10m
  .golangci.toml
  go.work.sum
Labels: tooling

#1496 bump golangci-lint timeout to 10m (#1494)
  .golangci.toml
Labels: tooling, qa/skip-qa

#1497 Remove container `all` from description
  api/datadoghq/v2alpha1/datadogagent_types.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  docs/configuration.v2alpha1.md
Labels: bug, documentation
