Repository DataDog/datadog-operator, pull requests merged in 2024-05, with the labels that each got.

#1154 fix(controller): always try to update status
  apis/datadoghq/v2alpha1/condition.go
  apis/datadoghq/v2alpha1/condition_test.go
  cmd/check-operator/upgrade/upgrade.go
  controllers/datadogagent/controller_reconcile_agent.go
  controllers/datadogagent/controller_reconcile_ccr.go
  controllers/datadogagent/controller_reconcile_dca.go
  controllers/datadogagent/controller_reconcile_v2.go
Labels: bug, component/controller

#1163 [cherry-pick] fix(controller): always try to update status (#1154)
  apis/datadoghq/v2alpha1/condition.go
  apis/datadoghq/v2alpha1/condition_test.go
  cmd/check-operator/upgrade/upgrade.go
  controllers/datadogagent/controller_reconcile_agent.go
  controllers/datadogagent/controller_reconcile_ccr.go
  controllers/datadogagent/controller_reconcile_dca.go
  controllers/datadogagent/controller_reconcile_v2.go
Labels: bug, component/controller

#1157 [APM Onboarding] Use creation timestamp and UID of DatadogAgent as env vars for APM Telemetry KPIs
  apis/datadoghq/v1alpha1/test/new.go
  controllers/datadogagent/agent_test.go
  controllers/datadogagent/clusteragent_test.go
  controllers/datadogagent/component/agent/default.go
  controllers/datadogagent/component/clusteragent/default.go
  controllers/datadogagent/component/utils.go
  pkg/controller/utils/shared_utils.go
Labels: bug

#1164 [APM Onboarding] Use creation timestamp and UID of DatadogAgent as env vars for APM Telemetry KPIs (#1157)
  apis/datadoghq/v1alpha1/test/new.go
  controllers/datadogagent/agent_test.go
  controllers/datadogagent/clusteragent_test.go
  controllers/datadogagent/component/agent/default.go
  controllers/datadogagent/component/clusteragent/default.go
  controllers/datadogagent/component/utils.go
  pkg/controller/utils/shared_utils.go
Labels: enhancement, qa/skip-qa

#1166 add limitranges and storageclasses rbacs to orch explorer feature
  controllers/datadogagent/feature/orchestratorexplorer/rbac.go
Labels: enhancement

#1167 add limitranges and storageclasses rbacs to orch explorer feature (#1166)
  controllers/datadogagent/feature/orchestratorexplorer/rbac.go
Labels: enhancement

#1168 [cherry-pick] Disable provenance gitlab (#1133)
  Makefile
Labels: bug, tooling

#1170 [remote-config] add envvars missing from core agent for system probe features
  controllers/datadogagent/feature/cspm/feature.go
  controllers/datadogagent/feature/cws/feature.go
  controllers/datadogagent/feature/ebpfcheck/feature.go
  controllers/datadogagent/feature/npm/feature.go
  controllers/datadogagent/feature/oomkill/feature.go
  controllers/datadogagent/feature/tcpqueuelength/feature.go
  controllers/datadogagent/feature/usm/feature.go
  controllers/datadogagent/merger/envvars.go
  controllers/datadogagent/merger/fake/envvar_manager.go
Labels: enhancement, qa/skip-qa

#1174 [bundle] add openmetrics check annotation
  bundle/manifests/datadog-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
Labels: enhancement, component/olm

#1183 Bump openshift-preflight version to 1.9.4
  Makefile
Labels: tooling, qa/skip-qa

#1184 bump openshift-preflight version to 1.9.4 (#1183)
  Makefile
Labels: tooling, qa/skip-qa

#1173 [CECO-1109] Allow label overrides for ds for DDA updates
  controllers/datadogagent/controller_reconcile_v2_common.go
  controllers/datadogagent/controller_reconcile_v2_common_test.go
Labels: bug

#1179 feat(origin detection): add OriginDetectionUnified setting
  apis/datadoghq/common/envvar.go
  apis/datadoghq/v2alpha1/datadogagent_types.go
  apis/datadoghq/v2alpha1/test/builder.go
  apis/datadoghq/v2alpha1/zz_generated.deepcopy.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  controllers/datadogagent/override/global.go
  controllers/datadogagent/override/global_test.go
  docs/configuration.v2alpha1.md
Labels: enhancement, mergequeue-status: removed

#1172 Add cluster name to all v2alpha examples
  examples/datadogagent/v2alpha1/datadog-agent-all.yaml
  examples/datadogagent/v2alpha1/datadog-agent-minimum.yaml
  examples/datadogagent/v2alpha1/datadog-agent-on-openshift.yaml
  examples/datadogagent/v2alpha1/datadog-agent-with-apm-hostport.yaml
  examples/datadogagent/v2alpha1/datadog-agent-with-clusteragent.yaml
  examples/datadogagent/v2alpha1/datadog-agent-with-dca-clusterchecksrunner.yaml
  examples/datadogagent/v2alpha1/datadog-agent-with-dca-with-orchestrator-explorer.yaml
  examples/datadogagent/v2alpha1/datadog-agent-with-extraconfd.yaml
  examples/datadogagent/v2alpha1/datadog-agent-with-logs-apm.yaml
  examples/datadogagent/v2alpha1/datadog-agent-with-otlp.yaml
  examples/datadogagent/v2alpha1/datadog-agent-with-remote-configuration.yaml
  examples/datadogagent/v2alpha1/datadog-agent-with-secret-backend.yaml
  examples/datadogagent/v2alpha1/datadog-agent-with-secret-keys.yaml
  examples/datadogagent/v2alpha1/datadog-agent-with-tolerations.yaml
  examples/datadogagent/v2alpha1/datadog-agent-with-unix-socket.yaml
Labels: enhancement, qa/skip-qa

#1188 Add Datadog SLO to PROJECT
  PROJECT
Labels: bug, tooling

#1189 remove deprecated v2alpha1 flag
  main.go
Labels: enhancement

#1192 [CECO-1183] Override install info tool version
  apis/datadoghq/common/envvar.go
  controllers/datadogagent/feature/enabledefault/feature.go
  controllers/datadogagent/feature/enabledefault/feature_test.go
Labels: enhancement

#1191 chore(mergequeue): add configuration
  repository.datadog.yml
Labels: tooling, qa/skip-qa

#1187 Fix agentConfig struct
  pkg/remoteconfig/updater.go
Labels: enhancement

#1181 [CECO-662] Add registry options in admission controller
  apis/datadoghq/common/envvar.go
  apis/datadoghq/v2alpha1/datadogagent_types.go
  apis/datadoghq/v2alpha1/zz_generated.deepcopy.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  controllers/datadogagent/clusteragent_test.go
  controllers/datadogagent/feature/admissioncontroller/feature.go
  controllers/datadogagent/feature/admissioncontroller/feature_test.go
  docs/configuration.v2alpha1.md
Labels: enhancement

#1193 Compare label hashes instead of recalculating spec hash for daemonsets
  controllers/datadogagent/controller_reconcile_v2_common.go
Labels: bug

#1197 remove webhook conversion and certmanager references from bundle
  config/crd/kustomization.yaml
  config/default/kustomization.yaml
  config/manager/manager.yaml
  hack/patch-bundle.sh
Labels: enhancement

#1146 [ClusterAgent] Add pods/exec ressource access to the cluster agent
  apis/datadoghq/common/envvar.go
  apis/datadoghq/v2alpha1/datadogagent_default.go
  apis/datadoghq/v2alpha1/datadogagent_default_test.go
  apis/datadoghq/v2alpha1/datadogagent_types.go
  apis/datadoghq/v2alpha1/test/builder.go
  apis/datadoghq/v2alpha1/zz_generated.deepcopy.go
  apis/utils/utils.go
  bundle/manifests/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  controllers/datadogagent/clusteragent_test.go
  controllers/datadogagent/feature/admissioncontroller/feature.go
  controllers/datadogagent/feature/admissioncontroller/feature_test.go
  controllers/datadogagent/feature/admissioncontroller/rbac.go
  controllers/datadogagent/feature/enabledefault/feature.go
  controllers/datadogagent/feature/enabledefault/feature_test.go
  controllers/datadogagent_controller.go
  controllers/datadogagent_controller_v2_test.go
  controllers/testutils/agent.go
  docs/configuration.v2alpha1.md
  pkg/kubernetes/rbac/const.go
Labels: enhancement

#1185 [SLO] fix reconcile bugs, add predicate to builder
  controllers/datadogslo/controller.go
  controllers/datadogslo/controller_test.go
  controllers/datadogslo_controller.go
  controllers/utils/tag.go
Labels: bug, feature/slo

#1200 Add v1beta1 CRD deprection warning
  README.md
  controllers/setup.go
Labels: enhancement

#1196 [remote-config] store RC config in dda status
  apis/datadoghq/v2alpha1/datadogagent_types.go
  apis/datadoghq/v2alpha1/zz_generated.deepcopy.go
  apis/datadoghq/v2alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  controllers/datadogagent/feature/cspm/feature.go
  controllers/datadogagent/feature/cws/feature.go
  controllers/datadogagent/feature/sbom/feature.go
  controllers/datadogagent/feature/usm/feature.go
  controllers/datadogagent_controller.go
  pkg/remoteconfig/updater.go
Labels: enhancement, qa/skip-qa

#1204 Bump agent image versions to 7.54
  pkg/defaulting/images.go
Labels: enhancement

#1203 [DatadogAgent] Aligns KSM Core default ConfigMap with Helm : adds pdbs, storageclasses, volumeattachments
  controllers/datadogagent/feature/kubernetesstatecore/configmap.go
Labels: enhancement, component/controller

#1202 [plugin] VULN-6817 escape dots in regex
  pkg/plugin/common/const.go
  pkg/plugin/common/utils.go
  pkg/plugin/common/utils_test.go
Labels: tooling, qa/skip-qa

#1207 [CECO-884] Add sidecar injection basic config in operator
  apis/datadoghq/common/envvar.go
  apis/datadoghq/v2alpha1/datadogagent_default.go
  apis/datadoghq/v2alpha1/datadogagent_types.go
  apis/datadoghq/v2alpha1/test/builder.go
  apis/datadoghq/v2alpha1/zz_generated.deepcopy.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  controllers/datadogagent/feature/admissioncontroller/feature.go
  controllers/datadogagent/feature/admissioncontroller/feature_test.go
  docs/configuration.v2alpha1.md
Labels: enhancement

#1199 Fix dead links for DDA v2alpha1 examples
  docs/configuration.v1alpha1.md
  docs/configuration.v2alpha1.md
  hack/generate-docs/header.markdown
  hack/generate-docs/v1alpha1_footer.markdown
  hack/generate-docs/v2alpha1_footer.markdown
Labels: documentation, qa/skip-qa

#1208 Refactoring cwsInstrumentation test in AC test
  apis/datadoghq/v2alpha1/test/builder.go
  controllers/datadogagent/feature/admissioncontroller/feature_test.go
Labels: enhancement

#1210 Revert "Adding KubeValidation Markers to align Datadog Operator behav…
  apis/datadoghq/v1alpha1/datadogagent_types.go
  apis/datadoghq/v1alpha1/zz_generated.openapi.go
  apis/datadoghq/v2alpha1/datadogagent_types.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  docs/configuration.v1alpha1.md
  docs/configuration.v2alpha1.md
Labels: bug

#1211 [tooling] specify ./apis for generated code
  Makefile
Labels: tooling

#1212 Revert "Adding KubeValidation Markers to align Datadog Operator behav…
  apis/datadoghq/v1alpha1/datadogagent_types.go
  apis/datadoghq/v1alpha1/zz_generated.openapi.go
  apis/datadoghq/v2alpha1/datadogagent_types.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  docs/configuration.v1alpha1.md
  docs/configuration.v2alpha1.md
Labels: bug

#1213 [tooling] specify ./apis for generated code (#1211)
  Makefile
Labels: tooling, qa/skip-qa

#1209 [CECO-1067] DDA config for Admission Controller sidecar injection using selector and profile
  apis/datadoghq/v2alpha1/datadogagent_types.go
  apis/datadoghq/v2alpha1/test/builder.go
  apis/datadoghq/v2alpha1/zz_generated.deepcopy.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  controllers/datadogagent/feature/admissioncontroller/feature.go
  controllers/datadogagent/feature/admissioncontroller/feature_test.go
  docs/configuration.v2alpha1.md
Labels: enhancement

#1214 [profile][CECO-795] Add dap status (#1155)
  apis/datadoghq/v1alpha1/datadogagentprofile_types.go
  apis/datadoghq/v1alpha1/zz_generated.deepcopy.go
  apis/datadoghq/v1alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagentprofiles.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagentprofiles.yaml
  controllers/datadogagent/controller_reconcile_v2.go
  controllers/datadogagent/controller_reconcile_v2_test.go
  pkg/agentprofile/agent_profile.go
  pkg/agentprofile/agent_profile_test.go
  pkg/agentprofile/status.go
  pkg/agentprofile/status_test.go
Labels: enhancement
