Repository DataDog/datadog-operator, pull requests merged in 2025-02, with the labels that each got.

#1649 Add watch env vars for dashboard and genericresource
  cmd/main.go
  pkg/config/config.go
  pkg/config/config_test.go
Labels: enhancement

#1657 Upgrade github artifact upload/download actions (#1656)
  .github/workflows/release.yaml
Labels: tooling, qa/skip-qa

#1655 release v1.12.0
  bundle-community-operators/manifests/datadog-operator.clusterserviceversion.yaml
  bundle/manifests/datadog-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
Labels: dependencies, qa/skip-qa

#1652 gpu: added cgroup mount to gpu feature
  internal/controller/datadogagent/feature/gpu/feature.go
  internal/controller/datadogagent/feature/gpu/feature_test.go
Labels: enhancement, mergequeue-status: in_progress

#1650 Add PodResources mount to agent
  api/datadoghq/v2alpha1/const.go
  api/datadoghq/v2alpha1/datadogagent_types.go
  api/datadoghq/v2alpha1/envvar.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1/datadoghq.com_datadogagents_v2alpha1.json
  docs/configuration.v2alpha1.md
  internal/controller/datadogagent/defaults/datadogagent_default.go
  internal/controller/datadogagent/override/global.go
  internal/controller/datadogagent/override/global_test.go
  pkg/testutils/builder.go
Labels: enhancement, mergequeue-status: in_progress

#1660 [CTK-4692] Enable process checks on core agent by default
  api/datadoghq/v2alpha1/datadogagent_types.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1/datadoghq.com_datadogagents_v2alpha1.json
  docs/configuration.v2alpha1.md
  internal/controller/datadogagent/controller_v2_test.go
  internal/controller/datadogagent/defaults/datadogagent_default.go
  internal/controller/datadogagent/feature/apm/feature.go
  internal/controller/datadogagent/feature/apm/feature_test.go
  internal/controller/datadogagent/feature/livecontainer/feature.go
  internal/controller/datadogagent/feature/livecontainer/feature_test.go
  internal/controller/datadogagent/feature/liveprocess/feature.go
  internal/controller/datadogagent/feature/liveprocess/feature_test.go
  internal/controller/datadogagent/feature/processdiscovery/feature.go
  internal/controller/datadogagent/feature/processdiscovery/feature_test.go
  internal/controller/datadogagent/feature/test/factory_test.go
  internal/controller/datadogagent/feature/utils/utils.go
  internal/controller/datadogagent_controller_profiles_test.go
Labels: enhancement

#1604 Add DD_AGENT_IPC_* env vars
  api/datadoghq/v2alpha1/envvar.go
  internal/controller/datadogagent/feature/otelcollector/feature.go
  internal/controller/datadogagent/feature/otelcollector/feature_test.go
Labels: enhancement

#1627 Update `make generate-openapi` to error when API violations occur
  Makefile
Labels: enhancement

#1661 Fixes for operator release (openshift preflight version, docker maintainer label)
  Dockerfile
  Makefile
Labels: tooling, qa/skip-qa

#1666 [CONTINT-4500] Add EKS Clusterrole Rule for EKS control plane metrics
  internal/controller/datadogagent/feature/enabledefault/rbac.go
  pkg/kubernetes/rbac/const.go
Labels: enhancement, qa/skip-qa, mergequeue-status: in_progress

#1665 Redhat preflight fixes for operator release (#1661)
  Dockerfile
  Makefile
Labels: tooling, qa/skip-qa

#1614 feat(injector): allow configuring injector version
  api/datadoghq/v2alpha1/datadogagent_types.go
  api/datadoghq/v2alpha1/zz_generated.deepcopy.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1/datadoghq.com_datadogagents_v2alpha1.json
  docs/configuration.v2alpha1.md
  internal/controller/datadogagent/defaults/datadogagent_default.go
  internal/controller/datadogagent/defaults/datadogagent_default_test.go
  internal/controller/datadogagent/feature/apm/envvar.go
  internal/controller/datadogagent/feature/apm/feature.go
  internal/controller/datadogagent/feature/apm/feature_test.go
  pkg/testutils/builder.go
Labels: enhancement, qa/skip-qa, mergequeue-status: in_progress

#1620 [cleanup] Remove unused files and unrelated logic from /api
  api/datadoghq/v2alpha1/datadogagent_conversion.go
  api/datadoghq/v2alpha1/datadogagent_webhook.go
  api/datadoghq/v2alpha1/secret.go
  api/go.mod
  api/go.sum
  internal/controller/datadogagent/component/agent/default.go
  internal/controller/datadogagent/controller_reconcile_v2.go
  internal/controller/datadogagent/feature/enabledefault/feature.go
  internal/controller/datadogagent/feature/eventcollection/feature.go
  internal/controller/datadogagent/feature/externalmetrics/feature.go
  pkg/controller/utils/datadog/metrics_forwarder.go
  pkg/secrets/secrets.go
Labels: refactoring

#1669 Generate EKS controlplane RBAC
  config/rbac/role.yaml
  internal/controller/datadogagent_controller.go
Labels: bug

#1664 Increase prometheus receiver scrape interval
  internal/controller/datadogagent/feature/otelcollector/configmap_test.go
  internal/controller/datadogagent/feature/otelcollector/defaultconfig/defaultconfig.go
  internal/controller/datadogagent/feature/otelcollector/feature_test.go
Labels: enhancement

#1676 Update latest Agent and Cluster Agent version to 7.62.2
  pkg/defaulting/images.go
Labels: enhancement, qa/skip-qa

#1677 update latest agent and cluster agent version to 7.62.2 (#1676)
  pkg/defaulting/images.go
Labels: enhancement, qa/skip-qa

#1679 [gitlab] update release candidate deployment environments
  .gitlab-ci.yml
Labels: tooling, qa/skip-qa

#1678 release v1.12.1-rc.1
  bundle-community-operators/manifests/datadog-operator.clusterserviceversion.yaml
  bundle/manifests/datadog-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
Labels: enhancement, qa/skip-qa

#1680 [gitlab] update rc deployment environments (#1679)
  .gitlab-ci.yml
Labels: tooling, qa/skip-qa

#1634 [CECO-1860][DatadogGenericResource] Refactor handler
  internal/controller/datadoggenericresource/finalizer_test.go
  internal/controller/datadoggenericresource/notebooks.go
  internal/controller/datadoggenericresource/notebooks_test.go
  internal/controller/datadoggenericresource/resource_handler.go
  internal/controller/datadoggenericresource/synthetics.go
  internal/controller/datadoggenericresource/synthetics_test.go
  internal/controller/datadoggenericresource/utils.go
  internal/controller/datadoggenericresource/utils_test.go
Labels: refactoring

#1685 release v1.12.1
  bundle-community-operators/manifests/datadog-operator.clusterserviceversion.yaml
  bundle/manifests/datadog-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
Labels: dependencies, qa/skip-qa

#1684 Levan m/gitlab gbi image jobs
  .gitlab-ci.yml
Labels: tooling, qa/skip-qa

#1648 [CECO-1860][DatadogGenericResource] Documentation
  docs/datadog_generic_resource.md
  docs/datadog_generic_resource_dev.md
  examples/datadoggenericresource/api-test-sample.yaml
  examples/datadoggenericresource/browser-test-sample.yaml
  examples/datadoggenericresource/monitor-sample.yaml
  examples/datadoggenericresource/notebook-sample.yaml
Labels: documentation, qa/skip-qa

#1682 Add support for SBOMs on CRI-O
  internal/controller/datadogagent/feature/sbom/const.go
  internal/controller/datadogagent/feature/sbom/feature.go
Labels: enhancement

#1674 Use PodResources mount as a path instead of file
  api/datadoghq/v2alpha1/datadogagent_types.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1/datadoghq.com_datadogagents_v2alpha1.json
  docs/configuration.v2alpha1.md
  internal/controller/datadogagent/defaults/datadogagent_default.go
  internal/controller/datadogagent/override/global.go
  internal/controller/datadogagent/override/global_test.go
  pkg/testutils/builder.go
Labels: bug

#1663 Share common types between Autoscaler versions
  .github/CODEOWNERS
  api/datadoghq/common/datadogpodautoscaler_types.go
  api/datadoghq/common/zz_generated.deepcopy.go
  api/datadoghq/v1alpha1/datadogpodautoscaler_types.go
  api/datadoghq/v1alpha1/zz_generated.deepcopy.go
  api/datadoghq/v1alpha2/datadogpodautoscaler_conversion.go
  api/datadoghq/v1alpha2/datadogpodautoscaler_conversion_test.go
  api/datadoghq/v1alpha2/datadogpodautoscaler_types.go
  api/datadoghq/v1alpha2/zz_generated.deepcopy.go
  api/go.mod
  api/utils/utils.go
  config/crd/bases/v1/datadoghq.com_datadogpodautoscalers.yaml
  config/crd/bases/v1/datadoghq.com_datadogpodautoscalers_v1alpha1.json
  config/crd/bases/v1/datadoghq.com_datadogpodautoscalers_v1alpha2.json
Labels: enhancement, qa/skip-qa

#1691 (tooling) [devcontainer] Use gci lint + install tools
  .devcontainer/devcontainer.json
Labels: tooling, qa/skip-qa

#1635 [CECO-1860][DatadogGenericResource] Add monitor support
  api/datadoghq/v1alpha1/datadoggenericresource_types.go
  api/datadoghq/v1alpha1/datadoggenericresource_validation.go
  config/crd/bases/v1/datadoghq.com_datadoggenericresources.yaml
  config/crd/bases/v1/datadoghq.com_datadoggenericresources_v1alpha1.json
  internal/controller/datadoggenericresource/controller.go
  internal/controller/datadoggenericresource/controller_test.go
  internal/controller/datadoggenericresource/finalizer_test.go
  internal/controller/datadoggenericresource/monitors.go
  internal/controller/datadoggenericresource/synthetics_test.go
  internal/controller/datadoggenericresource/utils.go
  internal/controller/datadoggenericresource/utils_test.go
  pkg/datadogclient/client.go
Labels: enhancement

#1698 make generate
  .devcontainer/devcontainer.json
  .github/CODEOWNERS
  .github/workflows/build.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/main.yml
  .github/workflows/pr-linter.yml
  .github/workflows/release.yaml
  api/datadoghq/common/datadogpodautoscaler_types.go
  api/datadoghq/common/zz_generated.deepcopy.go
  api/datadoghq/v1alpha1/datadoggenericresource_types.go
  api/datadoghq/v1alpha1/datadoggenericresource_validation.go
  api/datadoghq/v1alpha1/datadogpodautoscaler_types.go
  api/datadoghq/v1alpha1/zz_generated.deepcopy.go
  api/datadoghq/v1alpha1/zz_generated.openapi.go
  api/datadoghq/v1alpha2/datadogpodautoscaler_conversion.go
  api/datadoghq/v1alpha2/datadogpodautoscaler_conversion_test.go
  api/datadoghq/v1alpha2/datadogpodautoscaler_types.go
  api/datadoghq/v1alpha2/zz_generated.deepcopy.go
  api/datadoghq/v2alpha1/datadogagent_types.go
  api/go.mod
  api/utils/utils.go
  config/crd/bases/v1/datadoghq.com_datadogagentinternals.yaml
  config/crd/bases/v1/datadoghq.com_datadogagentinternals_v1alpha1.json
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1/datadoghq.com_datadogagents_v2alpha1.json
  config/crd/bases/v1/datadoghq.com_datadoggenericresources.yaml
  config/crd/bases/v1/datadoghq.com_datadoggenericresources_v1alpha1.json
  config/crd/bases/v1/datadoghq.com_datadogpodautoscalers.yaml
  config/crd/bases/v1/datadoghq.com_datadogpodautoscalers_v1alpha1.json
  config/crd/bases/v1/datadoghq.com_datadogpodautoscalers_v1alpha2.json
  docs/configuration.v2alpha1.md
  internal/controller/datadogagent/defaults/datadogagent_default.go
  internal/controller/datadogagent/override/global.go
  internal/controller/datadogagent/override/global_test.go
  internal/controller/datadoggenericresource/controller.go
  internal/controller/datadoggenericresource/controller_test.go
  internal/controller/datadoggenericresource/finalizer_test.go
  internal/controller/datadoggenericresource/monitors.go
  internal/controller/datadoggenericresource/synthetics_test.go
  internal/controller/datadoggenericresource/utils.go
  internal/controller/datadoggenericresource/utils_test.go
  pkg/datadogclient/client.go
  pkg/testutils/builder.go
Labels: dependencies, qa/skip-qa

#1695 (documentation) Update DatadogGenericResource contribute documentation
  docs/datadog_generic_resource_dev.md
  examples/datadoggenericresource/monitor-sample.yaml
Labels: documentation, qa/skip-qa, mergequeue-status: in_progress

#1697 Fix parsing group resource to allow groups with periods
  internal/controller/datadogagent/feature/enabledefault/rbac.go
  internal/controller/datadogagent/feature/enabledefault/rbac_test.go
Labels: enhancement

#1701 Update bundle and manager config from v1.12
  bundle/manifests/datadog-operator.clusterserviceversion.yaml
  bundle/manifests/datadoghq.com_datadogagentprofiles.yaml
  bundle/manifests/datadoghq.com_datadogagents.yaml
  bundle/manifests/datadoghq.com_datadoggenericresources.yaml
  bundle/manifests/datadoghq.com_datadogpodautoscalers.yaml
  config/manager/kustomization.yaml
Labels: dependencies, qa/skip-qa

#1709 Add Gitlab job to run redhat preflight check on rcs
  .gitlab-ci.yml
  Makefile
Labels: tooling, qa/skip-qa

#1716 update podresources mount to only be in agent container
  internal/controller/datadogagent/override/global.go
  internal/controller/datadogagent/override/global_test.go
Labels: enhancement

#1717 [v1.13][cherry-pick] update podresources mount to only be in agent container (#1716)
  internal/controller/datadogagent/override/global.go
  internal/controller/datadogagent/override/global_test.go
Labels: enhancement, qa/skip-qa

#1553 feat(error tracking): add core agent and error tracking standalone settings
  api/datadoghq/v2alpha1/datadogagent_types.go
  api/datadoghq/v2alpha1/zz_generated.deepcopy.go
  api/datadoghq/v2alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1/datadoghq.com_datadogagents_v2alpha1.json
  docs/configuration.v2alpha1.md
  examples/datadogagent/datadog-agent-with-error-tracking-standalone.yaml
  internal/controller/datadogagent/common/envvar.go
  internal/controller/datadogagent/component/clusterchecksrunner/default.go
  internal/controller/datadogagent/defaults/datadogagent_default.go
  internal/controller/datadogagent/defaults/datadogagent_default_test.go
  internal/controller/datadogagent/feature/apm/feature.go
  internal/controller/datadogagent/feature/apm/feature_test.go
  pkg/testutils/builder.go
Labels: enhancement

#1720 bump golang to 1.23.6
  .github/workflows/build.yml
  .github/workflows/main.yml
  .github/workflows/release.yaml
  .gitlab-ci.yml
  Dockerfile
  api/go.mod
  check-operator.Dockerfile
  go.mod
  go.work
  hack/update-golang.sh
  test/e2e/go.mod
Labels: tooling, qa/skip-qa

#1723 bump default agent images to 7.63.0 (#1722)
  pkg/defaulting/images.go
Labels: enhancement, qa/skip-qa

#1728 Update OTel agent image
  internal/controller/datadogagent/component/agent/default.go
  pkg/defaulting/images.go
Labels: enhancement

#1729 Update OTel agent image (#1728)
  internal/controller/datadogagent/component/agent/default.go
  pkg/defaulting/images.go
Labels: enhancement, qa/skip-qa

#1731 Generate fips image compiled with Go boringcrypto
  .gitlab-ci.yml
  Dockerfile
  Makefile
  internal/controller/fipsonly.go
Labels: tooling, qa/skip-qa

#1670 api/datadoghq/v2alpha1: add support for SSI targets
  api/datadoghq/v2alpha1/datadogagent_types.go
  api/datadoghq/v2alpha1/zz_generated.deepcopy.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1/datadoghq.com_datadogagents_v2alpha1.json
  docs/configuration.v2alpha1.md
  internal/controller/datadogagent/feature/apm/envvar.go
  internal/controller/datadogagent/feature/apm/feature.go
  internal/controller/datadogagent/feature/apm/feature_test.go
  pkg/defaulting/images.go
  pkg/testutils/builder.go
Labels: enhancement

#1734 api/datadoghq/v2alpha1: add support for SSI targets (#1670)
  api/datadoghq/v2alpha1/datadogagent_types.go
  api/datadoghq/v2alpha1/zz_generated.deepcopy.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1/datadoghq.com_datadogagents_v2alpha1.json
  docs/configuration.v2alpha1.md
  internal/controller/datadogagent/feature/apm/envvar.go
  internal/controller/datadogagent/feature/apm/feature.go
  internal/controller/datadogagent/feature/apm/feature_test.go
  pkg/defaulting/images.go
  pkg/testutils/builder.go
Labels: enhancement, qa/skip-qa

#1732 Add gitlab workflows to publish fips images
  .gitlab-ci.yml
  Makefile
Labels: tooling, qa/skip-qa

#1735 bump kustomize to 5.6.0
  Makefile
Labels: tooling, qa/skip-qa

#1737 Generate fips image compiled with Go boringcrypto (#1731)
  .gitlab-ci.yml
  Dockerfile
  Makefile
  internal/controller/fipsonly.go
Labels: tooling, qa/skip-qa

#1738 Add gitlab workflows to publish fips images (#1732)
  .gitlab-ci.yml
  Makefile
Labels: tooling, qa/skip-qa

#1739 release v1.13.0-rc.2
  bundle-community-operators/manifests/datadog-operator.clusterserviceversion.yaml
  bundle-community-operators/manifests/datadoghq.com_datadogagents.yaml
  bundle/manifests/datadog-operator.clusterserviceversion.yaml
  bundle/manifests/datadoghq.com_datadogagents.yaml
  config/manager/kustomization.yaml
Labels: enhancement, qa/skip-qa

#1740 Update check_preflight_redhat_image image tag
  .gitlab-ci.yml
Labels: bug, qa/skip-qa

#1741 Update check_preflight_redhat_image image tag (#1740)
  .gitlab-ci.yml
Labels: bug, qa/skip-qa

#1742 Remove IsReadOnly from dashboard
  internal/controller/datadogdashboard/dashboard.go
  internal/controller/datadogdashboard/dashboard_test.go
Labels: bug

#1744 bump default agent images to 7.63.2
  pkg/defaulting/images.go
Labels: enhancement

#1747 Cherry-pick: bump 7.63.2 (#1744)
  pkg/defaulting/images.go
Labels: enhancement, qa/skip-qa, mergequeue-status: in_progress

#1748 Pass fips image tag to internal fips template
  .gitlab-ci.yml
Labels: tooling, qa/skip-qa
