Repository DataDog/datadog-operator, pull requests merged in 2025-09, with the labels that each got.

#2056 Update EKS add-on for Operator 1.16
  marketplaces/addon_manifest.yaml
  marketplaces/charts/operator-eks-addon/Chart.yaml
  marketplaces/charts/operator-eks-addon/README.md
  marketplaces/update-addon-chart.sh
Labels: tooling, qa/skip-qa

#2152 add permission for argorollouts and karpenter
  config/rbac/role.yaml
  internal/controller/datadogagent/feature/orchestratorexplorer/rbac.go
  internal/controller/datadogagent_controller.go
  pkg/kubernetes/rbac/const.go
Labels: enhancement

#2158 Release v1.18.0-rc.3
  bundle-community-operators/manifests/datadog-operator.clusterserviceversion.yaml
  bundle/manifests/datadog-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
Labels: enhancement, qa/skip-qa

#2164 README: add link to configuration page
  docs/installation.md
Labels: documentation, qa/skip-qa

#2163 [CWS] clean up unused security agent features
  internal/controller/datadogagent/feature/cws/feature.go
  internal/controller/datadogagent/feature/cws/feature_test.go
Labels: enhancement

#2169 release v1.18.0-rc.4
  bundle-community-operators/manifests/datadog-operator.clusterserviceversion.yaml
  bundle/manifests/datadog-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
Labels: enhancement, qa/skip-qa

#2176 v1.18.0 bundle
  bundle/manifests/datadog-operator.clusterserviceversion.yaml
  bundle/manifests/datadoghq.com_datadogagentinternals.yaml
  bundle/manifests/datadoghq.com_datadogagentprofiles.yaml
  bundle/manifests/datadoghq.com_datadogagents.yaml
  bundle/manifests/datadoghq.com_datadogpodautoscalers.yaml
  config/manager/kustomization.yaml
Labels: dependencies, qa/skip-qa

#2182 Update EKS add-on for Operator 1.17
  marketplaces/addon_manifest.yaml
  marketplaces/charts/operator-eks-addon/Chart.yaml
  marketplaces/charts/operator-eks-addon/README.md
  marketplaces/charts/operator-eks-addon/aws_mp_configuration_schema.json
Labels: tooling, qa/skip-qa

#2181 EKS add-on release for 1.18.0
  marketplaces/addon_manifest.yaml
  marketplaces/charts/operator-eks-addon/Chart.yaml
  marketplaces/charts/operator-eks-addon/README.md
Labels: tooling, qa/skip-qa

#2191 [AGENTONB-2523] Set `resourceVersion` in PodDisruptionBudget reconciliation
  internal/controller/datadogagent/store/store.go
Labels: bug

#2196 Metadata change doc suggestions
  README.md
  docs/agent_metadata_changes.md
Labels: documentation, qa/skip-qa

#2200 [metrics-forwarder] Use official go client for Validation and sending events
  LICENSE-3rdparty.csv
  go.mod
  go.sum
  pkg/controller/utils/datadog/metrics_forwarder.go
  pkg/controller/utils/datadog/metrics_forwarder_test.go
Labels: enhancement

#2174 Autoscaling based on custom metric query
  api/datadoghq/common/datadogpodautoscaler_types.go
  api/datadoghq/common/zz_generated.deepcopy.go
  api/datadoghq/v1alpha2/datadogpodautoscaler_types.go
  api/datadoghq/v1alpha2/zz_generated.deepcopy.go
  config/crd/bases/v1/datadoghq.com_datadogpodautoscalers.yaml
  config/crd/bases/v1/datadoghq.com_datadogpodautoscalers_v1alpha1.json
  config/crd/bases/v1/datadoghq.com_datadogpodautoscalers_v1alpha2.json
Labels: enhancement, mergequeue-status: rejected

#2148 [metrics-forwarder] Use official go client and add origins
  LICENSE-3rdparty.csv
  go.mod
  go.sum
  pkg/controller/utils/datadog/metrics_forwarder.go
  pkg/controller/utils/datadog/metrics_forwarder_test.go
Labels: enhancement
