Repository DataDog/datadog-operator, pull requests merged in 2025-08, with the labels that each got.

#2092 [SINT-3831] fix dd-octo-sts policy
  .github/chainguard/self.release.create-release.sts.yaml
Labels: tooling, qa/skip-qa, mergequeue-status: in_progress

#2098 [SINT-3831] use dd-octo-sts for backport workflow
  .github/chainguard/self.backport-pr.create-pr.sts.yaml
  .github/workflows/backport-pr.yml
Labels: tooling, qa/skip-qa, mergequeue-status: in_progress

#2099 [AGENTRUN-610] Update FIPS proxy version references to 1.1.15
  pkg/images/images.go
Labels: enhancement, mergequeue-status: in_progress

#2100 [e2e] Bump test-infra-definitions version
  .gitlab-ci.yml
  go.work.sum
  test/e2e/go.mod
  test/e2e/go.sum
Labels: tooling, qa/skip-qa, mergequeue-status: removed

#2088 Add process-agent and trace-agent support to experimental GKE Autopilot
  internal/controller/datadogagent/common/const.go
  internal/controller/datadogagent/controller_v2_test.go
  internal/controller/datadogagent/experimental/autopilot.go
  internal/controller/datadogagent/feature/admissioncontroller/const.go
  internal/controller/datadogagent/feature/admissioncontroller/feature.go
  internal/controller/datadogagent/feature/apm/feature.go
  internal/controller/datadogagent/feature/dogstatsd/feature.go
Labels: enhancement

#2108 GPUM: set DD_GPU_MONITORING_ENABLED in the core agent
  internal/controller/datadogagent/feature/gpu/feature.go
  internal/controller/datadogagent/feature/gpu/feature_test.go
Labels: bug, mergequeue-status: rejected

#2112 Update bundle for v1.17.0
  bundle/manifests/datadog-operator.clusterserviceversion.yaml
  bundle/manifests/datadoghq.com_datadogagentinternals.yaml
  bundle/manifests/datadoghq.com_datadogagentprofiles.yaml
  bundle/manifests/datadoghq.com_datadogagents.yaml
  bundle/manifests/datadoghq.com_datadogmonitors.yaml
  bundle/manifests/datadoghq.com_datadogpodautoscalers.yaml
  config/manager/kustomization.yaml
Labels: dependencies, qa/skip-qa

#2046 update datadogmonitor controller to use object reconciler
  go.work.sum
  internal/controller/datadogmonitor/controller.go
  internal/controller/datadogmonitor/controller_test.go
  internal/controller/datadogmonitor/monitor_test.go
  internal/controller/datadogmonitor_controller.go
Labels: refactoring

#2117 Add etcd cert checks for control plane monitoring tests
  internal/controller/datadogagent/controller_v2_test.go
  internal/controller/datadogagent/feature/controlplanemonitoring/feature.go
Labels: enhancement, qa/skip-qa

#2124 CAP-2779 update orchestrator check RBAC
  config/rbac/role.yaml
  internal/controller/datadogagent/feature/orchestratorexplorer/rbac.go
  internal/controller/datadogagent_controller.go
Labels: enhancement, mergequeue-status: rejected

#2127 Remove old e2e tests references
  Makefile
  config/e2e/kustomization.yaml
  config/e2e/rc-e2e-manager.yaml
  test/e2e/common.go
  test/e2e/kind_test.go
  test/e2e/main.go
  test/e2e/manifests/autodiscovery-annotation.yaml
  test/e2e/manifests/datadog-agent-ccr-enabled.yaml
  test/e2e/manifests/datadog-agent-logs.yaml
  test/e2e/manifests/datadog-agent-minimum.yaml
  test/e2e/manifests/datadog-agent-rc-updater.yaml
  test/e2e/rc-updater/api/client.go
  test/e2e/rc-updater/api/ddsql.go
  test/e2e/rc-updater/api/updater.go
  test/e2e/rc-updater/common.go
  test/e2e/rc_updater_test.go
Labels: tooling, qa/skip-qa

#2132 Mount control plane checks to subfolders
  internal/controller/datadogagent/controller_v2_test.go
  internal/controller/datadogagent/feature/controlplanemonitoring/const.go
  internal/controller/datadogagent/feature/controlplanemonitoring/feature.go
  internal/controller/datadogagent/feature/controlplanemonitoring/feature_test.go
Labels: bug, enhancement

#2144 [AGENTRUN-678] Update FIPS proxy version references to 1.1.16
  pkg/images/images.go
Labels: enhancement, mergequeue-status: in_progress

#2131 Add retries to e2e tests CI jobs
  .gitlab-ci.yml
Labels: tooling, qa/skip-qa
