Repository DataDog/datadog-operator, pull requests merged in 2025-07, with the labels that each got.

#2024 [CECO-2070] Change dda/component/dca signature and remove ddai/component
  internal/controller/datadogagent/component/clusteragent/default.go
  internal/controller/datadogagent/component/clusteragent/default_test.go
  internal/controller/datadogagent/controller_reconcile_dca.go
  internal/controller/datadogagentinternal/component/agent/const.go
  internal/controller/datadogagentinternal/component/agent/default.go
  internal/controller/datadogagentinternal/component/agent/envvar.go
  internal/controller/datadogagentinternal/component/agent/new.go
  internal/controller/datadogagentinternal/component/agent/rbac.go
  internal/controller/datadogagentinternal/component/clusteragent/const.go
  internal/controller/datadogagentinternal/component/clusteragent/default.go
  internal/controller/datadogagentinternal/component/clusteragent/default_test.go
  internal/controller/datadogagentinternal/component/clusteragent/envvar.go
  internal/controller/datadogagentinternal/component/clusteragent/rbac.go
  internal/controller/datadogagentinternal/component/clusteragent/rbac_test.go
  internal/controller/datadogagentinternal/component/clusteragent/utils.go
  internal/controller/datadogagentinternal/component/clusterchecksrunner/const.go
  internal/controller/datadogagentinternal/component/clusterchecksrunner/default.go
  internal/controller/datadogagentinternal/component/clusterchecksrunner/default_test.go
  internal/controller/datadogagentinternal/component/clusterchecksrunner/envvar.go
  internal/controller/datadogagentinternal/component/clusterchecksrunner/rbac.go
  internal/controller/datadogagentinternal/component/objects/network.go
  internal/controller/datadogagentinternal/component/utils.go
  internal/controller/datadogagentinternal/component/utils_test.go
  internal/controller/datadogagentinternal/controller.go
  internal/controller/datadogagentinternal/controller_reconcile_agent.go
  internal/controller/datadogagentinternal/controller_reconcile_agent_test.go
  internal/controller/datadogagentinternal/controller_reconcile_ccr.go
  internal/controller/datadogagentinternal/controller_reconcile_dca.go
  internal/controller/datadogagentinternal/controller_v2_test.go
  internal/controller/datadogagentinternal/finalizer_test.go
  internal/controller/datadogagentinternal/global/dependencies.go
  internal/controller/datadogagentinternal/override/dependencies.go
  internal/controller/setup.go
Labels: refactoring, qa/skip-qa

#2025 [CECO-2070] Change dda/override signature and remove ddai/override
  internal/controller/datadogagent/controller_reconcile_v2_helpers.go
  internal/controller/datadogagent/override/dependencies.go
  internal/controller/datadogagent/override/dependencies_test.go
  internal/controller/datadogagentinternal/controller_reconcile_agent.go
  internal/controller/datadogagentinternal/controller_reconcile_ccr.go
  internal/controller/datadogagentinternal/controller_reconcile_dca.go
  internal/controller/datadogagentinternal/controller_reconcile_v2_helpers.go
  internal/controller/datadogagentinternal/override/const.go
  internal/controller/datadogagentinternal/override/container.go
  internal/controller/datadogagentinternal/override/container_test.go
  internal/controller/datadogagentinternal/override/daemonset.go
  internal/controller/datadogagentinternal/override/daemonset_test.go
  internal/controller/datadogagentinternal/override/dependencies.go
  internal/controller/datadogagentinternal/override/dependencies_test.go
  internal/controller/datadogagentinternal/override/deploymentspec.go
  internal/controller/datadogagentinternal/override/deploymentspec_test.go
  internal/controller/datadogagentinternal/override/doc.go
  internal/controller/datadogagentinternal/override/podtemplatespec.go
  internal/controller/datadogagentinternal/override/podtemplatespec_test.go
  internal/controller/datadogagentinternal/override/utils.go
Labels: refactoring, qa/skip-qa

#2033 [CECO-2270] Rework dda/global signatures to be DDA agnostic and remove ddai/global
  internal/controller/datadogagent/controller_reconcile_agent.go
  internal/controller/datadogagent/controller_reconcile_ccr.go
  internal/controller/datadogagent/controller_reconcile_dca.go
  internal/controller/datadogagent/controller_reconcile_v2_helpers.go
  internal/controller/datadogagent/dependencies.go
  internal/controller/datadogagent/global/agent.go
  internal/controller/datadogagent/global/clusteragent.go
  internal/controller/datadogagent/global/clusterchecksrunner.go
  internal/controller/datadogagent/global/dependencies.go
  internal/controller/datadogagent/global/fips.go
  internal/controller/datadogagent/global/fips_test.go
  internal/controller/datadogagent/global/global.go
  internal/controller/datadogagent/global/global_test.go
  internal/controller/datadogagent/global/utils.go
  internal/controller/datadogagent/global/utils_test.go
  internal/controller/datadogagentinternal/controller_reconcile_agent.go
  internal/controller/datadogagentinternal/controller_reconcile_ccr.go
  internal/controller/datadogagentinternal/controller_reconcile_dca.go
  internal/controller/datadogagentinternal/controller_reconcile_v2_helpers.go
  internal/controller/datadogagentinternal/global/agent.go
  internal/controller/datadogagentinternal/global/clusteragent.go
  internal/controller/datadogagentinternal/global/clusterchecksrunner.go
  internal/controller/datadogagentinternal/global/const.go
  internal/controller/datadogagentinternal/global/dependencies.go
  internal/controller/datadogagentinternal/global/envvar.go
  internal/controller/datadogagentinternal/global/fips.go
  internal/controller/datadogagentinternal/global/fips_test.go
  internal/controller/datadogagentinternal/global/global.go
  internal/controller/datadogagentinternal/global/global_test.go
  internal/controller/datadogagentinternal/global/utils.go
  internal/controller/datadogagentinternal/global/utils_test.go
Labels: refactoring, qa/skip-qa

#1855 Add service ports for otel-agent
  internal/controller/datadogagent/feature/otelcollector/feature.go
  internal/controller/datadogagent/feature/otelcollector/feature_test.go
Labels: enhancement, mergequeue-status: removed

#1949 Add support for CustomSchedule option in DatadogMonitor
  api/datadoghq/v1alpha1/datadogmonitor_types.go
  api/datadoghq/v1alpha1/zz_generated.deepcopy.go
  api/datadoghq/v1alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogmonitors.yaml
  config/crd/bases/v1/datadoghq.com_datadogmonitors_v1alpha1.json
  internal/controller/datadogmonitor/monitor.go
  internal/controller/datadogmonitor/monitor_test.go
Labels: enhancement

#2038 Remove DDAI markers for role generation - they were duplicated from DDA
  internal/controller/datadogagentinternal_controller.go
Labels: enhancement, qa/skip-qa

#2035 [CECO-2321][DatadogAgentInternal] Delete DDAIs if disabled
  cmd/main.go
  internal/controller/setup.go
  pkg/kubernetes/rbac/const.go
Labels: enhancement, qa/skip-qa

#2031 [CECO-2312] Add control plane monitoring for EKS
  internal/controller/datadogagent/controller_reconcile_dca.go
  internal/controller/datadogagent/controller_reconcile_v2_helpers.go
  internal/controller/datadogagent/feature/controlplanemonitoring/configmap.go
  internal/controller/datadogagent/feature/controlplanemonitoring/configmap_test.go
  internal/controller/datadogagent/feature/controlplanemonitoring/const.go
  internal/controller/datadogagent/feature/controlplanemonitoring/feature.go
  internal/controller/datadogagent/feature/controlplanemonitoring/feature_test.go
Labels: enhancement

#1999 add metadata forwarder
  cmd/main.go
  config/manager/manager.yaml
  internal/controller/datadogagent/component/clusterchecksrunner/default.go
  internal/controller/datadogagent/component/clusterchecksrunner/envvar.go
  internal/controller/setup.go
  internal/controller/suite_v2_test.go
  pkg/constants/envvar.go
  pkg/controller/utils/metadata/metadata_forwarder.go
  pkg/version/version.go
Labels: enhancement

#2047 fix dd_url handling
  pkg/controller/utils/metadata/metadata_forwarder.go
  pkg/controller/utils/metadata/metadata_forwarder_test.go
Labels: bug

#2050 Add missing debugfs mount for GPU monitoring
  internal/controller/datadogagent/feature/gpu/feature.go
  internal/controller/datadogagent/feature/gpu/feature_test.go
Labels: bug, mergequeue-status: rejected

#2058 Bump golang.org/x/oauth2 from 0.24.0 to 0.27.0
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: dependencies, qa/skip-qa

#2062 [metrics forwarder] add fallback for getting object kind
  pkg/controller/utils/datadog/metrics_forwarder.go
Labels: enhancement

#2063 update default agent images to 7.68.2
  pkg/images/images.go
Labels: enhancement

#2067 [metadata forwarder] fix requestURL, add test
  pkg/controller/utils/metadata/metadata_forwarder.go
  pkg/controller/utils/metadata/metadata_forwarder_test.go
Labels: bug

#2054 Update label selector
  api/datadoghq/common/const.go
  config/rbac/role.yaml
  internal/controller/datadogagent/common/utils.go
  internal/controller/datadogagent/component/agent/default.go
  internal/controller/datadogagent/controller_reconcile_agent.go
  internal/controller/datadogagent/controller_reconcile_v2_common.go
  internal/controller/datadogagent/controller_reconcile_v2_common_test.go
  internal/controller/datadogagent/utils.go
  internal/controller/datadogagent_controller.go
  internal/controller/datadogagentinternal/controller_reconcile_agent.go
Labels: enhancement

#2068 [CONS-7468] add replicationcontroller get permission to the dca admission controller
  internal/controller/datadogagent/feature/admissioncontroller/rbac.go
Labels: enhancement

#2071 Update network policy metadata
  internal/controller/datadogagent/component/objects/network.go
Labels: enhancement

#2075 [datadogpodautoscalers] Increase max stabilization window/scaling period from 30m to 1h
  api/datadoghq/common/datadogpodautoscaler_types.go
  config/crd/bases/v1/datadoghq.com_datadogpodautoscalers.yaml
  config/crd/bases/v1/datadoghq.com_datadogpodautoscalers_v1alpha1.json
  config/crd/bases/v1/datadoghq.com_datadogpodautoscalers_v1alpha2.json
Labels: enhancement

#2042 Add controller level tests for OTEL image handling
  internal/controller/datadogagent/controller_v2_test.go
Labels: tooling, qa/skip-qa

#2079 [metrics forwarder] move log line
  pkg/controller/utils/datadog/metrics_forwarder.go
Labels: refactoring, qa/skip-qa

#2080 [e2e] update oauth2 to 0.27.0
  go.work.sum
  test/e2e/go.mod
  test/e2e/go.sum
Labels: dependencies

#2078 [AGENTONB-2318][DatadogAgentInternal] Update DDAI DS selectors like DDA
  internal/controller/datadogagentinternal/controller_reconcile_agent.go
Labels: bug

#2077 Add experimental GKE Autopilot support
  config/rbac/role.yaml
  internal/controller/datadogagent/controller_v2_test.go
  internal/controller/datadogagent/ddai_test.go
  internal/controller/datadogagent/experimental/autopilot.go
  internal/controller/datadogagent/experimental/const.go
  internal/controller/datadogagent/experimental/utils.go
  internal/controller/datadogagent/global/global.go
  internal/controller/datadogagent/profile_test.go
  internal/controller/datadogagent_controller.go
  pkg/allowlistsynchronizer/allowlistsynchronizer.go
Labels: enhancement

#2087 release v1.17.0-rc.3
  bundle-community-operators/manifests/datadog-operator.clusterserviceversion.yaml
  bundle/manifests/datadog-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
Labels: enhancement, qa/skip-qa
