Repository DataDog/datadog-operator, pull requests merged in 2025-06, with the labels that each got.

#1940 Copy google-marketplace chart from datadog-agent
  marketplaces/charts/google-marketplace/Dockerfile
  marketplaces/charts/google-marketplace/README.md
  marketplaces/charts/google-marketplace/chart/datadog-mp/Chart.yaml
  marketplaces/charts/google-marketplace/chart/datadog-mp/charts/datadog-operator-2.9.1.tgz
  marketplaces/charts/google-marketplace/chart/datadog-mp/requirements.lock
  marketplaces/charts/google-marketplace/chart/datadog-mp/requirements.yaml
  marketplaces/charts/google-marketplace/chart/datadog-mp/templates/application.yaml
  marketplaces/charts/google-marketplace/chart/datadog-mp/templates/datadog-agent.yaml
  marketplaces/charts/google-marketplace/chart/datadog-mp/templates/manifests.yaml
  marketplaces/charts/google-marketplace/chart/datadog-mp/values.yaml
  marketplaces/charts/google-marketplace/publish-marketplace.sh
  marketplaces/charts/google-marketplace/schema-test.yaml
  marketplaces/charts/google-marketplace/schema.yaml
  marketplaces/charts/google-marketplace/test-marketplace.sh
Labels: tooling, qa/skip-qa, mergequeue-status: rejected

#1950 [CECO-2270] Use DatadogAgentSpec in defaults and remove ddai/defaults
  internal/controller/datadogagent/controller_reconcile_dca_test.go
  internal/controller/datadogagent/controller_reconcile_v2.go
  internal/controller/datadogagent/defaults/datadogagent_default.go
  internal/controller/datadogagentinternal/controller_reconcile_dca_test.go
  internal/controller/datadogagentinternal/controller_reconcile_v2.go
  internal/controller/datadogagentinternal/defaults/datadogagent_default.go
  internal/controller/datadogagentinternal/defaults/datadogagent_default_test.go
  pkg/testutils/builder.go
  pkg/testutils/ddai_builder.go
Labels: refactoring, qa/skip-qa

#1955 [CECO-2270] Modify pkg/constants/utils.go to make it generic, and remove DDAI specific
  internal/controller/datadogagent/component/clusteragent/default.go
  internal/controller/datadogagent/feature/admissioncontroller/feature.go
  internal/controller/datadogagent/feature/apm/feature.go
  internal/controller/datadogagent/feature/autoscaling/feature.go
  internal/controller/datadogagent/feature/clusterchecks/feature.go
  internal/controller/datadogagent/feature/cspm/feature.go
  internal/controller/datadogagent/feature/dogstatsd/feature.go
  internal/controller/datadogagent/feature/eventcollection/feature.go
  internal/controller/datadogagent/feature/externalmetrics/feature.go
  internal/controller/datadogagent/feature/helmcheck/feature.go
  internal/controller/datadogagent/feature/kubernetesstatecore/feature.go
  internal/controller/datadogagent/feature/orchestratorexplorer/feature.go
  internal/controller/datadogagent/feature/otlp/feature.go
  internal/controller/datadogagent/global/dependencies.go
  internal/controller/datadogagent/override/dependencies.go
  internal/controller/datadogagent/override/dependencies_test.go
  internal/controller/datadogagentinternal/component/clusteragent/default.go
  internal/controller/datadogagentinternal/feature/admissioncontroller/feature.go
  internal/controller/datadogagentinternal/feature/apm/feature.go
  internal/controller/datadogagentinternal/feature/autoscaling/feature.go
  internal/controller/datadogagentinternal/feature/clusterchecks/feature.go
  internal/controller/datadogagentinternal/feature/cspm/feature.go
  internal/controller/datadogagentinternal/feature/dogstatsd/feature.go
  internal/controller/datadogagentinternal/feature/eventcollection/feature.go
  internal/controller/datadogagentinternal/feature/externalmetrics/feature.go
  internal/controller/datadogagentinternal/feature/helmcheck/feature.go
  internal/controller/datadogagentinternal/feature/kubernetesstatecore/feature.go
  internal/controller/datadogagentinternal/feature/orchestratorexplorer/feature.go
  internal/controller/datadogagentinternal/feature/otlp/feature.go
  internal/controller/datadogagentinternal/global/dependencies.go
  internal/controller/datadogagentinternal/override/dependencies.go
  internal/controller/datadogagentinternal/override/dependencies_test.go
  pkg/constants/utils.go
  pkg/constants/utils_test.go
Labels: refactoring, qa/skip-qa

#1960 Use DDA-generated ConfigMap to store APM telemetry info
  internal/controller/datadogagent/common/const.go
  internal/controller/datadogagent/component/agent/default.go
  internal/controller/datadogagent/component/clusteragent/default.go
  internal/controller/datadogagent/component/clusteragent/default_test.go
  internal/controller/datadogagent/dependencies.go
  internal/controller/datadogagent/global/dependencies.go
  internal/controller/datadogagentinternal/component/agent/default.go
  internal/controller/datadogagentinternal/component/clusteragent/default.go
  internal/controller/datadogagentinternal/component/clusteragent/default_test.go
  internal/controller/datadogagentinternal/global/dependencies.go
Labels: refactoring, qa/skip-qa, mergequeue-status: in_progress

#1941 Allow container port overrides
  api/datadoghq/v2alpha1/datadogagent_types.go
  api/datadoghq/v2alpha1/zz_generated.deepcopy.go
  api/datadoghq/v2alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagentinternals.yaml
  config/crd/bases/v1/datadoghq.com_datadogagentinternals_v1alpha1.json
  config/crd/bases/v1/datadoghq.com_datadogagentprofiles.yaml
  config/crd/bases/v1/datadoghq.com_datadogagentprofiles_v1alpha1.json
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1/datadoghq.com_datadogagents_v2alpha1.json
  docs/configuration.v2alpha1.md
  internal/controller/datadogagent/override/container.go
  internal/controller/datadogagent/override/container_test.go
Labels: enhancement

#1958 [feature/autoscaling] Enable local fallback by default when autoscaling enabled
  internal/controller/datadogagent/feature/autoscaling/const.go
  internal/controller/datadogagent/feature/autoscaling/envvar.go
  internal/controller/datadogagent/feature/autoscaling/feature.go
  internal/controller/datadogagent/feature/autoscaling/feature_test.go
  internal/controller/datadogagentinternal/feature/autoscaling/const.go
  internal/controller/datadogagentinternal/feature/autoscaling/envvar.go
  internal/controller/datadogagentinternal/feature/autoscaling/feature.go
  internal/controller/datadogagentinternal/feature/autoscaling/feature_test.go
Labels: enhancement, mergequeue-status: rejected

#1961 Bump golang.org/x/net to v0.40.0
  go.work.sum
  test/e2e/go.mod
Labels: dependencies

#1966 (chore) Disable `exportloopref` linter due to depreciation
  .golangci.toml
Labels: tooling, qa/skip-qa

#1965 Force oci mediatype
  Makefile
Labels: tooling, qa/skip-qa

#1970 release v1.15.1-rc.1
  bundle-community-operators/manifests/datadog-operator.clusterserviceversion.yaml
  bundle/manifests/datadog-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
Labels: enhancement, qa/skip-qa

#1969 Revert "Release v1.16.0-rc.1"
  bundle-community-operators/manifests/datadog-operator-webhook-service_v1_service.yaml
  bundle-community-operators/manifests/datadog-operator.clusterserviceversion.yaml
  bundle-community-operators/manifests/datadoghq.com_datadogagentinternals.yaml
  bundle-community-operators/manifests/datadoghq.com_datadogagentprofiles.yaml
  bundle-community-operators/manifests/datadoghq.com_datadogagents.yaml
  bundle-community-operators/manifests/datadoghq.com_datadogdashboards.yaml
  bundle-community-operators/manifests/datadoghq.com_datadoggenericresources.yaml
  bundle-community-operators/manifests/datadoghq.com_datadogmetrics.yaml
  bundle-community-operators/manifests/datadoghq.com_datadogmonitors.yaml
  bundle-community-operators/manifests/datadoghq.com_datadogpodautoscalers.yaml
  bundle-community-operators/manifests/datadoghq.com_datadogslos.yaml
  bundle-community-operators/metadata/annotations.yaml
  bundle-community-operators/tests/scorecard/config.yaml
  bundle/manifests/datadog-operator.clusterserviceversion.yaml
  bundle/manifests/datadoghq.com_datadogagentinternals.yaml
  bundle/manifests/datadoghq.com_datadogagentprofiles.yaml
  bundle/manifests/datadoghq.com_datadogagents.yaml
  bundle/manifests/datadoghq.com_datadogdashboards.yaml
  bundle/manifests/datadoghq.com_datadogmonitors.yaml
  bundle/manifests/datadoghq.com_datadogpodautoscalers.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/datadog-operator.clusterserviceversion.yaml
Labels: dependencies, mergequeue-status: in_progress

#1973 [CECO-2270] Change dda/experimental signatures and remove ddai/experimental
  internal/controller/datadogagent/experimental/image.go
  internal/controller/datadogagent/experimental/utils.go
  internal/controller/datadogagentinternal/controller_reconcile_agent.go
  internal/controller/datadogagentinternal/experimental/const.go
  internal/controller/datadogagentinternal/experimental/image.go
  internal/controller/datadogagentinternal/experimental/image_test.go
  internal/controller/datadogagentinternal/experimental/utils.go
Labels: refactoring, qa/skip-qa

#1975 release v1.15.1
  bundle-community-operators/manifests/datadog-operator.clusterserviceversion.yaml
  bundle/manifests/datadog-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
Labels: enhancement, qa/skip-qa

#1974 Keep DS same between DDA and DDAI
  api/datadoghq/common/const.go
  internal/controller/datadogagent/controller_reconcile_agent.go
  internal/controller/datadogagent/controller_reconcile_agent_test.go
  internal/controller/datadogagent/ddai.go
  internal/controller/datadogagent/ddai_test.go
  internal/controller/datadogagentinternal/controller_reconcile_agent.go
  internal/controller/datadogagentinternal/controller_reconcile_agent_test.go
  internal/controller/datadogagentinternal/controller_reconcile_v2.go
  internal/controller/datadogagentinternal/controller_reconcile_v2_helpers.go
Labels: bug, qa/skip-qa

#1979 bug: Disable process config in clc runner
  internal/controller/datadogagent/component/clusterchecksrunner/default.go
Labels: bug, qa/skip-qa, mergequeue-status: in_progress

#1990 Cherry-pick 1978
  repository.datadog.yml
Labels: tooling, qa/skip-qa

#1991 Fix mergegate exception bot email addresses
  repository.datadog.yml
Labels: bug, tooling, qa/skip-qa, backport/v1.16

#1983 New OTEL Image
  internal/controller/datadogagentinternal/component/agent/default.go
  pkg/images/images.go
Labels: bug

#1993 Update default Agent to 7.67.0
  pkg/images/images.go
Labels: enhancement

#1994 Release v1.16.0-rc.2
  bundle-community-operators/manifests/datadog-operator.clusterserviceversion.yaml
  bundle/manifests/datadog-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
Labels: enhancement, qa/skip-qa

#2000 E2E enable allow_failure on release branches
  .gitlab-ci.yml
Labels: tooling, qa/skip-qa, backport/v1.16

#2001 Keep DDA ownerref for profile DDAI
  internal/controller/datadogagent/profile.go
  internal/controller/datadogagent/profile_test.go
Labels: refactoring, qa/skip-qa

#2002 [Documentation] Clarify how to onboard to DAP using Helm chart
  docs/datadog_agent_profiles.md
Labels: documentation, qa/skip-qa

#2004 [CECO-2029][DatadogAgentInternal] Add profile label to non-default profile DDAIs and do not create EDS if non-default profile DDAI
  internal/controller/datadogagent/profile.go
  internal/controller/datadogagent/profile_test.go
  internal/controller/datadogagentinternal/controller_reconcile_agent.go
  internal/controller/datadogagentinternal/controller_reconcile_agent_test.go
Labels: bug, qa/skip-qa

#2005 Pass DDAI with DDA name to store
  internal/controller/datadogagentinternal/controller_reconcile_v2.go
Labels: bug, qa/skip-qa

#2008 [CECO-2029][DatadogAgentInternal] Fix CCR when enabling DDAI
  internal/controller/datadogagent/override/ddai_utils.go
  internal/controller/datadogagent/override/ddai_utils_test.go
  internal/controller/datadogagentinternal/component/clusterchecksrunner/default.go
Labels: bug, qa/skip-qa, mergequeue-status: rejected

#2010 Merge DDAI affinities instead of replacing when using profiles
  internal/controller/datadogagent/ddai_test.go
  internal/controller/datadogagent/profile.go
  internal/controller/datadogagent/profile_test.go
Labels: bug, qa/skip-qa

#1980 Otel Agent: add support for multi items in configmap
  examples/datadogagent/datadog-agent-with-otel-agent-configmap-multi-item.yaml
  internal/controller/datadogagent/component/agent/default.go
  internal/controller/datadogagent/feature/otelcollector/feature.go
  internal/controller/datadogagent/feature/otelcollector/feature_test.go
  pkg/testutils/builder.go
Labels: enhancement

#2013 [CECO-2315] Update gitlab base image to use ubuntu 22.04
  .gitlab-ci.yml
Labels: tooling, qa/skip-qa

#2009 Move fieldmanager
  internal/controller/datadogagent/controller.go
  internal/controller/datadogagent/controller_reconcile_v2.go
  internal/controller/datadogagent/merge.go
  internal/controller/datadogagent/merge_test.go
  internal/controller/datadogagent/profile.go
  internal/controller/datadogagent/profile_test.go
Labels: enhancement, qa/skip-qa

#2017 Release v1.16.0
  bundle-community-operators/manifests/datadog-operator.clusterserviceversion.yaml
  bundle/manifests/datadog-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
Labels: dependencies, qa/skip-qa
