Repository DataDog/datadog-operator, pull requests merged in 2025-04, with the labels that each got.

#1837 (chore) merge main in dda
  .gitlab-ci.yml
  api/datadoghq/v1alpha1/datadogdashboard_types.go
  cmd/kubectl-datadog/clusteragent/leader/leader.go
  config/crd/bases/v1/datadoghq.com_datadogdashboards.yaml
  config/crd/bases/v1/datadoghq.com_datadogdashboards_v1alpha1.json
  internal/controller/datadogagent/common/envvar.go
  internal/controller/datadogagent/component/clusterchecksrunner/default.go
  internal/controller/datadogagent/feature/enabledefault/feature.go
  internal/controller/datadogagent/feature/gpu/feature.go
  internal/controller/datadogagent/feature/gpu/feature_test.go
  internal/controller/datadogagent/global/agent.go
  internal/controller/datadogagent/global/envvar.go
  internal/controller/datadogagent/global/global_test.go
  pkg/defaulting/images.go
  test/e2e/provisioners/kind.go
Labels: refactoring, qa/skip-qa

#1839 [defaulting] clean up unused image methods
  internal/controller/datadogagent/component/agent/default.go
  internal/controller/datadogagent/component/clusteragent/default.go
  internal/controller/datadogagent/component/clusterchecksrunner/default.go
  pkg/constants/utils_test.go
  pkg/defaulting/images.go
  pkg/defaulting/images_test.go
Labels: refactoring

#1841 Add permission for PDB
  internal/controller/datadogagent/feature/orchestratorexplorer/rbac.go
Labels: bug, qa/skip-qa, mergequeue-status: in_progress, backport/v1.14

#1845 [autoscaling] Move to v1alpha2 as only supported version for Cluster Agent 7.64+
  api/datadoghq/v1alpha1/datadogpodautoscaler_types.go
  api/datadoghq/v1alpha2/datadogpodautoscaler_types.go
  config/crd/bases/v1/datadoghq.com_datadogpodautoscalers.yaml
  internal/controller/datadogagent/feature/orchestratorexplorer/feature.go
  internal/controller/datadogagent/feature/orchestratorexplorer/feature_test.go
  pkg/testutils/builder.go
Labels: enhancement

#1840 Add feature flag when GPU monitoring is enabled
  internal/controller/datadogagent/feature/gpu/envvar.go
  internal/controller/datadogagent/feature/gpu/feature.go
  internal/controller/datadogagent/feature/gpu/feature_test.go
Labels: enhancement, mergequeue-status: in_progress

#1848 Add permission for PDB (#1841)
  internal/controller/datadogagent/feature/orchestratorexplorer/rbac.go
Labels: bug, qa/skip-qa

#1850 Add commit signing to backport workflow PRs
  .github/workflows/backport-pr.yml
Labels: tooling, qa/skip-qa

#1847 Bump Agent to 7.64.3
  pkg/defaulting/images.go
Labels: enhancement, backport/v1.14

#1852 Bump Agent to 7.64.3 (#1847)
  pkg/defaulting/images.go
Labels: enhancement

#1853 Release v1.14.0-rc.2
  bundle-community-operators/manifests/datadog-operator.clusterserviceversion.yaml
  bundle/manifests/datadog-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
Labels: enhancement, qa/skip-qa

#1856 [tooling] Add milestone to automated backport PR
  .github/workflows/backport-pr.yml
Labels: tooling, qa/skip-qa

#1857 [BARX-910] Add a config flag for SlowStartAdditiveIncrease
  cmd/main.go
  internal/controller/setup.go
Labels: bug, qa/skip-qa

#1849 [autoscaling] Move to v1alpha2 as only supported version for Cluster Agent 7.64+ (#1845)
  api/datadoghq/v1alpha1/datadogpodautoscaler_types.go
  api/datadoghq/v1alpha2/datadogpodautoscaler_types.go
  config/crd/bases/v1/datadoghq.com_datadogpodautoscalers.yaml
  internal/controller/datadogagent/feature/orchestratorexplorer/feature.go
  internal/controller/datadogagent/feature/orchestratorexplorer/feature_test.go
  pkg/testutils/builder.go
Labels: enhancement

#1861 [backport 1.14] Add flag to configure SlowStartAdditiveIncrease
  cmd/main.go
  internal/controller/setup.go
Labels: bug, qa/skip-qa, mergequeue-status: removed

#1862 update seccomp profile to fix k3s
  internal/controller/datadogagent/feature/enabledefault/configmap.go
Labels: bug

#1863 update seccomp profile to fix k3s (#1862)
  internal/controller/datadogagent/feature/enabledefault/configmap.go
Labels: bug

#1867 [autoscaling] Add external recommendation source
  api/datadoghq/common/datadogpodautoscaler_types.go
Labels: enhancement, qa/skip-qa

#1866 Move install info and seccomp out of enabledefault feature
  internal/controller/datadogagent/component/agent/default.go
  internal/controller/datadogagent/component/clusteragent/default_test.go
  internal/controller/datadogagent/component/clusteragent/envvar.go
  internal/controller/datadogagent/controller_reconcile_v2.go
  internal/controller/datadogagent/controller_reconcile_v2_helpers.go
  internal/controller/datadogagent/controller_reconcile_v2_helpers_test.go
  internal/controller/datadogagent/feature/admissioncontroller/feature.go
  internal/controller/datadogagent/feature/apm/feature.go
  internal/controller/datadogagent/feature/asm/feature.go
  internal/controller/datadogagent/feature/autoscaling/feature.go
  internal/controller/datadogagent/feature/clusterchecks/feature.go
  internal/controller/datadogagent/feature/cspm/feature.go
  internal/controller/datadogagent/feature/cws/feature.go
  internal/controller/datadogagent/feature/dogstatsd/feature.go
  internal/controller/datadogagent/feature/dummy/feature.go
  internal/controller/datadogagent/feature/ebpfcheck/feature.go
  internal/controller/datadogagent/feature/enabledefault/configmap.go
  internal/controller/datadogagent/feature/enabledefault/const.go
  internal/controller/datadogagent/feature/enabledefault/envvar.go
  internal/controller/datadogagent/feature/enabledefault/feature.go
  internal/controller/datadogagent/feature/enabledefault/feature_test.go
  internal/controller/datadogagent/feature/eventcollection/feature.go
  internal/controller/datadogagent/feature/externalmetrics/feature.go
  internal/controller/datadogagent/feature/gpu/feature.go
  internal/controller/datadogagent/feature/helmcheck/feature.go
  internal/controller/datadogagent/feature/kubernetesstatecore/feature.go
  internal/controller/datadogagent/feature/livecontainer/feature.go
  internal/controller/datadogagent/feature/liveprocess/feature.go
  internal/controller/datadogagent/feature/logcollection/feature.go
  internal/controller/datadogagent/feature/npm/feature.go
  internal/controller/datadogagent/feature/oomkill/feature.go
  internal/controller/datadogagent/feature/orchestratorexplorer/feature.go
  internal/controller/datadogagent/feature/otelcollector/feature.go
  internal/controller/datadogagent/feature/otlp/feature.go
  internal/controller/datadogagent/feature/processdiscovery/feature.go
  internal/controller/datadogagent/feature/prometheusscrape/feature.go
  internal/controller/datadogagent/feature/remoteconfig/feature.go
  internal/controller/datadogagent/feature/sbom/feature.go
  internal/controller/datadogagent/feature/servicediscovery/feature.go
  internal/controller/datadogagent/feature/tcpqueuelength/feature.go
  internal/controller/datadogagent/feature/test/testsuite.go
  internal/controller/datadogagent/feature/types.go
  internal/controller/datadogagent/feature/usm/feature.go
  internal/controller/datadogagent/finalizer.go
  internal/controller/datadogagent/global/const.go
  internal/controller/datadogagent/global/dependencies.go
  internal/controller/datadogagent/global/global.go
  internal/controller/datadogagent/global/global_test.go
  internal/controller/datadogagent/global/utils.go
  internal/controller/datadogagent/global/utils_test.go
Labels: bug, refactoring, qa/skip-qa

#1870 DDAI status
  api/datadoghq/v1alpha1/datadogagentinternal_types.go
  api/datadoghq/v1alpha1/zz_generated.deepcopy.go
  api/datadoghq/v1alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagentinternals.yaml
  config/crd/bases/v1/datadoghq.com_datadogagentinternals_v1alpha1.json
Labels: enhancement, qa/skip-qa

#1714 Include golangci-lint in fmt Make target
  Makefile
  internal/controller/datadogagent/feature/gpu/feature.go
  internal/controller/datadogagent/override/envvar.go
Labels: tooling, qa/skip-qa

#1761 fix SBOM feature env vars applying to all agents instead of just core
  internal/controller/datadogagent/feature/sbom/feature.go
  internal/controller/datadogagent/feature/sbom/feature_test.go
Labels: bug, mergequeue-status: in_progress

#1873 Merge main into dda 2025-04-22
  .github/workflows/backport-pr.yml
  Makefile
  api/datadoghq/common/datadogpodautoscaler_types.go
  api/datadoghq/v1alpha1/datadogpodautoscaler_types.go
  api/datadoghq/v1alpha2/datadogpodautoscaler_types.go
  api/datadoghq/v1alpha2/zz_generated.deepcopy.go
  cmd/main.go
  config/crd/bases/v1/datadoghq.com_datadogpodautoscalers.yaml
  config/crd/bases/v1/datadoghq.com_datadogpodautoscalers_v1alpha2.json
  config/crd/bases/v1/datadoghq.com_datadogpodautoscalers_v2alpha1.json
  internal/controller/datadogagent/component/agent/default.go
  internal/controller/datadogagent/component/clusteragent/default.go
  internal/controller/datadogagent/component/clusterchecksrunner/default.go
  internal/controller/datadogagent/feature/enabledefault/feature.go
  internal/controller/datadogagent/feature/gpu/envvar.go
  internal/controller/datadogagent/feature/gpu/feature.go
  internal/controller/datadogagent/feature/gpu/feature_test.go
  internal/controller/datadogagent/feature/orchestratorexplorer/feature.go
  internal/controller/datadogagent/feature/orchestratorexplorer/feature_test.go
  internal/controller/datadogagent/feature/orchestratorexplorer/rbac.go
  internal/controller/setup.go
  pkg/defaulting/images.go
  pkg/defaulting/images_test.go
  pkg/testutils/builder.go
Labels: refactoring, qa/skip-qa

#1874 Delete v1beta1 CRDs from repo
  config/crd/bases/v1beta1/datadoghq.com_datadogagentprofiles.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogmetrics.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogmonitors.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogpodautoscalers.yaml
  config/crd/bases/v1beta1/datadoghq.com_datadogslos.yaml
  hack/patch-crds.sh
Labels: tooling, qa/skip-qa

#1876 release v1.14.0
  bundle-community-operators/manifests/datadog-operator.clusterserviceversion.yaml
  bundle/manifests/datadog-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
Labels: enhancement, qa/skip-qa

#1872 readme clean-up
  README.md
Labels: documentation, qa/skip-qa

#1885 Add permission for endpointslices
  config/rbac/role.yaml
  internal/controller/datadogagent/feature/orchestratorexplorer/rbac.go
  internal/controller/datadogagent_controller.go
  pkg/kubernetes/rbac/const.go
Labels: enhancement, mergequeue-status: in_progress

#1886 (chore) Add cursor to gitignore, e.g. for rules
  .gitignore
Labels: tooling, qa/skip-qa

#1712 Remove deprecated dependencies
  .golangci.toml
  api/datadoghq/v1alpha1/datadogslo_validation_test.go
  api/go.mod
  api/go.sum
  api/utils/utils.go
  internal/controller/datadogagent/utils.go
Labels: dependencies, qa/skip-qa
