Repository DataDog/datadog-operator, pull requests merged in 2025-05, with the labels that each got.

#1869 add syscalls to seccomp profile for trivy SBOM host scans
  internal/controller/datadogagent/component/agent/default.go
Labels: bug

#1888 Set DD_OTELCOLLECTOR_ENABLED in otel-agent container
  internal/controller/datadogagent/feature/otelcollector/feature.go
  internal/controller/datadogagent/feature/otelcollector/feature_test.go
Labels: bug

#1713 Run golangci-lint in api and e2e too
  Makefile
  api/datadoghq/v1alpha1/datadogagentprofile_types.go
  api/datadoghq/v1alpha1/datadogdashboard_types.go
  api/datadoghq/v1alpha1/datadogpodautoscaler_types.go
  api/datadoghq/v1alpha2/datadogpodautoscaler_types.go
  test/e2e/provisioners/common.go
  test/e2e/provisioners/kind.go
  test/e2e/rc-updater/api/client.go
  test/e2e/rc-updater/api/ddsql.go
  test/e2e/rc-updater/api/updater.go
  test/e2e/rc-updater/common.go
  test/e2e/tests/utils/utils.go
Labels: tooling, qa/skip-qa

#1854 SLO deletion, ignore 404 error in finalizer
  internal/controller/datadogslo/controller.go
  internal/controller/datadogslo/slo.go
Labels: bug

#1889 Clean up finalizer
  config/rbac/role.yaml
  internal/controller/datadogagent/finalizer.go
  internal/controller/datadogagent/finalizer_test.go
  internal/controller/datadogagent/store/store.go
  internal/controller/datadogagent/store/store_test.go
  internal/controller/datadogagent_controller.go
Labels: refactoring

#1900 small fix for FIPS configuration
  internal/controller/datadogagent/global/global.go
Labels: bug

#1901 Update agent image to 7.65.0
  pkg/defaulting/images.go
Labels: enhancement, mergequeue-status: in_progress

#1905 Refactor defaulting pkg into images
  cmd/kubectl-datadog/agent/upgrade/upgrade.go
  cmd/kubectl-datadog/clusteragent/upgrade/upgrade.go
  cmd/kubectl-datadog/clusteragent/upgrade/upgrade_test.go
  internal/controller/datadogagent/common/utils.go
  internal/controller/datadogagent/common/utils_test.go
  internal/controller/datadogagent/component/agent/default.go
  internal/controller/datadogagent/component/clusteragent/default.go
  internal/controller/datadogagent/component/clusteragent/default_test.go
  internal/controller/datadogagent/component/clusterchecksrunner/default.go
  internal/controller/datadogagent/defaults/datadogagent_default.go
  internal/controller/datadogagent/defaults/datadogagent_default_test.go
  internal/controller/datadogagent/experimental/image.go
  internal/controller/datadogagent/experimental/image_test.go
  internal/controller/datadogagent/feature/admissioncontroller/feature.go
  internal/controller/datadogagent/feature/admissioncontroller/feature_test.go
  internal/controller/datadogagent/feature/apm/feature.go
  internal/controller/datadogagent/feature/utils/utils.go
  internal/controller/datadogagent/global/agent.go
  internal/controller/datadogagent/global/clusteragent.go
  internal/controller/datadogagent/global/clusterchecksrunner.go
  internal/controller/datadogagent/global/fips.go
  internal/controller/datadogagent/global/global.go
  internal/controller/datadogagent/global/utils.go
  internal/controller/datadogagent/override/podtemplatespec.go
  internal/controller/datadogagent/override/podtemplatespec_test.go
  pkg/defaulting/images.go
  pkg/defaulting/images_test.go
  pkg/images/images.go
  pkg/images/images_test.go
  pkg/testutils/builder.go
Labels: enhancement, refactoring

#1907 [Doc] Documents that otel-agent is not enabled by default
  api/datadoghq/v2alpha1/datadogagent_types.go
  api/datadoghq/v2alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1/datadoghq.com_datadogagents_v2alpha1.json
  docs/configuration.v2alpha1.md
Labels: documentation, qa/skip-qa

#1912 [tooling] fix backport workflow pr number fetching
  .github/workflows/backport-pr.yml
Labels: tooling, qa/skip-qa

#1911 Fix Autoscaling ApplyMode conversion
  api/datadoghq/v1alpha2/datadogpodautoscaler_conversion.go
  api/datadoghq/v1alpha2/datadogpodautoscaler_conversion_test.go
Labels: bug, qa/skip-qa

#1914 Update agent images to 7.65.2
  pkg/images/images.go
Labels: enhancement

#1913 Add support for secret_refresh_interval
  api/datadoghq/v2alpha1/datadogagent_types.go
  api/datadoghq/v2alpha1/zz_generated.deepcopy.go
  api/datadoghq/v2alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1/datadoghq.com_datadogagents_v2alpha1.json
  docs/configuration.v2alpha1.md
  internal/controller/datadogagent/global/envvar.go
  internal/controller/datadogagent/global/global.go
  internal/controller/datadogagent/global/global_test.go
  pkg/testutils/builder.go
Labels: enhancement, mergequeue-status: rejected

#1916 if otel collector is enabled, use full agent image
  internal/controller/datadogagent/component/agent/default.go
  internal/controller/datadogagent/feature/otelcollector/feature.go
  internal/controller/datadogagent/feature/otelcollector/feature_test.go
  internal/controller/datadogagent/feature/test/testsuite.go
  pkg/images/images.go
  pkg/images/images_test.go
Labels: enhancement

#1918 add skip-qa label to backport PRs by default
  .github/workflows/backport-pr.yml
Labels: tooling, qa/skip-qa

#1920 Bump crypto and net packages
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  go.work.sum
  test/e2e/go.mod
  test/e2e/go.sum
Labels: dependencies, qa/skip-qa

#1925 release v1.15.0-rc.2
  bundle-community-operators/manifests/datadog-operator.clusterserviceversion.yaml
  bundle-community-operators/manifests/datadoghq.com_datadogagents.yaml
  bundle/manifests/datadog-operator.clusterserviceversion.yaml
  bundle/manifests/datadoghq.com_datadogagents.yaml
  config/manager/kustomization.yaml
Labels: enhancement, qa/skip-qa

#1928 Update to Go 1.23.8
  .github/workflows/build.yml
  .github/workflows/main.yml
  .github/workflows/release.yaml
  .gitlab-ci.yml
  Dockerfile
  api/go.mod
  check-operator.Dockerfile
  go.mod
  go.work
  hack/update-golang.sh
  test/e2e/go.mod
Labels: dependencies, qa/skip-qa

#1906 Move EKS add-on wrapper chart
  marketplaces/.gitignore
  marketplaces/addon_manifest.yaml
  marketplaces/charts/operator-eks-addon/CHANGELOG.md
  marketplaces/charts/operator-eks-addon/Chart.lock
  marketplaces/charts/operator-eks-addon/Chart.yaml
  marketplaces/charts/operator-eks-addon/README.md
  marketplaces/charts/operator-eks-addon/aws_mp_configuration.schema.json
  marketplaces/charts/operator-eks-addon/values.yaml
  marketplaces/update-addon-chart.sh
Labels: tooling, qa/skip-qa, mergequeue-status: rejected

#1935 Limit service equality check
  internal/controller/datadogagent/global/dependencies.go
  internal/controller/datadogagent/merger/service.go
  pkg/equality/equality.go
Labels: enhancement
