Repository DataDog/datadog-operator, pull requests merged in 2025-03, with the labels that each got.

#1751 Pass fips image tag to internal fips template (#1748)
  .gitlab-ci.yml
Labels: tooling, qa/skip-qa

#1757 add doc page for slos
  docs/datadog_slo.md
Labels: documentation, qa/skip-qa

#1746 [CECO-2016] Small controller reconcile v2 refactor
  internal/controller/datadogagent/controller_reconcile_v2.go
  internal/controller/datadogagent/controller_reconcile_v2_helpers.go
  internal/controller/datadogagent/controller_reconcile_v2_helpers_test.go
Labels: refactoring, qa/skip-qa

#1762 Agent/DCA bump 7.63.3 (#1760)
  pkg/defaulting/images.go
Labels: enhancement, qa/skip-qa, mergequeue-status: in_progress

#1763 update default fips-proxy image version to 1.1.8
  pkg/defaulting/images.go
Labels: enhancement, qa/skip-qa, mergequeue-status: in_progress

#1768 small fix for error handling
  internal/controller/datadogagent/controller_reconcile_v2.go
Labels: bug

#1770 Fix internal fips image tag
  .gitlab-ci.yml
Labels: tooling

#1764 [CECO-2004] Always run e2e tests on release branches
  .gitlab-ci.yml
Labels: tooling, qa/skip-qa

#1771 [CECO-2004] Always run e2e tests on release branches (#1764)
  .gitlab-ci.yml
Labels: tooling, qa/skip-qa

#1774 Fix internal fips image tag (#1770)
  .gitlab-ci.yml
Labels: tooling, qa/skip-qa

#1758 Gate profile canary waits behind annotation
  internal/controller/datadogagent/controller_reconcile_v2_common.go
  internal/controller/datadogagent/controller_reconcile_v2_common_test.go
Labels: enhancement

#1767 Use `app.kubernetes.io/part-of` label to cleanup only owned ds/deployments
  internal/controller/datadogagent/controller_reconcile_agent.go
  internal/controller/datadogagent/controller_reconcile_agent_test.go
  internal/controller/datadogagent/controller_reconcile_ccr.go
  internal/controller/datadogagent/controller_reconcile_ccr_test.go
  internal/controller/datadogagent/controller_reconcile_dca.go
  internal/controller/datadogagent/controller_reconcile_dca_test.go
Labels: enhancement

#1766 [CECO-2013] Use `app.kubernetes.io/part-of` label to cleanup only owned ds/deployments
  internal/controller/datadogagent/controller_reconcile_agent.go
  internal/controller/datadogagent/controller_reconcile_agent_test.go
  internal/controller/datadogagent/controller_reconcile_ccr.go
  internal/controller/datadogagent/controller_reconcile_ccr_test.go
  internal/controller/datadogagent/controller_reconcile_dca.go
  internal/controller/datadogagent/controller_reconcile_dca_test.go
Labels: enhancement

#1775 Gate profile canary waits behind annotation (#1758)
  internal/controller/datadogagent/controller_reconcile_v2_common.go
  internal/controller/datadogagent/controller_reconcile_v2_common_test.go
Labels: enhancement, qa/skip-qa

#1776 release v1.13.0-rc.3
  bundle-community-operators/manifests/datadog-operator.clusterserviceversion.yaml
  bundle/manifests/datadog-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
Labels: enhancement, qa/skip-qa

#1778 Use object reconciler
  api/datadoghq/v2alpha1/datadogagent_validation.go
  internal/controller/datadogagent/controller.go
  internal/controller/datadogagent/controller_reconcile_v2.go
  internal/controller/datadogagent/controller_reconcile_v2_helpers.go
  internal/controller/datadogagent/controller_reconcile_v2_helpers_test.go
  internal/controller/datadogagent/controller_test.go
  internal/controller/datadogagent/controller_v2_test.go
  internal/controller/datadogagent/utils.go
  internal/controller/datadogagent_controller.go
  pkg/controller/utils/datadog/common.go
  pkg/controller/utils/datadog/metrics_forwarder.go
Labels: enhancement, qa/skip-qa

#1782 Pass TMPL_RELEASE_TAG in internal image build workflow
  .gitlab-ci.yml
Labels: tooling, qa/skip-qa

#1783 Pass TMPL_RELEASE_TAG in internal image build workflow (#1782)
  .gitlab-ci.yml
Labels: tooling, qa/skip-qa

#1784 release v1.13.0-rc.4
  bundle-community-operators/manifests/datadog-operator.clusterserviceversion.yaml
  bundle/manifests/datadog-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
Labels: enhancement, qa/skip-qa

#1715 Clean up integration tests
  .github/workflows/main.yml
  Makefile
  docs/how-to-contribute.md
  internal/controller/datadogagent_controller_profiles_test.go
  internal/controller/datadogagent_controller_test.go
  internal/controller/suite_v2_test.go
Labels: tooling

#1788 Revert "Pass TMPL_RELEASE_TAG in internal image build workflow (#1782)"
  .gitlab-ci.yml
Labels: tooling, qa/skip-qa

#1781 [feature/eventcollection] Don't set anything for the node agent
  internal/controller/datadogagent/feature/eventcollection/feature.go
Labels: enhancement, mergequeue-status: in_progress

#1793 fix typo in license dir on operator image
  Dockerfile
Labels: enhancement, qa/skip-qa

#1730 enhancement: per-container image override support
  api/datadoghq/v2alpha1/datadogagent_types.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1/datadoghq.com_datadogagents_v2alpha1.json
  docs/configuration.v2alpha1.md
  internal/controller/datadogagent/common/utils.go
  internal/controller/datadogagent/controller_reconcile_agent.go
  internal/controller/datadogagent/experimental/const.go
  internal/controller/datadogagent/experimental/image.go
  internal/controller/datadogagent/experimental/image_test.go
  internal/controller/datadogagent/experimental/utils.go
  internal/controller/datadogagent/override/podtemplatespec.go
Labels: enhancement

#1789 Move creds and dca token out of enabledefault
  internal/controller/datadogagent/controller_reconcile_agent.go
  internal/controller/datadogagent/controller_reconcile_ccr.go
  internal/controller/datadogagent/controller_reconcile_dca.go
  internal/controller/datadogagent/controller_reconcile_v2.go
  internal/controller/datadogagent/feature/enabledefault/envvar.go
  internal/controller/datadogagent/feature/enabledefault/feature.go
  internal/controller/datadogagent/override/envvar.go
  internal/controller/datadogagent/override/global.go
  internal/controller/datadogagent/override/global_test.go
  internal/controller/datadogagent/override/utils.go
  pkg/testutils/builder.go
Labels: refactoring, qa/skip-qa

#1790 Revert "Pass TMPL_RELEASE_TAG in internal image build workflow (#1782)" (#1788)
  .gitlab-ci.yml
Labels: tooling, qa/skip-qa

#1796 release v1.13.0
  bundle-community-operators/manifests/datadog-operator.clusterserviceversion.yaml
  bundle/manifests/datadog-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
Labels: enhancement, qa/skip-qa

#1780 add support for Service Discovery network stats collection
  api/datadoghq/v2alpha1/datadogagent_types.go
  api/datadoghq/v2alpha1/zz_generated.deepcopy.go
  bundle/manifests/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1/datadoghq.com_datadogagents_v2alpha1.json
  docs/configuration.v2alpha1.md
  examples/datadogagent/datadog-agent-all.yaml
  internal/controller/datadogagent/defaults/datadogagent_default.go
  internal/controller/datadogagent/defaults/datadogagent_default_test.go
  internal/controller/datadogagent/feature/servicediscovery/envvar.go
  internal/controller/datadogagent/feature/servicediscovery/feature.go
  internal/controller/datadogagent/feature/servicediscovery/feature_test.go
Labels: enhancement, mergequeue-status: in_progress

#1797 [tooling] use latest preflight version
  Makefile
  hack/install-openshift-preflight.sh
Labels: tooling

#1792 Allow disabling features that are enabled by default
  internal/controller/datadogagent/controller.go
  internal/controller/datadogagent/controller_reconcile_v2.go
  internal/controller/datadogagent/feature/admissioncontroller/feature.go
  internal/controller/datadogagent/feature/autoscaling/feature.go
  internal/controller/datadogagent/feature/clusterchecks/feature.go
  internal/controller/datadogagent/feature/cspm/feature.go
  internal/controller/datadogagent/feature/enabledefault/feature.go
  internal/controller/datadogagent/feature/eventcollection/feature.go
  internal/controller/datadogagent/feature/externalmetrics/feature.go
  internal/controller/datadogagent/feature/factory.go
  internal/controller/datadogagent/feature/helmcheck/feature.go
  internal/controller/datadogagent/feature/kubernetesstatecore/feature.go
  internal/controller/datadogagent/feature/orchestratorexplorer/envvar.go
  internal/controller/datadogagent/feature/orchestratorexplorer/feature.go
  internal/controller/datadogagent/feature/orchestratorexplorer/feature_test.go
  internal/controller/datadogagent/feature/remoteconfig/feature.go
  internal/controller/datadogagent/feature/test/factory_test.go
  internal/controller/datadogagent/feature/test/testsuite.go
  internal/controller/datadogagent/feature/types.go
  internal/controller/datadogagent/feature/types_test.go
  internal/controller/datadogagent/finalizer.go
Labels: enhancement, qa/skip-qa

#1795 Remove MonitoredObject
  internal/controller/datadogagent/controller_reconcile_v2.go
  internal/controller/datadogagent/controller_test.go
  pkg/controller/utils/datadog/common.go
  pkg/controller/utils/datadog/forwarders_manager.go
  pkg/controller/utils/datadog/metrics_forwarder.go
  pkg/controller/utils/datadog/metrics_forwarder_test.go
Labels: refactoring, qa/skip-qa

#1799 fixing links in docs
  docs/data_collected.md
  docs/installation.md
Labels: documentation, qa/skip-qa

#1786 [CECO-2084] Handle custom versions (not following semver) as always above minVersion
  pkg/utils/version.go
  pkg/utils/version_test.go
Labels: enhancement

#1798 Change Operator base image from ubi-minimal to ubi-micro
  Dockerfile
  check-operator.Dockerfile
Labels: tooling, qa/skip-qa

#1803 [tooling][gitlab] separate publishing latest images, tweak community operators job
  .gitlab-ci.yml
Labels: tooling, qa/skip-qa

#1807 [tooling] sort git tag by semver
  Makefile
Labels: tooling, qa/skip-qa

#1805 [Remote config feature] Agent & DCA are not required components, but need to be configured
  internal/controller/datadogagent/feature/remoteconfig/feature.go
Labels: enhancement, qa/skip-qa

#1804 servicediscovery: add support for eBPF runtime-compilation
  internal/controller/datadogagent/feature/servicediscovery/feature.go
  internal/controller/datadogagent/feature/servicediscovery/feature_test.go
Labels: enhancement, mergequeue-status: in_progress

#1811 [documentation] add example for configuring extra confd
  examples/datadogagent/datadog-agent-with-extra-confd.yaml
Labels: documentation, qa/skip-qa

#1808 Refactor global
  internal/controller/datadogagent/controller_reconcile_agent.go
  internal/controller/datadogagent/controller_reconcile_ccr.go
  internal/controller/datadogagent/controller_reconcile_dca.go
  internal/controller/datadogagent/controller_reconcile_v2.go
  internal/controller/datadogagent/controller_reconcile_v2_helpers.go
  internal/controller/datadogagent/global/agent.go
  internal/controller/datadogagent/global/clusteragent.go
  internal/controller/datadogagent/global/clusterchecksrunner.go
  internal/controller/datadogagent/global/const.go
  internal/controller/datadogagent/global/dependencies.go
  internal/controller/datadogagent/global/envvar.go
  internal/controller/datadogagent/global/fips.go
  internal/controller/datadogagent/global/fips_test.go
  internal/controller/datadogagent/global/global.go
  internal/controller/datadogagent/global/global_test.go
  internal/controller/datadogagent/global/utils.go
  internal/controller/datadogagent/override/container.go
  internal/controller/datadogagent/override/container_test.go
  internal/controller/datadogagent/override/global.go
  internal/controller/datadogagent/override/podtemplatespec_test.go
  internal/controller/datadogagent/override/utils.go
  pkg/constants/envvar.go
Labels: refactoring, qa/skip-qa

#1815 Remove ddai commit
  PROJECT
  api/datadoghq/v1alpha1/datadogagentinternal_types.go
  api/datadoghq/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/v1/datadoghq.com_datadogagentinternals.yaml
  config/crd/bases/v1/datadoghq.com_datadogagentinternals_v1alpha1.json
  config/crd/kustomization.yaml
  config/rbac/datadoghq_datadogagentinternal_editor_role.yaml
  config/rbac/datadoghq_datadogagentinternal_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/datadoghq_v1alpha1_datadogagentinternal.yaml
  internal/controller/datadogagentinternal/controller.go
  internal/controller/datadogagentinternal_controller.go
Labels: refactoring, qa/skip-qa

#1820 Add CA certificate bundle to ubi9-micro base
  Dockerfile
Labels: bug

#1819 [autoscaling] Make objectives required CRD v1alpha2
  api/datadoghq/v1alpha2/datadogpodautoscaler_types.go
  config/crd/bases/v1/datadoghq.com_datadogpodautoscalers.yaml
  config/crd/bases/v1/datadoghq.com_datadogpodautoscalers_v1alpha2.json
Labels: enhancement, qa/skip-qa

#1777 [CECO-2004] Run e2e tests in more conditions
  .gitlab-ci.yml
  test/e2e/tests/k8s_suite/k8s_suite_test.go
Labels: tooling, qa/skip-qa, backport/testing

#1822 [testing backport] noop change
  .github/workflows/backport-pr.yml
Labels: tooling, qa/skip-qa, backport/testing

#1825 more backport testing
  .github/workflows/backport-pr.yml
Labels: tooling, qa/skip-qa

#1821 [BARX-910] Allow to configure SlowStartAdditiveIncrease
  internal/controller/datadogagent/component/agent/new.go
Labels: enhancement, qa/skip-qa, mergequeue-status: in_progress

#1826 Update backport PR conditions
  .github/workflows/backport-pr.yml
Labels: tooling, qa/skip-qa

#1828 (chore) Change test-id to integer string id
  internal/controller/datadoggenericresource/synthetics_test.go
Labels: bug, qa/skip-qa

#1694 Add validations to DatadogMonitorSpec
  api/datadoghq/v1alpha1/datadogmonitor_types.go
  config/crd/bases/v1/datadoghq.com_datadogmonitors.yaml
  config/crd/bases/v1/datadoghq.com_datadogmonitors_v1alpha1.json
Labels: enhancement

#1829 [e2e] Disable e2e tests on nightly build
  .gitlab-ci.yml
Labels: bug, tooling, qa/skip-qa

#1769 [CECO-2005] Configure additional k8s versions for e2e CI
  .gitlab-ci.yml
  test/e2e/go.mod
  test/e2e/go.sum
Labels: tooling, qa/skip-qa

#1801 Enable pod-resources mount only with GPU monitoring enabled
  internal/controller/datadogagent/common/envvar.go
  internal/controller/datadogagent/feature/gpu/feature.go
  internal/controller/datadogagent/feature/gpu/feature_test.go
  internal/controller/datadogagent/override/envvar.go
  internal/controller/datadogagent/override/global.go
  internal/controller/datadogagent/override/global_test.go
Labels: enhancement

#1831 (chore) E2E: use m5.xlarge instead of default t3.medium
  .gitlab-ci.yml
  test/e2e/provisioners/kind.go
Labels: tooling, qa/skip-qa

#1830 update default fips-proxy image version to 1.1.9
  pkg/defaulting/images.go
Labels: enhancement, qa/skip-qa, mergequeue-status: in_progress

#1823 Add checksd volume to ccr init-config
  internal/controller/datadogagent/component/clusterchecksrunner/default.go
Labels: bug

#1704 Add validations to DatadogDashboardSpec
  api/datadoghq/v1alpha1/datadogdashboard_types.go
  config/crd/bases/v1/datadoghq.com_datadogdashboards.yaml
  config/crd/bases/v1/datadoghq.com_datadogdashboards_v1alpha1.json
Labels: enhancement

#1833 [kubectl plugin] Fallback to configmap leader attempt for `clusteragent` if lease failed
  cmd/kubectl-datadog/clusteragent/leader/leader.go
Labels: enhancement

#1834 Bump Agent to 7.64.1
  pkg/defaulting/images.go
Labels: enhancement
