Repository DataDog/datadog-operator, pull requests merged in 2025-01, with the labels that each got.

#1599 Update bundle and manager config from v1.11
  bundle/manifests/datadog-operator.clusterserviceversion.yaml
  bundle/manifests/datadoghq.com_datadogagentprofiles.yaml
  bundle/manifests/datadoghq.com_datadogagents.yaml
  bundle/manifests/datadoghq.com_datadogdashboards.yaml
  bundle/manifests/datadoghq.com_datadogmetrics.yaml
  bundle/manifests/datadoghq.com_datadogmonitors.yaml
  bundle/manifests/datadoghq.com_datadogpodautoscalers.yaml
  bundle/manifests/datadoghq.com_datadogslos.yaml
  config/manager/kustomization.yaml
Labels: dependencies, qa/skip-qa, mergequeue-status: in_progress

#1593 Add AWS kind E2E provisioner
  .gitlab-ci.yml
  Makefile
  bundle/manifests/datadog-operator.clusterserviceversion.yaml
  bundle/manifests/datadoghq.com_datadogagentprofiles.yaml
  bundle/manifests/datadoghq.com_datadogagents.yaml
  bundle/manifests/datadoghq.com_datadogdashboards.yaml
  bundle/manifests/datadoghq.com_datadogmetrics.yaml
  bundle/manifests/datadoghq.com_datadogmonitors.yaml
  bundle/manifests/datadoghq.com_datadogpodautoscalers.yaml
  bundle/manifests/datadoghq.com_datadogslos.yaml
  config/manager/kustomization.yaml
  go.mod
  go.sum
  go.work.sum
  test/e2e/common.go
  test/e2e/common/common.go
  test/e2e/go.mod
  test/e2e/go.sum
  test/e2e/kind_test.go
  test/e2e/manifests/new_manifests/autodiscovery-annotation.yaml
  test/e2e/manifests/new_manifests/datadog-agent-ccr-enabled.yaml
  test/e2e/manifests/new_manifests/datadog-agent-logs.yaml
  test/e2e/manifests/new_manifests/datadog-agent-minimum.yaml
  test/e2e/provisioners/common.go
  test/e2e/provisioners/kind.go
  test/e2e/provisioners/kindProvisioner.go
  test/e2e/rc-updater/api/client.go
  test/e2e/rc-updater/api/ddsql.go
  test/e2e/rc-updater/api/updater.go
  test/e2e/rc-updater/common.go
  test/e2e/rc_updater_test.go
  test/e2e/tests/k8sSuite/k8sSuite_test.go
  test/e2e/tests/k8s_suite/k8s_suite_test.go
  test/e2e/tests/k8s_suite/kind_aws_test.go
  test/e2e/tests/k8s_suite/kind_local_test.go
  test/e2e/tests/utils/utils.go
Labels: tooling, qa/skip-qa

#1547 Add make command to run a specific e2e test
  Makefile
  test/e2e/tests/k8s_suite/k8s_suite_test.go
Labels: tooling

#1607 Fix API violation from OTel Agent
  api/datadoghq/v2alpha1/datadogagent_types.go
  api/datadoghq/v2alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1/datadoghq.com_datadogagents_v2alpha1.json
  docs/configuration.v2alpha1.md
Labels: bug, qa/skip-qa

#1534 [CECO-1763] Controller for generic custom resource
  api/datadoghq/v1alpha1/datadoggenericresource_types.go
  api/datadoghq/v1alpha1/datadoggenericresource_validation.go
  api/datadoghq/v1alpha1/datadoggenericresource_validation_test.go
  api/datadoghq/v1alpha1/zz_generated.deepcopy.go
  api/datadoghq/v1alpha1/zz_generated.openapi.go
  cmd/main.go
  config/crd/bases/v1/datadoghq.com_datadoggenericresources.yaml
  config/crd/bases/v1/datadoghq.com_datadoggenericresources_v1alpha1.json
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_datadoghq_datadoggenericresources.yaml
  config/crd/patches/webhook_in_datadoghq_datadoggenericresources.yaml
  config/rbac/datadoghq_datadoggenericresource_editor_role.yaml
  config/rbac/datadoghq_datadoggenericresource_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/datadoghq_v1alpha1_datadoggenericresource.yaml
  config/samples/kustomization.yaml
  internal/controller/datadoggenericresource/controller.go
  internal/controller/datadoggenericresource/controller_test.go
  internal/controller/datadoggenericresource/finalizer.go
  internal/controller/datadoggenericresource/finalizer_test.go
  internal/controller/datadoggenericresource/notebooks.go
  internal/controller/datadoggenericresource/notebooks_test.go
  internal/controller/datadoggenericresource/synthetics.go
  internal/controller/datadoggenericresource/utils.go
  internal/controller/datadoggenericresource/utils_test.go
  internal/controller/datadoggenericresource_controller.go
  internal/controller/setup.go
  pkg/datadogclient/client.go
Labels: enhancement

#1603 Bump golang.org/x/net version
  go.mod
  go.sum
  go.work.sum
  test/e2e/go.mod
  test/e2e/go.sum
Labels: dependencies, qa/skip-qa

#1565 Create a go module for CRDs
  Dockerfile
  LICENSE-3rdparty.csv
  Makefile
  api/go.mod
  api/go.sum
  check-operator.Dockerfile
  go.mod
  go.work
  go.work.sum
  hack/update-golang.sh
  test/e2e/go.mod
Labels: enhancement

#1610 service discovery: Add missing cgroup mount
  internal/controller/datadogagent/feature/servicediscovery/feature.go
  internal/controller/datadogagent/feature/servicediscovery/feature_test.go
Labels: bug, mergequeue-status: in_progress

#1617 service discovery: Add missing cgroup mount (#1610)
  internal/controller/datadogagent/feature/servicediscovery/feature.go
  internal/controller/datadogagent/feature/servicediscovery/feature_test.go
Labels: bug

#1558 Require extendeddaemonset/api instead of whole EDS
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  go.work.sum
  test/e2e/common.go
  test/e2e/go.mod
  test/e2e/go.sum
Labels: enhancement

#1549 [CECO-1153] APM e2e test
  test/e2e/kind_test.go
  test/e2e/manifests/new_manifests/apm/datadog-agent-apm.yaml
  test/e2e/manifests/new_manifests/apm/tracegen-deploy.yaml
  test/e2e/tests/k8s_suite/k8s_suite_test.go
  test/e2e/tests/utils/utils.go
Labels: tooling, qa/skip-qa

#1619 make small adjustments to clusterrole
  config/rbac/role.yaml
  internal/controller/datadogagent_controller.go
Labels: enhancement

#1623 [conductor] disable build impact analysis
  service.datadog.yaml
Labels: tooling, qa/skip-qa

#1618 Move condition logic to main module
  api/go.mod
  api/go.sum
  go.sum
  internal/controller/datadogagent/controller_reconcile_agent.go
  internal/controller/datadogagent/controller_reconcile_ccr.go
  internal/controller/datadogagent/controller_reconcile_dca.go
  internal/controller/datadogagent/controller_reconcile_v2.go
  internal/controller/datadogagent/controller_reconcile_v2_common.go
  pkg/condition/condition.go
  pkg/condition/condition_test.go
  pkg/controller/utils/datadog/metrics_forwarder.go
Labels: enhancement

#1624 Remove support for otel annotation
  examples/datadogagent/datadog-agent-with-otel-agent-annotations.yaml
  internal/controller/datadogagent/feature/enabledefault/feature.go
  internal/controller/datadogagent/feature/test/factory_test.go
  internal/controller/datadogagent/feature/utils/utils.go
Labels: refactoring, mergequeue-status: removed

#1622 [default/images] Bump default agent/cluster agent version to 7.61.0
  pkg/defaulting/images.go
Labels: enhancement, mergequeue-status: removed

#1628 Add otel collector configdata annotations
  internal/controller/datadogagent/feature/otelcollector/configmap_test.go
  internal/controller/datadogagent/feature/otelcollector/feature.go
  internal/controller/datadogagent/feature/otelcollector/feature_test.go
Labels: bug

#1630 Add otel collector configdata annotations (#1628)
  internal/controller/datadogagent/feature/otelcollector/configmap_test.go
  internal/controller/datadogagent/feature/otelcollector/feature.go
  internal/controller/datadogagent/feature/otelcollector/feature_test.go
Labels: bug

#1629 Fix daemonset status duplication in DDA when DS can't be created
  internal/controller/datadogagent/controller_reconcile_agent.go
  internal/controller/datadogagent/controller_reconcile_v2_common.go
  pkg/condition/condition.go
  pkg/condition/condition_test.go
Labels: bug

#1632 Fix daemonset status duplication in DDA when DS can't be created (#1629)
  api/datadoghq/v2alpha1/condition.go
  api/datadoghq/v2alpha1/condition_test.go
  internal/controller/datadogagent/controller_reconcile_agent.go
  internal/controller/datadogagent/controller_reconcile_v2_common.go
Labels: bug

#1633 release v1.12.0-rc.2
  bundle-community-operators/manifests/datadog-operator.clusterserviceversion.yaml
  bundle/manifests/datadog-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
Labels: enhancement, qa/skip-qa

#1644 Update latest Agent and Cluster Agent version to 7.62.0
  pkg/defaulting/images.go
Labels: enhancement

#1645 Update latest agent and cluster agent version to 7.62.0 (#1644)
  pkg/defaulting/images.go
Labels: enhancement

#1601 Add support for GPU monitoring
  api/datadoghq/v2alpha1/datadogagent_types.go
  api/datadoghq/v2alpha1/zz_generated.deepcopy.go
  api/datadoghq/v2alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_datadogagents.yaml
  config/crd/bases/v1/datadoghq.com_datadogagents_v2alpha1.json
  docs/configuration.v2alpha1.md
  examples/datadogagent/datadog-agent-all.yaml
  internal/controller/datadogagent/controller.go
  internal/controller/datadogagent/defaults/datadogagent_default.go
  internal/controller/datadogagent/defaults/datadogagent_default_test.go
  internal/controller/datadogagent/feature/gpu/const.go
  internal/controller/datadogagent/feature/gpu/envvar.go
  internal/controller/datadogagent/feature/gpu/feature.go
  internal/controller/datadogagent/feature/gpu/feature_test.go
  internal/controller/datadogagent/feature/ids.go
  internal/controller/datadogagent/feature/test/factory_test.go
  internal/controller/datadogagent_controller_test.go
  internal/controller/testutils/agent.go
  pkg/testutils/builder.go
Labels: enhancement, mergequeue-status: in_progress

#1646 release v1.12.0-rc.3
  bundle-community-operators/manifests/datadog-operator.clusterserviceversion.yaml
  bundle/manifests/datadog-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
Labels: enhancement, qa/skip-qa

#1647 Bump datadog-agent dependencies
  .github/workflows/build.yml
  .github/workflows/main.yml
  .github/workflows/release.yaml
  .gitlab-ci.yml
  Dockerfile
  LICENSE-3rdparty.csv
  api/go.mod
  api/go.sum
  check-operator.Dockerfile
  go.mod
  go.sum
  go.work
  go.work.sum
  test/e2e/go.mod
  test/e2e/go.sum
Labels: tooling
